bridges = []
persistence_dir = '/tmp/tmp.mtLHYj3b0I/tryorama/l6kaOR'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'alice::columns::98b1c5cd-7224-4614-9640-e14f5b04b200'
public_address = 'HcSCJ37gctmODa9po9mZZ3K5k84HH4csaW3unIiHIcvc7cbgxtm969d3765y59i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::98b1c5cd-7224-4614-9640-e14f5b04b200'
public_address = 'HcSCjJ5kMmSBqgdxano998nCDzf4msqznJCucNC4Y4Xuvv55IKE73oA9Cpm4hrz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::98b1c5cd-7224-4614-9640-e14f5b04b200'
public_address = 'HcScI5hVeZdcia5bn754Q4VHpcJGG4rdbDeURnZYrkjhmm3pikwFDM544pBfuci'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmXFNSMV5ezLxwb4jNTKCDzQY5yYGcrXYsmugGnP5RQkLD'
id = 'columns-test'
uuid = '98b1c5cd-7224-4614-9640-e14f5b04b200'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmXMe9Qayk2bB9myT2gqEkMGxptphUXBzsCJC3rt9NeS2Z'
id = 'notes-test'
uuid = '98b1c5cd-7224-4614-9640-e14f5b04b200'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmaf7eG4k7bqg9A4DMicu9KsGAjgMcZW54RmK9d6s1AfLX'
id = 'tasks-test'
uuid = '98b1c5cd-7224-4614-9640-e14f5b04b200'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.mtLHYj3b0I/tryorama/l6kaOR/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.mtLHYj3b0I/tryorama/l6kaOR/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.mtLHYj3b0I/tryorama/l6kaOR/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
