bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/lqEKo3'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCjCrIgXisehtj53GzsjGfGVze8y744h6JsPqvDTgqwknjHf8o4QE85wucvri'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcScjwRKBtosa7f9i7TOk7Y94EbXbrdi88GWsw977f7ppDzgXav8Kuack34fnvi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcScj7zZiJcm3mdc5yCI8cPbIbpatzcuev8f5qy9zDMe8uirJrEQBOJ3Cu3n7cz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCjE3wrGqKmiq79tSkXEJ7DIspo9iaq98gvksXHvX6wj4pST88BrgpSFzitjr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCjBHap96w9cvojnu6Ky4e8O7M6M93WIZ93CvKq9wZpx8yUriCkdJHxgb3fqz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCirTMF8SU997b84BDc7QnzOKrh57z9e8aA6AJe8Hmq9syWMec9wyTofm3j3r'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmZ2TGpauVUoTTTPwmqNpwmCLcDavKr4utUxdJAmHXZfXE'
id = 'kanban-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmbL8eFNsa9UYtJY2iqRPWVfhHok46fdoYCAskt6gakegE'
id = 'notes-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeqVu6wrMg1KapacXdZDLr5CC4WkjMKYUMXdjubuHeDUE'
id = 'tasks-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmap2ypwmfw4DccYDrJDDZF8iGRbKNsMbcAV69NwRLQ5hG'
id = 'fields-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmW74wFsoGzCrYudphWBtHVFY6wfK5k5GrDLhXXEJj9C2g'
id = 'personalinformation-test::e3cff22c-e6b6-4b77-a4a5-ccfabc1b9932'
uuid = 'e3cff22c-e6b6-4b77-a4a5-ccfabc1b9932::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmSNFSC8iDvsCT8FUiFUFY97EZcTLaAnHmX6UsysFtzbdU'
id = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
uuid = '59280fe2-f7cb-43ec-9f20-e4d7cd883a8b::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/lqEKo3/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/lqEKo3/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/lqEKo3/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/lqEKo3/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::e3cff22c-e6b6-4b77-a4a5-ccfabc1b9932'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/lqEKo3/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/lqEKo3/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
