bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/eNofmi'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScic9ETRtudgw5agm3TohZ6V6MeeptdOCv3KqF8kfgyogvY4mVjMbcEqvfrvz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCJ5yKcbTezrmcqtT48KjNMJ4swyr3pOiZJ5rJVWa7njhnP4x89eGtSUpv4za'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCJ448M8SQqdnjajwgRkNfJochijuo4wDhSO48nRa778cuS4P7I7wCiQIs9ta'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCJra7NfHfgnczgoK7ZD4aVxXta9uvt6D9mGjKXYJd3a9wK3q4oB5KSVhhesz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScI6TCAR4P7Kq8335SNkgnicixrb88eGYNPgVo6Uowcti7Dt4ONciRXszttbi'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCjgxGRg6kjzy39vFWI7dxcsOxufw87xi4no5wF3NRzop8XdMP9mrVEpo7d9z'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmedGmoWrgruqTQo8CCbueViSHtygNqDGUe5UDuNMBw49J'
id = 'kanban-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYj38vX7snVRgUbRiYSnCSTeQ7rfXRTzPZnthyMGPVuy6'
id = 'notes-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmSkMFYYPAvptbPV4oHMR4jDRR1EZVjrHJy7xE4fqz9jtN'
id = 'tasks-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmZV4fqhTA68pJXXSwLqgDDvj9C4QE2in6H6Er8rk6n5cc'
id = 'fields-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmadQ8b6idZ7pPzPbsmqoJcJo16jb2WdqvkeoxcVJicWk4'
id = 'personalinformation-test::baf81b30-7663-4e8d-987a-164572deb7c5'
uuid = 'baf81b30-7663-4e8d-987a-164572deb7c5::460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmQKynt27wddsW3qw2SpKgXtToZBEFUZwvrUmHoozA5uN5'
id = 'freckles-test::cd82d866-2022-4b03-a303-35754cdab152'
uuid = 'cd82d866-2022-4b03-a303-35754cdab152::460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eNofmi/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eNofmi/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eNofmi/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eNofmi/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::baf81b30-7663-4e8d-987a-164572deb7c5'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eNofmi/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::cd82d866-2022-4b03-a303-35754cdab152'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eNofmi/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
