bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/vTs29t'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'phil::projects::b161e62b-0bb8-4ee3-8290-2d13a5a85743'
public_address = 'HcSCJ5H6r9uamg4tz6E6s35eM7n7oIJ3m6NUkXG7XoEdqs4gFrQ4AQV45DC6poz'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::b161e62b-0bb8-4ee3-8290-2d13a5a85743'
public_address = 'HcScjsmk5Aqvwob89ogK7uRbQFno7giko4fqHHc9kzknfxe8iZzD7TVXijvvrtz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::b161e62b-0bb8-4ee3-8290-2d13a5a85743'
public_address = 'HcScip4MqjQJaudmavGwm9ZrsYXtobxkeeHqjbgaYrgydqckiGFn89WZy6Sht8a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::b161e62b-0bb8-4ee3-8290-2d13a5a85743'
public_address = 'HcSci7KEQohQ6ggip9wB9HvppyUfvnjbaC99oNyND8k6Mww7FwpPf5nHmshnxfi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::b161e62b-0bb8-4ee3-8290-2d13a5a85743'
public_address = 'HcSCIG4MQ6HHi98dpxkXiqH6PX95c3tawN8Tbc8IvWijftncV9G5yOmfYwisk8i'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::b161e62b-0bb8-4ee3-8290-2d13a5a85743'
public_address = 'HcSciY69r4gTg45cchT9sG6p3BQhBdgz6JsWGfoEOsdowsrdTpFzIGnCiqwkdba'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::b161e62b-0bb8-4ee3-8290-2d13a5a85743'
public_address = 'HcSCIGmpdeMyrj4vrpezwR9YrqM9knoqjwocVGd8vim8y5bmNDgO4uipToremdr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::b161e62b-0bb8-4ee3-8290-2d13a5a85743'
public_address = 'HcSciIN4VUhTrcq73uX7n7t5BBRgQuq9335CDN3b63f6UI9rQ5e5Hv3AKaWdjbi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmaKEhrtqepB2c4nddVU4AnA33aT4vQ1BZpjbcrDC6uU6n'
id = 'projects-test'
uuid = 'b161e62b-0bb8-4ee3-8290-2d13a5a85743'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmS6YNdxxcJEuMmCbaUQKeF9LGNKiBke5hBFhy4NhSEPLD'
id = 'origins-test'
uuid = 'b161e62b-0bb8-4ee3-8290-2d13a5a85743'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmWYL7w2zbk6kFPtkt3azPzHWLBdCvKCh6dDyR4hYx48y9'
id = 'kanban-test'
uuid = 'b161e62b-0bb8-4ee3-8290-2d13a5a85743'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSW5gYZde8x9fDvLR41hqXEhc3JiJbecB3FPCGnYHbvf6'
id = 'notes-test'
uuid = 'b161e62b-0bb8-4ee3-8290-2d13a5a85743'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmNrdBEWFhnXvP6oBHGEhG6znVrr9YbWBUZiYMVTPDDz2G'
id = 'tasks-test'
uuid = 'b161e62b-0bb8-4ee3-8290-2d13a5a85743'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmTDFzxfjf3Cmb8bpR8ceDts13YCUYTcDrhb8nptGCpMHF'
id = 'fields-test'
uuid = 'b161e62b-0bb8-4ee3-8290-2d13a5a85743'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmPCaawbaHtBsFgTQEMboB11d32VPYVjdWk3C5CzPHs8XD'
id = 'personalinformation-test::5c48e8f3-843e-4f36-afff-abcb5e10871e'
uuid = '5c48e8f3-843e-4f36-afff-abcb5e10871e::b161e62b-0bb8-4ee3-8290-2d13a5a85743'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmWKzWrbkff7rdgYdEGjMsHAz9pTVL2qq96WuJW6XavzzA'
id = 'freckles-test::280fcf8a-77a9-4133-8f62-be6da7918a29'
uuid = '280fcf8a-77a9-4133-8f62-be6da7918a29::b161e62b-0bb8-4ee3-8290-2d13a5a85743'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/vTs29t/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/vTs29t/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/vTs29t/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/vTs29t/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/vTs29t/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/vTs29t/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::5c48e8f3-843e-4f36-afff-abcb5e10871e'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/vTs29t/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::280fcf8a-77a9-4133-8f62-be6da7918a29'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/vTs29t/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
