bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/GBwe5e'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScJ8cQVjC9Wchgx4Zdd8QX9nkc5pjhocPzrsSt6Vr6cvotUTaoqdkBqfwye5z'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScicgUBF6Gwxqkh5XBT8CptoRptcstcVN8XXIdXtqgbbuu6aR5x6ArKW3X4ma'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCjisW3q8x7SdhquspgpxVMde7ghxgxYtiNT4TuN7butqoQmGVgfXQi5ygt8r'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScJ9MhwCoUihmzko6N9yTu8yu3G6Egm45WE3ecp4nHdbg85nBdtGkXyfh397r'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCjEEVKgp4xzch7p8FjamcBDybmqavwaoScNz478a58azrbFYkxeXsn3ocyyr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScjRGYp57YYx6o4393Z98XhBNOkGwuz3t6HHhGTSsfm3yy4rGVua5CkTn68ai'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCJ9XsUbx4tamay88oKa7ODA3Fbmj8vE85qoRR7MdS7ur7vwm3MrE4cFkadki'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmPFZhyBXvh2hQ5PS1owunyYQYXtYdgQiqvqPddeF3XkoQ'
id = 'origins-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmeSXu4dswfLrsRyzNTbymk8sKpkzwbRxAYRpfhv7GVRit'
id = 'kanban-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmUXgNsmbaFgMgBzaQJSAfaCyKu9iYGJqoi9FozngzLTy8'
id = 'notes-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXXAi39ozsnt2VevFJXXbfosLbd9H5GXBuGmT9kEoh4jt'
id = 'tasks-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUVZeALCVgsXi1cwvFJNtxMQYLvfAg3v8WSQ3pwGvT71f'
id = 'fields-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmatKb3oakaEo8p8F6JNw2DsYquWzzGSSs9fuRXrX3DTMt'
id = 'personalinformation-test::b5622ae4-cc2b-43af-8b5d-920c5fae3b92'
uuid = 'b5622ae4-cc2b-43af-8b5d-920c5fae3b92::889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmVYSaV357KD231hRsiHoRnxtTh3yAhh1qy8XDYmFJ8JLj'
id = 'freckles-test::4b691b60-1794-4462-a39c-ab8fd0038262'
uuid = '4b691b60-1794-4462-a39c-ab8fd0038262::889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/GBwe5e/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/GBwe5e/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/GBwe5e/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/GBwe5e/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/GBwe5e/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::b5622ae4-cc2b-43af-8b5d-920c5fae3b92'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/GBwe5e/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::4b691b60-1794-4462-a39c-ab8fd0038262'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/GBwe5e/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
