bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/EnFbsf'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcScjGkGxYWtq55cj5JumSkG4R5xtxaov377qA4WhTxTWxiiOE4CXNIe6goak9r'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcScJTAPpe7Hrcxrtse3nJpjOKca7mrx9tj87MRwMtynnr5r7tU6QgVyyItm6ur'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCjinGUAqu8m8gfj79AmcdQo58z3MdbFREQkr5TS98bbddTnBEyI6dfhcc8wi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSciIdyVogt7pndpap9V94D6zJKn6rxo4eO8p4KbKUNjjq9CiTkrZ7aPhn8f3z'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCJ7WqB7AIW6bhab9m9XGY6R97b4cVqhXCPPajEkfh8yoiCMjNPXOV7zvw5vz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCinMyUX7gi67n9doNa6DrVJDm8wucwyPaRvy7tDuvcc5sh6N9b4I3pFoGz4i'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCj4s8Rcu5XZomdcbBSAoXaO5omey7v8YRGN74d9ubYsfg6RWISA3XP35onor'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeKjDnW2RYQwTguAtiaHyhBiEkroP4QcHSsWdnztaGmCT'
id = 'origins-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmY5hzbvPET4W2ZPyzhdpbNd1tqkUSvAwSnXQWw44jMbyU'
id = 'kanban-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYULeLPPfiC8yAhvwvxcjYgAmzajtezuWB3JiJ7XHCqe4'
id = 'notes-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmaBbotBPBSgLiqmFwgqX2Tf65rQ4CrdKKwuemDtDjwqYo'
id = 'tasks-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUqFKMUNmgZdMvsK1jdBwZ3MtEaJKurPFQRFG4MDDioVN'
id = 'fields-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'Qmf1iQYrwWLt6PvTCV9hWiaWKiwitpMGDdd3eTHP6BdTyr'
id = 'personalinformation-test::15439ead-20e1-4d84-9e09-102eb71691da'
uuid = '15439ead-20e1-4d84-9e09-102eb71691da::3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmY5iSifHVjZwBYheJzX9zrZwJBxVtjkqos1jksvkub8ox'
id = 'freckles-test::051792a2-1184-42ce-9f84-a8b80955b413'
uuid = '051792a2-1184-42ce-9f84-a8b80955b413::3169c5fb-64b8-4668-949d-ebafc253d684'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/EnFbsf/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/EnFbsf/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/EnFbsf/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/EnFbsf/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/EnFbsf/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::15439ead-20e1-4d84-9e09-102eb71691da'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/EnFbsf/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::051792a2-1184-42ce-9f84-a8b80955b413'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/EnFbsf/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
