bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/LeapnN'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'phil::projects::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScj8IwjvBiezayauMnByJ76RGE5ujjgNCx8t8kNUi45uuj8fZ947ImUH8o6hi'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCjAApxrb83ma4u9VKDSpkiz5gvva5nxp9DfEPAx5p5hfsJqZ5oSy9NSr93ar'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScI68xWu939VJQ89u9cM59vb6N5Fx3yCG6shuzSsh5uauyPo75YTZAj8pf4ei'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCiObjyaifgyvx67D88F8KOR5DVeb4kCKR4SXMy76Wgbae65u6r4xpgm8JDoa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSci46MEhvcZgo97kQ5ie7ZonQgrgbt8sjhhDk88nT5794ugJ57k6wWnfJeb8z'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScjrwC9s8iFqdi4k53h8yTviChs6hvc5iT8eND3DDQejmco9F95oDducwme9z'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCjIt6SF5fE5quauMYxjnSXQ8cvtuad39kOMxER36ssjjomd3bKV565twJtqi'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScJqbmVprk4vdbpkgwnem4dWPdeofqdJVcDYTTNbxq7dkaOHFuoarstguu5or'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmUfuphzKGDCPrE4PHSwi5afC1GeKk4aPQhWfs4Ard3RaG'
id = 'projects-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmWyriGuATgo1GFQgTptmfCxeLZXGMXyadLtCANQDkY3K3'
id = 'origins-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmcDhhqTmDs23m3Y5BkdBzQfGL1eYDSfAnnsBMQoCwMqvG'
id = 'kanban-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQ5y4jfcu9qXKPp5ruu8ooAzvJ2Lb4Kzwmr9UpQLAoobR'
id = 'notes-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXDkj9aqA28zUksXSwonAF3nSzPvgycUnZEqsyAvJ7CAu'
id = 'tasks-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbWbsBwqnuGBUvnBhVXSQ3f5qMGihdEFPsyDp4eK3ognT'
id = 'fields-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmVz9WUKvKcgUVZ7hjbVgACTYNzhzifSjuH4DxXMNWjjPN'
id = 'personalinformation-test::af349ab9-1ee8-4f90-8b2d-faf41598ed7c'
uuid = 'af349ab9-1ee8-4f90-8b2d-faf41598ed7c::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qma8Xq6UMmagyzuug5iM8YjrVe73caRyNrQrtXHMWBoVU7'
id = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
uuid = '33fd973f-e5ec-45c2-b4e6-bbd294cae814::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/LeapnN/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/LeapnN/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/LeapnN/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/LeapnN/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/LeapnN/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/LeapnN/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::af349ab9-1ee8-4f90-8b2d-faf41598ed7c'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/LeapnN/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/LeapnN/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
