bridges = []
persistence_dir = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '6261170b-2064-4920-be43-98cc7ca1d68b'
keystore_file = '[UNUSED]'
name = 'phil::6261170b-2064-4920-be43-98cc7ca1d68b::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScI9jfR6uUuy6ufbY3CdtxYSPqq7mjpHVQ4qo59Q7qvfcq8Mg9ZuWHObiteqa'
test_agent = true

[[agents]]
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
keystore_file = '[UNUSED]'
name = 'phil::41553681-4c82-4c8c-87bb-ae2a3d2ba4cc::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScIWxZuYbddcoof8IjNPzkrFsoyq3kt7WSPX8WGS9phppxxMIQp5E6Bh8955i'
test_agent = true

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'phil::tags::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScI5T3IXvWgq6kbuqapH7uJcGvp6mzch87trOitO38Sintocb96tMx74QZhbz'
test_agent = true

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'phil::ef5ba968-0048-4135-b831-a86b615a89b2::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcSCj8v67EoAsyfyaw5Bbg3uckpM7z7sd5O3fso969P4eTt97uEg3BQw7tc3o9z'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'phil::57c01ed8-30ae-4fca-b6f9-40192821fed2::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScIb4JKJG59b74zuy8ymrYh58yuwrzrnTOBDttNstp6pdvwK3PWDdrqvrruxz'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'phil::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcSCiRXJheud4gy4f65sDVZvzN3P3wp5b9WPd3PXwXVwwfo4PscizsNb93phq5i'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScjPiRPkZu6dgnr6vGcXzac4Xrr9i5jpJrTVpBdxkh935nO748Oa9jNtK75Qz'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'phil::a23de7fe-bff7-4e6e-87f0-f4c44d038888::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScIJkGe447aYftteZxuKM6dZkzzwna3d8eDQ7PfBppazuuSGryHSbPzug3kta'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScJDIspYx6whjkryFhXzemN5met4tswxKsJ5QIgf5aqkrib4jBaioMeoq5btz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScJhkcZTax3fug4dA4o9xWx9P5F5E7qTOdj5zwn3K55xp5QoS7DNXezsbpm3z'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcSCJfYd7Txshj3oum569PiQzzaIvfytoBq7AuuwG4Y4cmgbcY9vpe4z4Micgta'
test_agent = true

[[agents]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
keystore_file = '[UNUSED]'
name = 'phil::0d765fcf-118f-4122-8f03-f5f9ba74e7fa::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScj5F3fF4dREcc5tezkdajB43Qf4usrQqmRoyFOrb7aooueQXAgZibqih4dxr'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'phil::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScjtNJUSUa5yz4rbRPR5db73AkRsnq3wCC4xo5pzY6to6kgdpmjeBVuje6oii'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeGgCyNNMhvgjj8cvFpV5bqJm3T8GpJMLQ5oXNLAVNrHW'
id = 'origins-test::ca96ac2e-a41a-4c72-a46c-c7c25245b46b'
uuid = 'ca96ac2e-a41a-4c72-a46c-c7c25245b46b::24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmeYHs7pNh7UMDzu4BkTsU9NyDWC1vPWzo6AP6ivnGgo7z'
id = 'freckles-test::8f36fbf0-4532-45c1-92d2-f839c39f9e41'
uuid = '8f36fbf0-4532-45c1-92d2-f839c39f9e41::24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmZPu59FnR56CUTnFZvEBS4uU1ekZiqyoCvYdUTY5WENjs'
id = 'tags-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmTBx6LpXMF5s3EwHSRjRcd1Y6bP7SsZFkfTyRtH5rc65t'
id = 'projects-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmVdciPiAXvKLYQdpu1MEXCShosoJh3qwAkQiFopuEH7bK'
id = 'origins-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmZphVKdCmeDnVWhefbQ7xMXSoABxytYftUFrdPio6sCJu'
id = 'origins-test::c0b235df-e113-49f6-8d79-dc54780daa48'
uuid = 'c0b235df-e113-49f6-8d79-dc54780daa48::24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmdMAGGTeW8C17VbHdWBShM9FuyT167BAdN8xJEFfN1S82'
id = 'kanban-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmbgQ6uZpVAYAnVVi3CKpBXWfYzqdvrKGNpysRSziTgAao'
id = 'notes-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmfFmFoBkQChYxAiXVVhJtWz3viF3LJyx2NHMAgAKSkduV'
id = 'tasks-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmakUGYwtXaWw8tDRzwPuZxFnqZuxEhfSoKis9QXHtYC2u'
id = 'fields-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmYvH5wEwhsA2pYha1Xqy2vuMKfupTbyn91ttVTrR18jmK'
id = 'personalinformation-test::f78aa882-8af2-45c4-84f6-1df201dea97e'
uuid = 'f78aa882-8af2-45c4-84f6-1df201dea97e::24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmRyYVpBWKRHRuPW1E1EQJHjo3rctWVGprGtGBZebMcRzb'
id = 'freckles-test::415cacd2-5dad-498a-a205-55e659b1a2f0'
uuid = '415cacd2-5dad-498a-a205-55e659b1a2f0::24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmW1xG1VLF3XUaDdCxWKmedHANNTdH3KNxR6u4XpRC9zKz'
id = 'freckles-test::74db425c-8d9c-4856-b101-dd055a7a89e8'
uuid = '74db425c-8d9c-4856-b101-dd055a7a89e8::24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[instances]]
agent = '6261170b-2064-4920-be43-98cc7ca1d68b'
dna = 'origins-test::ca96ac2e-a41a-4c72-a46c-c7c25245b46b'
id = '6261170b-2064-4920-be43-98cc7ca1d68b'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/6261170b-2064-4920-be43-98cc7ca1d68b'
type = 'lmdb'

[[instances]]
agent = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
dna = 'freckles-test::8f36fbf0-4532-45c1-92d2-f839c39f9e41'
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
type = 'lmdb'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/tags'
type = 'lmdb'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects-test'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins-test::c0b235df-e113-49f6-8d79-dc54780daa48'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/kanban'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::f78aa882-8af2-45c4-84f6-1df201dea97e'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
dna = 'freckles-test::415cacd2-5dad-498a-a205-55e659b1a2f0'
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::74db425c-8d9c-4856-b101-dd055a7a89e8'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/QmhqC6/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '6261170b-2064-4920-be43-98cc7ca1d68b'

[[interfaces.instances]]
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
