bridges = []
persistence_dir = '/tmp/tmp.OWNPLglEr7/tryorama/xCIvMB'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcScJ8cACqszxer686HaRXdeYc53wpyhvO8qTATKjpdsq3ktC8TkxNvORm9x5za'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSCiasf6Tftxmms9dymSqe8iyJfc3qwzj5C73tGpWJ3Xwd9PWb66UMdeVdnxya'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSCJEDEYfwxp389nfD4JD4Eg94RE3ryuJgoAvTi8Muksov4FTsR83dw45q9Yia'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcScjv3jsjdYgdxdjyiCGkxg8WW83izbxIS8VkCuDyiar8m6vOm6OG6U6extqur'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSciiURxc744Berfp6mvxHRXFTaqz6pmViNeMK9Jpnyga9oj33K9cMJef3phyz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcScjjS6UWOX9hkvek5xxBuB8sX3Skhim6hyY8Wavgz5ttfyqX49KQ83oOfvduz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmYVdbfytqwqkM4Mr4gmqm6KYuvkoKmHfCECpnmZkjHMyr'
id = 'kanban-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdGtdWeCoYbiz1qCU2hZmLa2AjUiA6gJeFyKvpYNLyngA'
id = 'notes-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmVWBR6YCNCVP7gCosgv6e63drYiwJaQuqKMnNqizT4aFs'
id = 'tasks-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmWzE9sFyPxuSGK6bBRovcAK8d2sMm7SKVaED7T4FT3dDB'
id = 'fields-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmUUBDN67tue7S37JiyCf83dZJYa8qvQpwteV5b3QaJprG'
id = 'personalinformation-test::d6e22d70-14d6-402c-867a-819d8ec973ed'
uuid = 'd6e22d70-14d6-402c-867a-819d8ec973ed::94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmNUAQoevAXBaDef2eMRzy2N4mpEpiDtoqayeL7a5aQnzp'
id = 'freckles-test::9738bc47-ab84-42c7-98d5-ee6537dc69b6'
uuid = '9738bc47-ab84-42c7-98d5-ee6537dc69b6::94d80625-7315-41aa-9beb-4ac94b237877'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/xCIvMB/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/xCIvMB/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/xCIvMB/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/xCIvMB/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::d6e22d70-14d6-402c-867a-819d8ec973ed'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/xCIvMB/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::9738bc47-ab84-42c7-98d5-ee6537dc69b6'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/xCIvMB/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
