bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'phil::tags::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSciDFCxNKqkj8zoo5iDg7rDRePtmnmdidyRF7uAXvp7g69DrfG3CQn7G7tu9i'
test_agent = true

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'phil::projects::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScijiTB7ao74tukcU4qKqmyffmyxdyqHsOP3W8KD7w5p5fwpjZVUBTgczc6pi'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCjIoeyKxws9i7buIb9RAYQ4tY4vdw8nCTCE3ghU4nhdkbSUE8U49dOPxeqma'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSci5xNNT767bAjtya6ZP54ao6erat7jXVcDi3KpDaix8jgrKompVpo9odsyxr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScJWRWOUEnthihxnz75JDcc6bYFk4dyfiBAj56JMQgfa7sCU97BoQpWR7fskz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCJyTWHYA5xqqviuRfiB44UG4bJgz8fYZarRY9IPmjy3f4cci59iWDM4T89si'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCjtqaXpF6chrzomWazoUH583DDvo3ar6A8R9qFfhRro4gf8Y5x96xjOivifa'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScj4fDgPrBtrqmmcemw5z57zKCW3mdbODjMGAM7m87xbom8K49CB7WQHHhk9r'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCIDK34b7FIGq7qrCSGKRRJEhk3jmdsCUXKcUdufgavw75QO33Jd4jYKd4q8i'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmU4CN7gvvxpx5p4FZobR1cmSjpKPDnfhhAxEG5Tq8uniQ'
id = 'tags-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmbJrmZy27juv2HYjoLWt8CdRJqQkTk38pxcSurDyWzYDW'
id = 'projects-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmQutjyu1gmtmBmAysKi97J7zWFGZ5vd4qswrqNt2RU7xq'
id = 'origins-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNnYtKAEggRsuFufbRZyPmKYgRVtTHNVWHmGMmsYPu7C6'
id = 'kanban-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmaNcK79mga5ttAcHDfZT4KphgXsdYLZeFhM2Vw5UL5euF'
id = 'notes-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWkkYJaZxunVzn66Sba67XRqsvCrBKuYm7744TJwyrK49'
id = 'tasks-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbA5oA41mbtKNCSUaAyhvc8NUjzidT2LDop1TqZETawmu'
id = 'fields-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmR2NHxyBEMKHXTdgVbudZeRwZBmHq3uMqzxox21cdd8Qt'
id = 'personalinformation-test::9cfbf028-480d-412f-98e0-1259828f3b9c'
uuid = '9cfbf028-480d-412f-98e0-1259828f3b9c::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbrwEAXQjS1b7fqhLFkmxusDXYirSmATwMW9nE9egS2t4'
id = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
uuid = '747c6bb9-c2d1-4b5d-9927-b3ffd4174748::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW/tags'
type = 'lmdb'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::9cfbf028-480d-412f-98e0-1259828f3b9c'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/17JoeW/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
