bridges = []
persistence_dir = '/tmp/tmp.4OYPJetHpj/tryorama/U3iECb'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'phil::columns::5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'
public_address = 'HcSCiBU866Kk8Fezehhmtkj7A4fjdtvkkWwBq8ISQvhkd459TnkD38rRmwrv9fz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'
public_address = 'HcScjsxgI3Kzztiq7n9TfGWQqzMck9f4v8r3Wg783n6r6uXMiRE8783eFACpr8z'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'
public_address = 'HcScirNbHu5Gwm4w8gyHxNx8ckZsoyaopBT5ppkOS8iwza7ptZpUgEVQwk7386i'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmYYJmyGErtD88cFTTUsf48UeXMSwBLMLHakbTduHZg2U5'
id = 'columns-test'
uuid = '5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmZHCQNULeC2hhTvE2gk4kLN8UCArZm5ybYHTxYiqv1uZt'
id = 'notes-test'
uuid = '5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmW4cHiM2qeVjYuWgkVbB2YHAoP917yqHxxsxDAhE34sZr'
id = 'tasks-test'
uuid = '5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/U3iECb/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/U3iECb/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/U3iECb/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
