bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'phil::tags::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCI45jbR7kuU3euh8ykeHUpka8p8c4a597JmbDI6AascugJPO5DeHpXwp6vor'
test_agent = true

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'phil::projects::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCIerpZUCxnvhugmFXgGdrFu9or86bjW76Ga5Rq8anhfwuCUkRoJe3Jigje8z'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScjFrN73I97BzjcsAOUcPkY8K9fd9ogwGHhqhqamz9hixrVJS8c3I6i7x5sda'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScJNwSh9T3S4yybtda4o4AXig6uomt6miwrxeAznd35z3qI454RGGq8B86Z6R'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCIkY4ZsGnbomyasI3XOBiYoj899d6sEpSq73ttEV4nusu5aNh877FcFuzi5a'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCJC47UuMOCch9pgFGeMh63fa65iwbpz4d3Qsd5JiP3fw7d7udVJ8aoJbdbqa'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCJ35ug4Xo4Kojx49FV58xrkev6Tyk8gpY6J6qqJU8uthpMtEQoDGGpfw6xaz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCj8NQIQYwmhjt3z4zrex5iEw3edq7i7TjnSJDv3Mroqbda3i38kXB6FMRqaz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScJ5Jce7DEZrm9fzUgBuyPQ7V9v3poxxwdgPy6ibn4x9qyk4tvJ5mzSjkzhjr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmQFJhm63QCMcxzvbMjz2FyMabNieFXaYqtdYgSV3BhirP'
id = 'tags-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmTWPHy3wW8ykVXTzmFQCiXqZFf74wjdSSppH2ZCgdoeWB'
id = 'projects-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmPBaGbmisGCYgPqV82xZUX3ozuEmJqmtbhDCRZkjzF1t2'
id = 'origins-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmPHWJrJV9M8KhEkRQZhwqtC9cjKc6VUQG6axBVFwxcWWx'
id = 'kanban-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmP1hHTmSf77Q41E5Z8tvoyEefgLHBCWQ3wTBDucDAsMGf'
id = 'notes-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeJz3YttC3m6QKpxkR2saYnLPpsoUUyB8Cf6nvftnGMnU'
id = 'tasks-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmP3JEF2b3JnZ3iqY96pq3hDyKMr2HLShLT2qojFCMbNHo'
id = 'fields-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmY8dyfEDh5nahfm6TGTrbwP4AiFQrm3qkx5Jo9Ue5QDeL'
id = 'personalinformation-test::4194f031-86cb-4436-b860-021e04c6dd95'
uuid = '4194f031-86cb-4436-b860-021e04c6dd95::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmV4kNmjK3i5yWb8HbAXpnCsdhLaAs5LjfGZBZadRRnT46'
id = 'freckles-test::a794d207-53c0-434f-b1a1-16c730db9017'
uuid = 'a794d207-53c0-434f-b1a1-16c730db9017::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk/tags'
type = 'lmdb'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::4194f031-86cb-4436-b860-021e04c6dd95'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::a794d207-53c0-434f-b1a1-16c730db9017'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/CqK4bk/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
