bridges = []
persistence_dir = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'phil::tags::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCJctVzovym33ht6hqPi4ZGXteccasqPB65qtPRU8Hwdvs7KnX6hCP7r6sjur'
test_agent = true

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'phil::projects::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScJcXsid5SbymtarN3HnIcFVRvnxj3vx68YvK76QXSwuso3Fikmdrm45sw6rr'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScJFX78OIGHkupucAFcQJVHZh9h4xmuAVtmjISmj4jbx3ww4CRUcFZgaktuer'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCiHYjvrHptnbj9s3ebY5447zQyMnheJ3jMkW7E7t4Wunhp7KS5VzBifar4zr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCjxwYowwfqawuyfY49JuO7GfQEhdaaKQ5u7TUao83asbqS3a8q4J3AGsp77i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCjriy7odp8xmwv4diKETG6XtaqenbqWCZP5NopR44ch7cAc9duFqIDohb4zz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSci75y45CoQ5Vvba4A5ZzE7xajnjnkj9b5TqTNTsqhp36jrUmty6FC57V7hpz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCJmTWJAA9hvzkqsDOPkc5v6WmgmrxfDQYXyeuxaxjsof6SZoCqCIEey7nc7i'
test_agent = true

[[agents]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
keystore_file = '[UNUSED]'
name = 'phil::0d765fcf-118f-4122-8f03-f5f9ba74e7fa::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScIPddk44c6sjuve8Zz9zIc6nP5nari5QMxNBXM8cc8pg8g7oRJQI7Yrixw5r'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'phil::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScI6UhyBfutrjd5k636VtDyX6Jn9e534n5GXB9b4oOHaheJ3asD5wHkdti9sr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'Qmf3yD44i1RdwfLbavejVRaDW2ts6oyTbKhKq6t6PzhXdf'
id = 'tags-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmTowXu1g5ovGc6jNVzshdPB3h1Y4wUhMq1LF5FXemm63M'
id = 'projects-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeY3adbehJxnTaBKudvdknhDhpDA7PeaHfSmWVUShU5K5'
id = 'origins-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmb5F5DqPpjtXZa3bcUJSqsy2eD9Q8ZAFKGqjaVWaxs86f'
id = 'kanban-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSqxSQ9EGh5xMNjmoL3AAc24rHUsdJmrdAGfYJ3DwMruc'
id = 'notes-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeuwMKfLwq3GTows2oxEDrnV57dbXVgvWhxpJkLdwzbUZ'
id = 'tasks-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmdrXAi1JaH1WzGZ9gffDmUdq4zcx2ZpDw2R6Bsywb6qAk'
id = 'fields-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmbRkfthqoL9TDhj35UwyRVZF2JCEDrTYz8a8LgMcQZLLA'
id = 'personalinformation-test::16cb6b26-be28-4485-a8dc-04c1f4b03d38'
uuid = '16cb6b26-be28-4485-a8dc-04c1f4b03d38::a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qme9LKREXoB33WzhHDEtga9YsJcVcQPtsLe5y5GH2aRUBK'
id = 'freckles-test::04638213-a28e-49e3-8fe5-0624017f9b57'
uuid = '04638213-a28e-49e3-8fe5-0624017f9b57::a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmfTpUaoqtzHH5ziER6xVWCzHWGun3qViWwTynGsXdXgwc'
id = 'freckles-test::ba5fc91b-5602-4eff-80cc-34801d511e2d'
uuid = 'ba5fc91b-5602-4eff-80cc-34801d511e2d::a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/tags'
type = 'lmdb'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::16cb6b26-be28-4485-a8dc-04c1f4b03d38'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
dna = 'freckles-test::04638213-a28e-49e3-8fe5-0624017f9b57'
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::ba5fc91b-5602-4eff-80cc-34801d511e2d'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/9W9xwd/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
