bridges = []
persistence_dir = '/tmp/tmp.RKtVZnekW0/tryorama/IJCSUH'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'alice::columns::8c644d3b-6693-451a-beb6-c34dfdd53ffd'
public_address = 'HcSci739xZ8wrQ9PaxC8EU83X9RaAJjfxTFhPS5TCBddkighJ78rpNEYTfahbcz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::8c644d3b-6693-451a-beb6-c34dfdd53ffd'
public_address = 'HcScImsGxWfkjd6igxwhhd4x8SaM4keawHVCbecIAmimy6f89fnKOpgFp8za86r'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::8c644d3b-6693-451a-beb6-c34dfdd53ffd'
public_address = 'HcSCiKK87zkwvynmtvZ73t3YAQEAMvh7yeNQBoGtH9x8br3qf6ZShp7fWX9ocsr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRK7TfNMMfDLXJ8BAGZuDbbCoBx8PEKbvbceKBERbw9aP'
id = 'columns-test'
uuid = '8c644d3b-6693-451a-beb6-c34dfdd53ffd'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmVcAtRV6YsCZYpBqEUa2jazvddEx9JYnMHrqhVuzamvPb'
id = 'notes-test'
uuid = '8c644d3b-6693-451a-beb6-c34dfdd53ffd'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWNdAZba3eYB91QVWxuDidV12tRL3kBWS5N14gADt36qb'
id = 'tasks-test'
uuid = '8c644d3b-6693-451a-beb6-c34dfdd53ffd'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.RKtVZnekW0/tryorama/IJCSUH/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.RKtVZnekW0/tryorama/IJCSUH/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.RKtVZnekW0/tryorama/IJCSUH/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
