bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/LDiNTN'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCjr8d6ZHVWmvw4juOZsw7UP9Od6yxuh6U5qkmeAo3cx3zR4kfUAVtyeuvnma'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSciuibZXDtyohixui4XnZ9NaeoibiyuFr7FU6BuU55O5duv3EBUytCSnkw4ma'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCidR46N7tXy4uaivOG3aHf69fhq9moOP58K5B4EMVZ5ra5u79ohrwisdha3i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcScj5HCjy4995uTsoGmCf9fM5QSfixpwMOedEx4FJ9djrf6x9q54zJKa8RP4xi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCIuKGF6jNit3gqfBu3paneKKwcntp3JHRbicBCxnrraquoB7gT6AWDzq9mma'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcScjvpOZWeru6dr94J4NJq5QN9YittuiaA3IS3CmBqexwpdGTzmiZ6VFt7cn3a'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCJGg7T96IRtfmstib75vs7VW3Qy8t6sJFq9tpDNojrm9yFIr8tW4c5xj48mi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmYMAuBtwh5tvEWoe3CyMygGZvGM9qN5Q5yUx29xv4FhRC'
id = 'origins-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTEe5g9Na1cuMG5MefVBFAgWJ7E3t8ThM6GxXaR1jmbtA'
id = 'kanban-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdfNoBr3Ct9SSKcuEjbgqZVwDMyNXRy3BUGFBYcNd94kb'
id = 'notes-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmVKCr5xhBrmdikE7aeBVCwC9ds38gbjRoSrDn2Aao96tD'
id = 'tasks-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmcGm2V8nrSdhT8iQusSg7w5hpPxeH2jR534ptP1FiTwsC'
id = 'fields-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmWnJJGvVJaL8XU6BKWY64bvLzHbsZfoxFAvd8r4EYrn9V'
id = 'personalinformation-test::4c137d9a-dd79-4b5c-9778-64972d91618f'
uuid = '4c137d9a-dd79-4b5c-9778-64972d91618f::a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmcufKtfPJjH25ncN4wb2g7qWRNMpBkH9JU5mrRcrbAwQ5'
id = 'freckles-test::c3114f14-45dc-4f92-b539-0c7ce6c40e63'
uuid = 'c3114f14-45dc-4f92-b539-0c7ce6c40e63::a18e62c6-4277-412e-a730-b8a327cb4367'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/LDiNTN/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/LDiNTN/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/LDiNTN/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/LDiNTN/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/LDiNTN/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::4c137d9a-dd79-4b5c-9778-64972d91618f'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/LDiNTN/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::c3114f14-45dc-4f92-b539-0c7ce6c40e63'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/LDiNTN/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
