bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/TFJDU5'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCJMrzHAP5sr5r5z6dMur9cRM4OqgqazfEgZAj8vvvngypHkpM3ZWdKfy5frr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCiWv6ijgGth5pkc8R9X9cZyzW6JectG7wgSpzoYvwx7aoS6f7GmUnJTjhv6a'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCJAuiVRWducoec6URo7T98fv955EBro3IW4qOr9bbdcyyUJ5UyDgoJai84jz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCjf9ymjgcxmwtagSDVfqz4Daarhsisbh6I6JKNTImpe38QEOO93WW5985x8r'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScJCNus4G7RktmaymajHFW6ZBb7bq8q8fxy5vrc6g7Xkm5ftzU83EvPcdjj4r'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScJfiWAp7wzatsgvt9W6EN6qDtw9cue9pvBaeRBsehenq3bk3SyuIGhnf7d3a'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTvEQoxuEYwvZgt4QRv82SPBEMAbv4pGa5KF6TJUdArZV'
id = 'kanban-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmfENeArJWfouiueEiFJNktR79wd7iEwxmBRps8ikVZ8xs'
id = 'notes-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qme7HaKn5K2zZARtCLWdgvkxzCGLpETeue7iPStGV6eGMa'
id = 'tasks-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmeXdovo2y5QMKi3eGE13tcLuuDB2vjDcCxtL9dBB8y5B5'
id = 'fields-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmZTW12pcK4K8PoEYDWNir1is4HsuVzfGhkn2St48HXMwd'
id = 'personalinformation-test::fbf77ff9-1082-4a14-bda3-12839968db94'
uuid = 'fbf77ff9-1082-4a14-bda3-12839968db94::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmcZthhqvMS1UwzPt8YakjRTV65SnfRmsRLyfhEeW66oJj'
id = 'freckles-test::642d38e7-c187-4e56-92c0-f160fd5afa08'
uuid = '642d38e7-c187-4e56-92c0-f160fd5afa08::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/TFJDU5/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/TFJDU5/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/TFJDU5/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/TFJDU5/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::fbf77ff9-1082-4a14-bda3-12839968db94'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/TFJDU5/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::642d38e7-c187-4e56-92c0-f160fd5afa08'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/TFJDU5/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
