bridges = []
persistence_dir = '/tmp/tmp.tSmRn1QBs1/tryorama/PSloVs'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'alice::columns::ad712d12-e870-4f42-a54a-e0ac344582d2'
public_address = 'HcSCj5844vcCzi8Jcg5mJV59AaFgJzrbi4K64OGR8Cdv4vp67mDXk8N8foTum3a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::ad712d12-e870-4f42-a54a-e0ac344582d2'
public_address = 'HcSCJZRsGOKf7igi59ZV55SItChZousgx7hMoktTqyiu96ax599o9RB6eC9o9XR'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::ad712d12-e870-4f42-a54a-e0ac344582d2'
public_address = 'HcScJpuHrOKmjdcdgpq7Ek3z4DPRwkpkioO4mif34TInwg4fEaRUpwscvamorvz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmZFrnYNk62utKKhF8wNLUdwnARv9BkjHVMMJAJdR62Vk9'
id = 'columns-test'
uuid = 'ad712d12-e870-4f42-a54a-e0ac344582d2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPJxDWfrJXPPyp7wQkhxWnApDqy4RHiP5iQMZFvemmmom'
id = 'notes-test'
uuid = 'ad712d12-e870-4f42-a54a-e0ac344582d2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmW1sBHN3RVHqNMe6Bj7m8tNuTr9kfZxz2LSZCFkBvjHLx'
id = 'tasks-test'
uuid = 'ad712d12-e870-4f42-a54a-e0ac344582d2'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.tSmRn1QBs1/tryorama/PSloVs/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.tSmRn1QBs1/tryorama/PSloVs/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.tSmRn1QBs1/tryorama/PSloVs/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
