bridges = []
persistence_dir = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'phil::tags::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScI9ndXZgbtfusg9TSh3Wh4Qi5nvioieGZXZyw98C6z47o4B9yVRs76Ownuui'
test_agent = true

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'phil::projects::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCjIsUvAhivpqejkPp9ZsRTmndp4d8qn4SsX7WSDFd8sh5yjMpnpN35kbfwri'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'phil::57c01ed8-30ae-4fca-b6f9-40192821fed2::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCJ8FogHfDhytmhzeqcOnunmckfcmo65SeAbF3TG9qa5379YP88TxHJd6wuza'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'phil::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScI9hMA6YHVgqhe669P7FyvzsWov3h7qkjS5T7CtGusmq73DXyOVqh6ewmhfz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScjYJzev9Vnt484x4x89UcS6F5DNdcb33TOh4XXSHEqbb9fgNUtbVnhqt8x8a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScJX5JrgoRpnk35vS67NV354TVfiRociC3yUmR3Icrazq6Oro9iNxf85Zhk8i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScjX6IMJH7Aymdi74DuDdc776fGVvo756BGzPkZrF5r3xfaN5XsYnUm7rn55r'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScIzW5FFCTqz6ov5o74Q3eo6B33WA5B9kegpxfkA74yn6ipCOOi7ip9dujitr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSciFqyBszqhe9don47yaXOhZsr5a7bk5fR6yzPZZ6TaiiuyRZU8wMgZknw63a'
test_agent = true

[[agents]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
keystore_file = '[UNUSED]'
name = 'phil::0d765fcf-118f-4122-8f03-f5f9ba74e7fa::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScIh6bmsQ6Eqqee56obA5h4Njq6Ybf7Ay3aeNfmst7j3yzyA7nTCCyr8yo6sz'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'phil::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSciJDUTMreiy653s7Ije4AOZ9Ttea9qUHZk5ZruYg36redQQntuRsW6osutqr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmZo537cguMkGZUEkETBcB1ytGb4w9zkghtf2V1MmqUCzi'
id = 'tags-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmY9iCT9rspB34nVGD2RocQodDwbGefbZMye6DXJn3Lyy2'
id = 'projects-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qme2fURTTGenmv4Q37AcjRPszaptc8WxZLBViCi7rHqg9G'
id = 'origins-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmaXjThESHey5T5qioKK2XxtaZMSKnsySbWzJvMQ84ZSV8'
id = 'origins-test::932ccc73-91bd-4142-942c-a9809601b7c7'
uuid = '932ccc73-91bd-4142-942c-a9809601b7c7::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTvKjN6pQiYqgY11JtQnxMQbAp1TfK8TKUyDn9uLus8G6'
id = 'kanban-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmXdA1jW3sxFMM9YiPMANSCpwoqK5bRKaRj9E9DWVLxsBy'
id = 'notes-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmaHRhRZozYmmjkJiavN4HANP1yfbE7r3Wp1AAaKumFYoH'
id = 'tasks-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmZnfNNAtPEx9dSkwtzTqE86u7GzQ3KUvzJHk8is4ggcAK'
id = 'fields-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmQU6kAfqJWEk7idxPLS4zfH63Ki5kM1vSWwZDd53nAdRQ'
id = 'personalinformation-test::a54fbafb-ba81-4cea-b969-ce7f9967c80e'
uuid = 'a54fbafb-ba81-4cea-b969-ce7f9967c80e::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmZRMWSswTUtr3zpfXsBuMeLwoLVMAc11EBU5mLdsGDtQs'
id = 'freckles-test::9b358beb-7ba3-484e-bb1d-656c6ac4fbc2'
uuid = '9b358beb-7ba3-484e-bb1d-656c6ac4fbc2::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qmddhy4DaGnyrp1ZTn62duJbMh8G5TnX15kJWFxQPuKENy'
id = 'freckles-test::fd4840e6-f120-482a-beea-334d911eae38'
uuid = 'fd4840e6-f120-482a-beea-334d911eae38::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/tags'
type = 'lmdb'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/projects'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins-test::932ccc73-91bd-4142-942c-a9809601b7c7'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::a54fbafb-ba81-4cea-b969-ce7f9967c80e'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
dna = 'freckles-test::9b358beb-7ba3-484e-bb1d-656c6ac4fbc2'
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::fd4840e6-f120-482a-beea-334d911eae38'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/n1Mbdc/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
