bridges = []
persistence_dir = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
keystore_file = '[UNUSED]'
name = 'phil::41553681-4c82-4c8c-87bb-ae2a3d2ba4cc::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScIHt4Pbp7pzj4ut77k49xa5S8Ke3DPVTarpmAfxdeeagk7j6ThMB4hB3R4ez'
test_agent = true

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'phil::tags::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSciZBjaOyn9w7yhwHiySq4gktzitpq73IdT8s57c7c4mknOhRPwTGGoj4eqaa'
test_agent = true

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'phil::projects::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSci5r5p3gchJgtbeHWn94V677kYTR6psGEbbMHg6bobax37o5A34fn67hNS3R'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'phil::57c01ed8-30ae-4fca-b6f9-40192821fed2::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSCI76rq996v5Xrch5KBHF8pyZTt96cm3u97XF3fcF7bDk8X9JNvc73EjRw5fa'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'phil::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSCJFOqgUzgydkq4x3g3pPVhk65vEep5JrRpWvimag8wmw7ExrikxBSnsa7vjr'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScJZTsJszvk4j9tdMPtA37Mg8Swz63yJbpvK6av7Ryf6konVO4zWue3Yx3pia'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScI4h5FyosYs3wvs7mp5TUyfj3QtuhnbD6didZECobmivtJWzmY7pTGygccqa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSciYR5mdxfcm4iacc6POZQGcQq3bn598jtHUt3IQKb9438SdoTWK37Of89dgr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSCJW8MEd5AAigdzjBMtowuDBoz377my6guCA7OG3pHfh6ubJS4GpYTW9p6s7i'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScje5S7uS4DgjovmuD7iNsMFDbubdah9yc3m3kAMQQ4izfMiW3eo3Hpcgs3wz'
test_agent = true

[[agents]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
keystore_file = '[UNUSED]'
name = 'phil::0d765fcf-118f-4122-8f03-f5f9ba74e7fa::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSCIHz4ANr8fkfrkvVHhFWeEjzmz5osnXgETRhcvfv7ye5kY6meC9Ox6PA4oti'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'phil::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScIXA9MYgv7i3wmpr7C3zDp4qSMzy6iBiCor48w7xk6xu6v8cY9Us7c87Rj8i'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmcW9FPJdVsNjf49SmcToJZKWS3qjuxKM7Py2oYGYPLUJc'
id = 'freckles-test::4a00ec7a-8d7f-4a66-88fe-dd9e1b3fc435'
uuid = '4a00ec7a-8d7f-4a66-88fe-dd9e1b3fc435::ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmR3Qr9uGYhJznG34BoG7QCsnkfXqumqh7nYwG393XsJdu'
id = 'tags-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmR94wEXeaXxXnNFkd2cNUcahYDyFrpfPuXwqcebs438DV'
id = 'projects-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmZ6mb7pkyh34ifEBcYyceHBUcJXsAQwJTML7vJAQqiLvM'
id = 'origins-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmXWq4z1XeeHaDcwYNeEaj3B1wKjbpEcaxLAZ893NRzrfw'
id = 'origins-test::2e0bc1c2-fa7e-4686-a13e-70dc89d99c8a'
uuid = '2e0bc1c2-fa7e-4686-a13e-70dc89d99c8a::ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmWiYJtUvruiEC82iCdk6gKUfwKCvoTwopfms4t7LeH7PA'
id = 'kanban-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmRWrXvPsKg2VQzfQXeQRJuwMsrkhsPp5G5u6ryfy19bK3'
id = 'notes-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmUnpSCbfYjgoLJspA3h1hfaibYQtMzKTjYpV2i3V2j3qb'
id = 'tasks-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmXwWQLUBYQyCHp89pG61mX5TQmsFS6o9EbyHsvC3rhFs5'
id = 'fields-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmbpJWrzJy5APdQA7k69cNe66DJJCEg8e57vFtmzwdFWwZ'
id = 'personalinformation-test::5976d6c3-514a-4cba-8c93-5f8fe3a2d042'
uuid = '5976d6c3-514a-4cba-8c93-5f8fe3a2d042::ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmYB6LoDq1P2k7ZcyzGK2gsXvDHgY6XEZ7k1w3EHLteb1Q'
id = 'freckles-test::bfa164a9-24a0-43bc-ae25-3aa347d93693'
uuid = 'bfa164a9-24a0-43bc-ae25-3aa347d93693::ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmZPfbLLeazEKr36J4fdA3GcTzzWtMjYzaup2t5Ghaz4VV'
id = 'freckles-test::8c3dff43-f9a3-4b53-8548-7512ce72dbfc'
uuid = '8c3dff43-f9a3-4b53-8548-7512ce72dbfc::ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[instances]]
agent = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
dna = 'freckles-test::4a00ec7a-8d7f-4a66-88fe-dd9e1b3fc435'
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
type = 'lmdb'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/tags'
type = 'lmdb'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/projects'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins-test::2e0bc1c2-fa7e-4686-a13e-70dc89d99c8a'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::5976d6c3-514a-4cba-8c93-5f8fe3a2d042'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
dna = 'freckles-test::bfa164a9-24a0-43bc-ae25-3aa347d93693'
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::8c3dff43-f9a3-4b53-8548-7512ce72dbfc'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/lI0dbp/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
