bridges = []
persistence_dir = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'phil::tags::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCJS3T3qtE7XtgswKac6E7aqI33Xgj4mzRch9Kgnq5aytk9ag9ytr5pWS9arz'
test_agent = true

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'phil::projects::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCi3FJnNQ3q7hi49H9V4AiOCczghff75z68eRyZAf6Bbp95S86Tb7DZEhgnji'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScJWdCSf8Y555xphUtZIQMDM3j8myzswj3pIrsfrngj3hjdIw76H5KSzW4xxz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCjjAkbHu8iebpr56bwRo686u3tIg38bMa8jWvOCd8g6hzB9SsQ8xbfTikn9a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSciqtyJ6AU6bi5r937cvwOC9D9dMqt5O9hWe4zd85Fpep54cMoTuO94Kvysaz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScivpFc47ezgm7r5CvA4ET3i9x4mjdwxz8zPecWKajvsnwrr9ME678Ayizvwi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCiQ8mw8YWtfwfunyDV7Ek7bBc8r7vssyb8fT75kfWrcfuCCrz3jYvknsdcmz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScIjbizhMkrq4kroT9qimfHecpvh5sq8UQ4RjaMYhyeuc55ywPnFDuHdh6whi'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCJmJtJNX9nekf97f8K63553HcWf4YW3DnenPx7C36a3hrD96BIPJ8K59kqtz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmTpGrkbrxrHT7gHzUKYuLJcer1TwYj8HCMKiT4GSu5jHn'
id = 'tags-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmZy6baFVXRqJwEbTa2PzEQTAwSXLcFh8wjZLtUkYRBb9Q'
id = 'projects-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmUnZVzRcXX2nBYgfpTJDVQVTYHnX3R7bwJ1WRdUn4JmPF'
id = 'origins-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTxSTHTjwMwEW6sUizD8euRk2RV6kLqkXCT4NBXxMkgzq'
id = 'kanban-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQDHS5v5V1cCtik1RiZzBiZLdAmrFqCffe74oHWh2DqSW'
id = 'notes-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmdHzqRj1X2woEa5wxKVx4VHx8HfEK7jKyoXdhZFPLvFpN'
id = 'tasks-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmRzbVi6sBZ15yAS3ri7WXakpJ9XtbTMpkdbYhGS3qLcVU'
id = 'fields-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmYRJHkek41si8u67ZKcqCskhPvSuvhbak7Zst7ehQ9unT'
id = 'personalinformation-test::75bdc29a-0a05-47b2-bfe0-fe6318634b2c'
uuid = '75bdc29a-0a05-47b2-bfe0-fe6318634b2c::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmeYjU1hubDJth1NWHCmgPEddPzhnFQDkjoY99ttg9oV67'
id = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
uuid = '93309f35-de11-4f62-8af4-af46a19ab638::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL/tags'
type = 'lmdb'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::75bdc29a-0a05-47b2-bfe0-fe6318634b2c'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/LpPKPL/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
