bridges = []
persistence_dir = '/tmp/tmp.aszRTGxx6O/tryorama/G11Cai'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'phil::columns::132d5403-13d5-4761-96c9-4586647e8e4a'
public_address = 'HcScjqHNMsQufx8pfioSUscV7rOagyfwqBcSM6G73xJphd5xcGaOsfubiywmyka'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::132d5403-13d5-4761-96c9-4586647e8e4a'
public_address = 'HcScjge7Q8835I58iGNgTK9764ftSfjja36fHEfmTJOnqktn4IN9nRYab83Q4pi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::132d5403-13d5-4761-96c9-4586647e8e4a'
public_address = 'HcSCJzihdAEbbzvtgmU3nw8SQOWozznqk7NyIA4qAEI7s3xyjbkdaT8aqyd6jca'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::132d5403-13d5-4761-96c9-4586647e8e4a'
public_address = 'HcSCj34jiq7T7acexwseoDB8sgG7k9g4jBJixmcp89e5aoe66Dm6r9YeXi6Nqhi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmfV5VVt3MwHw3dwfTranbkTs7hhx5TE4sXt8aGzwYUVgf'
id = 'columns-test'
uuid = '132d5403-13d5-4761-96c9-4586647e8e4a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmfEa9ngNRkCZ4kTP7Z3AyWoJmSy61EiaVU4RKpzScnn4n'
id = 'notes-test'
uuid = '132d5403-13d5-4761-96c9-4586647e8e4a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXisEqTPq6xKyLg4X7kG473wWDVN8XdvZSBMxax5gJEo6'
id = 'tasks-test'
uuid = '132d5403-13d5-4761-96c9-4586647e8e4a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmT1gmnhHTz1QaUDqUGto8ykhGFjjciu8DmD7bUyn9cuzs'
id = 'fields-test'
uuid = '132d5403-13d5-4761-96c9-4586647e8e4a'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.aszRTGxx6O/tryorama/G11Cai/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.aszRTGxx6O/tryorama/G11Cai/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.aszRTGxx6O/tryorama/G11Cai/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.aszRTGxx6O/tryorama/G11Cai/fields'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
