bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/Pu00U5'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'phil::origins::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSciHceioD3ni48gjGKTUcHyAm3u8bvwra4pCpYUMfj3xjeWmUdm7sIjvg9tcz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'phil::kanban::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScic5WmWNKot8ovpoPEdHiSj356yvpc7yYfoAzPImuqzd8C86bcYoySUne36a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScj9DZ8z9krFv9hqAPGMftOcuarzqn9QSFneQTr67d3viw8vHbb4eqJWypk3i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCj69ipq3QjT6bvr6SrQI9Y45yVYr4wkdg39aTN58vuofmYcajHmJN3rdwdyr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScjJC9dzRCmaddexH7Jo7i8Mfnxae85Gn6BbkzdTtoy7kihz6H5bR66wRB5ba'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCi4x8iGBSyzoiff9gBz39otA68W3KgbxwiaSUPfcufwcnBEpbF68cxeozgmz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'phil::freckles::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScjvA7AgNZqy6za9b4hB4m688ny99UQnZtFymQAq558aq777Ewj9E4R3x3jwz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmRxkGsNZP2Q1yXhwiRfxTotEicNzDRDn5TNL7bGUu5mvy'
id = 'origins-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmQvpxoiR4zLcbZgJXPGGm7jWnnLPN5nZRiV7mTsT3Eyqb'
id = 'kanban-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmVBYv9DcLc6fju9AXUKbpp5guuU3Bae14j7KpC6GbrsEM'
id = 'notes-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmU3pxPmfoaRdcmsDjcZigBDq2xKLVmYq8234Fp1tYfSxq'
id = 'tasks-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmPMyZn4P9iB7KcCLt4u5NkAJ9muQJc2qFaLxAScSjwp6c'
id = 'fields-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmUj8rKzomTjbKsh5yQLPBW4BoESNzhR7JZawLxdVcrs4h'
id = 'personalinformation-test::b402c1ef-2efe-4f1d-aebc-f57fc3f1c5e2'
uuid = 'b402c1ef-2efe-4f1d-aebc-f57fc3f1c5e2::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmPpencuh7jGURJFSTNAZMM6UTcZSLhgrCg96E8hWb66of'
id = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
uuid = 'a66e1d3a-6ad0-43d7-9619-e3b4a622690b::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Pu00U5/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Pu00U5/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Pu00U5/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Pu00U5/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Pu00U5/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::b402c1ef-2efe-4f1d-aebc-f57fc3f1c5e2'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Pu00U5/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Pu00U5/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
