bridges = []
persistence_dir = '/tmp/tmp.9VlgWQxqgQ/tryorama/30K93D'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcSCif45jJAFZg6yn6548HDrbpUsh9czf87OYzkdZY8s37e9aH7Mssj8wGwknua'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcScIPqoWOCdo46qtkG976U6pRtuAvqvdrDWBG8D4KNw78cif5TIVJQMcy348bz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcSCiY4j9hrPy6g55mtOTJXoQDp7oyzznRv65Hcv9ZfXpqnvMZbjNZHxggmh4na'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcScjmUxewqi4psc6vuNhgrZSCobi3xpkmE5Uw58KH9bNgroJ9FCZG5ZaR3mqnz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcSCIaABRjIw4ugamuW3xtuWVxVjpib3whP7e5wYGbgr6h3yEXT45PcDTwihkpz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmaFZ9hSpG3Vza1QsXAqtm622Mz5gXDbQUXreaDfLCFvrD'
id = 'kanban-test'
uuid = 'a08ba0a0-027d-4239-b608-88a225cf5533'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'Qmeiy4HpFmEioqahyQq4uBzYc93YnLNZiagUQVmyrfiNVu'
id = 'notes-test'
uuid = 'a08ba0a0-027d-4239-b608-88a225cf5533'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeLboBHgzqKRGp3D41jMTN64w4m2RzrxfhcCFuzuawVH1'
id = 'tasks-test'
uuid = 'a08ba0a0-027d-4239-b608-88a225cf5533'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmVsXQFieDTqZkNsVyuQ35dfFAdfcwmh4AYuGRzJuhu7BZ'
id = 'fields-test'
uuid = 'a08ba0a0-027d-4239-b608-88a225cf5533'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmZcN2UZEbFzV4h9rvHYPptM5VTfHzHeYWjwpTgR4wm6ww'
id = 'personalinformation-test::eaf6b8c6-02f0-4651-9ab6-a9c3dfe48aeb'
uuid = 'eaf6b8c6-02f0-4651-9ab6-a9c3dfe48aeb::a08ba0a0-027d-4239-b608-88a225cf5533'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/30K93D/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/30K93D/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/30K93D/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/30K93D/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::eaf6b8c6-02f0-4651-9ab6-a9c3dfe48aeb'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/30K93D/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
