bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/BvHOhb'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCjXNjgO3Wshzdcd5rGbZd9CRa89pzv7myNz4TWjyrjtokwOE577bANV5M8ei'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCjQswn6YNk4d6e447OvCxw54hAdy746Cj4mn9dkOoubjx4BZAJmarviz88ca'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCja35C7M3CO49MjpZ7EHfF4wGj9nxeR7zbkEOk4cbksbf9eewgsp4bhkby7r'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScJe5h4GIv6M5pa3D7uvaWQba3oqgvkbApJrWsp6vrz6rdVh5SZOCWO3ykgjz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScjhHZEbZftekqxqjJTKq55M7zjmttoa33WNgA6CRgdzob8TbjS9iSQFcrkpz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScjqd6oOQJ94zdfdzwBRFPCUxxxitn4OSrHBWUnfidsudm8V4whXbe53k695a'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTvEQoxuEYwvZgt4QRv82SPBEMAbv4pGa5KF6TJUdArZV'
id = 'kanban-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmfENeArJWfouiueEiFJNktR79wd7iEwxmBRps8ikVZ8xs'
id = 'notes-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qme7HaKn5K2zZARtCLWdgvkxzCGLpETeue7iPStGV6eGMa'
id = 'tasks-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmeXdovo2y5QMKi3eGE13tcLuuDB2vjDcCxtL9dBB8y5B5'
id = 'fields-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmXPFkDzhLBqdW37kB1Vg5jBDzPVS6PSs1GGY1pyfMMTsd'
id = 'personalinformation-test::b4da09e3-b458-4d7e-9eb2-08f22825e0d6'
uuid = 'b4da09e3-b458-4d7e-9eb2-08f22825e0d6::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmcZthhqvMS1UwzPt8YakjRTV65SnfRmsRLyfhEeW66oJj'
id = 'freckles-test::642d38e7-c187-4e56-92c0-f160fd5afa08'
uuid = '642d38e7-c187-4e56-92c0-f160fd5afa08::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BvHOhb/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BvHOhb/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BvHOhb/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BvHOhb/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::b4da09e3-b458-4d7e-9eb2-08f22825e0d6'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BvHOhb/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::642d38e7-c187-4e56-92c0-f160fd5afa08'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BvHOhb/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
