bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/UkgrMe'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'lucy::origins::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScJQmIJ3Dk8gurtiFV4h7DgDF8renwwe37T45gzeCigfccZyE6K8izEzqm9xa'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCjVXPTApfjzwc3ccURuiuGD3efhspy69qYJk34ygbpaqvcXUE7qd7vWssyuz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCjgYhO6wbe4gf4rIvwzWEpziydkaneoUN4wCnurr7aejrPfVXsZFWed7q73r'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCJp3bEDfb9fkhw686UCYqoaccctwdnQeCISDtG7y36qprr3iK3C4RxaHvvti'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCjWeCsK8Pxavdi6nJh9reCoUesptyiqAE8oqZKdxqfbtbZ5nKYGXoM5qugai'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCjkX7wwrosvbjrgmrFMQTObqzzro6sfwwU3pun5ftra8bKp8CJY6Puhro8zr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScioh9SI3gu7xyphibd4xC3s6yv7h9jxr8NiNn8u93EkarW5t9ZOtXfps7f7i'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmXY5ei2q8tCvRBGb2diHjTj7jQ7pFnwiMf4ERvBSyyLBc'
id = 'origins-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRv9ga5obxctQqz6DPxVkJbyo4ZjadiwD49Hcx6ML7833'
id = 'kanban-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmTujJA3qJUgy2XhvjvVxWSYbegUV8n1GDuRmsSePfL5YK'
id = 'notes-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmf5CUzvxThU6C22RsBKRBZTf8spmynjavtWe2d9dgqXjr'
id = 'tasks-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmdzu7EiT4eM89tDytzJ1SsJLPPMdJ23z9aCeYnwniUumW'
id = 'fields-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmQcQhqtMo3yo6CibuzCFn5FRihZVnpdPftj8hkr5wxZgC'
id = 'personalinformation-test::3f39765a-f07c-48ed-9488-cb615f457f59'
uuid = '3f39765a-f07c-48ed-9488-cb615f457f59::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qme4LkdURYs1nEpK4VhrmvyPbPpPDw6ZCkVHYMFgMa9VBT'
id = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
uuid = '84b0e8f9-cc77-43b4-94ad-a41582d7b704::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/UkgrMe/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/UkgrMe/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/UkgrMe/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/UkgrMe/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/UkgrMe/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::3f39765a-f07c-48ed-9488-cb615f457f59'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/UkgrMe/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/UkgrMe/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
