bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/zOZdjb'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'lucy::tags::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCJYjnApyzusiwkwAf9IuF7AxCwkhpnoxZ7rgnd5u4rqb5AcO3sbJbmtzvaqa'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'lucy::origins::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScIqDm87mSy6b8mewEN5FgHn6Ieaik89gh5BIzFhOdxmr4Tz7qBopTTfi4sir'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCIS7Heb8fW8asw3mCbRa8vIjtguw36ACor8t36hnz9rfm95yOi5QdbYEyz5i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCiQCizgoz3mbyqhP4h8k3OoHk3U9bp85r6URTA69xiPk4PWOhp8vO96a4jyz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCIGpSjw8Uhf4aeqEB537kCeik37A4uJHX7RmSMeamcfxyf3Wp4V57TMgX3zi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScJT7HiH3Qkwg8kjARIwBTVak68pm7yQCMF8reQ3umtwszWfBzRNNJ9gppmda'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScJTxiSuVr95jjeeXn3msE3A6tSif849p7IfBUoe8e4um8f7UMI7E98kb7uba'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCj6CfcVrIn8wmfnHogUJdA365X4azm9dap93WvE8GRf4uF6CrOukCVy4ys5z'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmU4CN7gvvxpx5p4FZobR1cmSjpKPDnfhhAxEG5Tq8uniQ'
id = 'tags-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmQutjyu1gmtmBmAysKi97J7zWFGZ5vd4qswrqNt2RU7xq'
id = 'origins-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNnYtKAEggRsuFufbRZyPmKYgRVtTHNVWHmGMmsYPu7C6'
id = 'kanban-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmaNcK79mga5ttAcHDfZT4KphgXsdYLZeFhM2Vw5UL5euF'
id = 'notes-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWkkYJaZxunVzn66Sba67XRqsvCrBKuYm7744TJwyrK49'
id = 'tasks-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbA5oA41mbtKNCSUaAyhvc8NUjzidT2LDop1TqZETawmu'
id = 'fields-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmRLXSq29g9t4Dsqhp1VPSKA8LxKpSM1XoS2ezVDUzhpAm'
id = 'personalinformation-test::f8887917-bf76-4230-8953-a4c5b1462cfe'
uuid = 'f8887917-bf76-4230-8953-a4c5b1462cfe::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbrwEAXQjS1b7fqhLFkmxusDXYirSmATwMW9nE9egS2t4'
id = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
uuid = '747c6bb9-c2d1-4b5d-9927-b3ffd4174748::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/zOZdjb/tags'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/zOZdjb/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/zOZdjb/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/zOZdjb/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/zOZdjb/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/zOZdjb/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::f8887917-bf76-4230-8953-a4c5b1462cfe'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/zOZdjb/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/zOZdjb/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
