bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/Vcge67'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcSci5bJPJ5CPfy38nzhKI8IEBFxmo4jrhF8fOhYfhix7z8ca9yH698bf4wDmor'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcScjc7ZPFjY4pxftjbzJSJY94pm7efxrACx8Jcwmkkfv7g8FnJrEQv3Quh3fcz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcSCixWVT9B5tzaa3pFuG8Vem76WB3ge8Jb3AKCM9MFh5yczA474eduv49hU8Za'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcScj8SJiKSY5dn8bgV7Q56z3GQoIftbd37utxP4vvfi8waoeaqWk6Mahgvurfa'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcSCiib7Zovb78eao8bvBoP4xyGaazzg4UKvnXEX5Hsfmfq38bqMwHvwyd99e4a'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcSCi3oEkQDy3b4h3hP8mPEgKhtsnw3fyZN8KXW5zTqurxerd7i9VO7WoKXkcua'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmcepKbsTX4PSPw9okiHXp3x3seMTVMZPdgXzWZMgJJAEt'
id = 'kanban-test'
uuid = '21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSrFy7gAG9JKk4sAYNG5iva5kqhuYTdMVexDdfXr29u4a'
id = 'notes-test'
uuid = '21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmRHLxDTTnYmQjzwaskGM9vkcgVRBGQ7qmMXZUVx4nby9K'
id = 'tasks-test'
uuid = '21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'Qmc5xPesmzFhAuuPh7FVssiK8k8Y5NcqHgDQdofZBay5Ux'
id = 'fields-test'
uuid = '21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmduTeTXbRVK5xyQh6FtLw1iGGP2rcBmQjfUSkc6Bakg8Q'
id = 'personalinformation-test::aeea821a-ff6c-4fd0-aeb1-3cd21539a2b9'
uuid = 'aeea821a-ff6c-4fd0-aeb1-3cd21539a2b9::21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmYt6hRTdNy2yd6QvkCY6HfRCSV5CgJ6izH2g7498sK2a8'
id = 'freckles-test::e1117c58-52ca-4564-9d55-07b0a876f643'
uuid = 'e1117c58-52ca-4564-9d55-07b0a876f643::21502273-7cde-45a7-ae26-c1d335993a21'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Vcge67/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Vcge67/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Vcge67/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Vcge67/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::aeea821a-ff6c-4fd0-aeb1-3cd21539a2b9'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Vcge67/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::e1117c58-52ca-4564-9d55-07b0a876f643'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Vcge67/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
