bridges = []
persistence_dir = '/tmp/tmp.MjOx6luAGZ/tryorama/krqRiq'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'lucy::tags::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCIh68srkh9Vjfsd9pPX7C7hN8Bhgc8UPV6JDW9e7ueuahZvt9qFerZe3wbcr'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'lucy::origins::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScigRUb493xF9uwkQXVCT7GfV8bc466pqNtowf6Pteaqt3IREg9UfnWyfjr7z'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSciAn4fRUQs9hnxpPDrP3IeYsmraciaWDDB5RNXzra79w6es4CcH3phj9fp8i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScJfK6SCZFnea8jfADHR6ODJNutz6sveTS4ukEiTefh6itjxc7NT3IHkgnn5z'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScIiT3xvFSgvo9de5DTPT3Df4NT7fraS783hhXptrR7m4wn366Yd4nhZob9ja'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScJ837hKy3piWvujiXoFxYjJb3dbhh3EYR349O7JKCb37kXQGyXDR87rz9gwi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCjkpwTEOjmwtoccO5kume6QAqgejosvkFeoJvnhypuca93AuMnVBjbqn6yca'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'lucy::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCJRIodqD5ftifpjq8XHCe8hUgamxqeTmXr3fIfiitfrjxT53evBzhMRerxxz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'Qmf3yD44i1RdwfLbavejVRaDW2ts6oyTbKhKq6t6PzhXdf'
id = 'tags-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeY3adbehJxnTaBKudvdknhDhpDA7PeaHfSmWVUShU5K5'
id = 'origins-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmb5F5DqPpjtXZa3bcUJSqsy2eD9Q8ZAFKGqjaVWaxs86f'
id = 'kanban-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSqxSQ9EGh5xMNjmoL3AAc24rHUsdJmrdAGfYJ3DwMruc'
id = 'notes-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeuwMKfLwq3GTows2oxEDrnV57dbXVgvWhxpJkLdwzbUZ'
id = 'tasks-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmdrXAi1JaH1WzGZ9gffDmUdq4zcx2ZpDw2R6Bsywb6qAk'
id = 'fields-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'Qmdah2KoyUQa7q3PjhVK7AhBrg9GwAkWcohEc5u82ynHYX'
id = 'personalinformation-test::e98b248c-9637-4f7a-b3b1-4ab8659670b1'
uuid = 'e98b248c-9637-4f7a-b3b1-4ab8659670b1::a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmfTpUaoqtzHH5ziER6xVWCzHWGun3qViWwTynGsXdXgwc'
id = 'freckles-test::ba5fc91b-5602-4eff-80cc-34801d511e2d'
uuid = 'ba5fc91b-5602-4eff-80cc-34801d511e2d::a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/krqRiq/tags'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/krqRiq/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/krqRiq/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/krqRiq/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/krqRiq/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/krqRiq/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::e98b248c-9637-4f7a-b3b1-4ab8659670b1'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/krqRiq/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::ba5fc91b-5602-4eff-80cc-34801d511e2d'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/krqRiq/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
