bridges = []
persistence_dir = '/tmp/tmp.4OYPJetHpj/tryorama/Q1pWGe'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'bob::columns::00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'
public_address = 'HcSciBDmCy33kzzzphB8gXUYrpSg7imz498VCuufg85Zc79qeSUw89JZWrmpv9a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'bob::notes::00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'
public_address = 'HcScj7CMWz57y3t6voh8EqdK4iHnow4xqi6wjVXj3NR6qubcfGQSzxMdq9bn7nz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'bob::tasks::00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'
public_address = 'HcSCjr3Z8vItwavdynIsJnZidOs48qr6e6IO3rTXmrwpdd84FD68Vdf364M7KVi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmZYjp2AhrBnVHxhKdG5aQ4nvM6fiU12pUQr4m4bfVkK14'
id = 'columns-test'
uuid = '00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'Qmc8ocDJrw32uGY99fYzkjifkSu2154oPoySLLxP7EtniJ'
id = 'notes-test'
uuid = '00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmQHPDYeQ38gqbKQvciBp7xw8fdZx6B41F2BzU7irCPWvo'
id = 'tasks-test'
uuid = '00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/Q1pWGe/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/Q1pWGe/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/Q1pWGe/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
