bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/MKpNdw'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'lucy::origins::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScjX5FoQDwrryrcwNw9ydqZ6BVzwpsveczoUdFFwpitsj3vVjW6wWGiu37yrz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScIFtyvz4Ab63wt6wPrnAbwvunk8zh9qUu57OHOCcng84xmIUsyzz86Kur57z'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSciMAweQ6Kodpy3e7Z4tfhcSaSb8npoWI7NOJJP94qr5swHkZIdAJKgfiekei'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSciRZiKmgoy8dsobnc5UCsrfBpgdgnygG9mnesiVwuq5med7DIHvjXGfo4cfr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCi9BzxWoYti75urjz39mguM5d7EhetccD9qBgg3363Ii668P7he5KWrirhdz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScI3IYOp8dBgkbbtHVt65bGpOOsav8ua44YVN7c88RSQw8oaoFPCfu7e36ptr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCiEsIzAPt4xcbyxBA63nFtA8P94m5ezSKg7ZT3M5Pn6jdqbxukJbE7jzjjia'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qma1JTKpyG4URmDcgPANiRVBr8TneiTXhipMMFE5kPNnU2'
id = 'origins-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNW3pea1AdCue3cNx2cmgD7F2Cpajbu45t3jmXMqfVpL6'
id = 'kanban-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmV8fqNo5sD6Uz86JnFbvQJE6BXcTnhozwm5WF4FoenDL6'
id = 'notes-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmNp9Bw3XNDAHHcBXJn2w8XfdH1QxZ7QXStRK9KUYpzdQa'
id = 'tasks-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbcZ4twcVVNPDwg25HwfzkFaN4w6xWzTctbjf3gn45krL'
id = 'fields-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmZ2zuQLUWKzvWXPgki8W6BydsdsonpumKui7RvyF4USMq'
id = 'personalinformation-test::7c60cee5-c808-4a7b-9e61-466ef5e60905'
uuid = '7c60cee5-c808-4a7b-9e61-466ef5e60905::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmWLNDe1gYhjEcNzKmFKPYfsYPbHa2h7YZCyMMrgxPW5uy'
id = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
uuid = 'cda1197e-03cf-4b98-8fd6-8a713f367342::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/MKpNdw/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/MKpNdw/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/MKpNdw/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/MKpNdw/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/MKpNdw/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::7c60cee5-c808-4a7b-9e61-466ef5e60905'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/MKpNdw/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/MKpNdw/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
