bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/741tUJ'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'lucy::origins::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScJg4jsCwbhkmc4nhnKnIk3EWhs6qaeb4OrfE9Qd5cqiyszXqC4qd7gMgn8ca'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSciyDQIP8xpkxr6oBdnmNrVEsomu8dqJihvqspif8godxr6fDVG9cGIphfasa'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScjeQhbOR5z9wnieyzDpG74k6Hazako8X35btz57gNWqajCT7FfaomQk7mehz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSci9ySkrEqdoizjawzmymmexb4a6t5u7eD5Fqa3ivs8fuw7JNv66tQ5XVpzfi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCjxuD6XZqvnci7iH7J5dkyeGxk5xpz5s9uTw9k3Tg9S7xK9doe3O45Q8Faii'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCiKkP8dE5mdw3tyK9o5YS64KINDjsg39uy48NrokO8Sw33AAuSSyy3cp83ca'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScirGhRQIjjo94acmBu8wV53Zcn4yhvcCCcNjVvd6kd9onhpaWCHwFo7z57qi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmWyriGuATgo1GFQgTptmfCxeLZXGMXyadLtCANQDkY3K3'
id = 'origins-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmcDhhqTmDs23m3Y5BkdBzQfGL1eYDSfAnnsBMQoCwMqvG'
id = 'kanban-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQ5y4jfcu9qXKPp5ruu8ooAzvJ2Lb4Kzwmr9UpQLAoobR'
id = 'notes-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXDkj9aqA28zUksXSwonAF3nSzPvgycUnZEqsyAvJ7CAu'
id = 'tasks-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbWbsBwqnuGBUvnBhVXSQ3f5qMGihdEFPsyDp4eK3ognT'
id = 'fields-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmNzH7FkzQ1tML62Y5RDuCA3aravd9pKoM1YFGL619tDhw'
id = 'personalinformation-test::e3e15335-b0e5-4456-a93b-3bf0cd223bcf'
uuid = 'e3e15335-b0e5-4456-a93b-3bf0cd223bcf::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qma8Xq6UMmagyzuug5iM8YjrVe73caRyNrQrtXHMWBoVU7'
id = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
uuid = '33fd973f-e5ec-45c2-b4e6-bbd294cae814::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/741tUJ/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/741tUJ/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/741tUJ/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/741tUJ/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/741tUJ/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::e3e15335-b0e5-4456-a93b-3bf0cd223bcf'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/741tUJ/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/741tUJ/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
