bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/QWDAOH'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'lucy::origins::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSci6OTueWzpq6c8iMoB9p3zP3G5djjmFbaGX6hrMwymegvpJ6smo8Gd59fszi'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCJUHFi7RDdctybifHq7c3v4m9gGo9bEn6R3B37uZtIrxrKvtj6K43s4QKwvi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCiEdgAoK4azzo7gGtf43B7gOiry4oaFY8AFX9fyu5kxowmOT6PIQiD49wakr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCjCQsVDNkehbya6M7T9AybsAr8pymnZDuXrcXSqfputvraSk8baVm7vg8c9i'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCj6bb7ASoYnwnta6CGP7ptM6uizijd6iSk9Vo8Jfa5vvr54zYBwz7S6NKxxz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcScimquC4HgxgyvcsSROcthew9rm43ecNOg53WFzV734qysWnERmz85jWw8oor'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCJCN88Y779UR8kyRBQhAPtj6bfstakdcsix6dHb8o85e49BdX89C5za7Kn3i'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qmb7p6mBV37tfhmhX8XYrVWGKtRvCcT5DTnFJgtdpZ36aQ'
id = 'origins-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmeYSH4uiDD1B7FxFpYishKeRbHy4PrVXUH6y1pxoE9N3B'
id = 'kanban-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPwfAmvYZLXHnXcE56XCLYd7iSZUUbcimp9WqaZEKjPuz'
id = 'notes-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXbj16YVJEEsvnueYT9rLNPYpyu4WvQKVgL5HJ644dvWi'
id = 'tasks-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUx9DQeZrXmN1PA8ahX5VVyQa8pR2hfREgJQqyD5Jja1z'
id = 'fields-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmdCv5QD9MEmPF13tb8omYa6CgdVekupGNYnYJZf3oGLxh'
id = 'personalinformation-test::e233bc4c-dbf7-45a1-b348-941cc9770410'
uuid = 'e233bc4c-dbf7-45a1-b348-941cc9770410::40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmWJ7PP9r5YLGVadVUNVa1Hor9WrSpSDcgj3ucMnseC1qv'
id = 'freckles-test::2a056bee-03fb-4871-a9d7-07acc3002515'
uuid = '2a056bee-03fb-4871-a9d7-07acc3002515::40c9d725-fb55-427b-8480-b4907c2e07ef'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/QWDAOH/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/QWDAOH/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/QWDAOH/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/QWDAOH/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/QWDAOH/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::e233bc4c-dbf7-45a1-b348-941cc9770410'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/QWDAOH/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::2a056bee-03fb-4871-a9d7-07acc3002515'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/QWDAOH/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
