bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/em2ABI'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCI4pR8J7MYA9kra9QDOBxSE5akhh6fCWna5SQ45ssm6atA5TTsN5bdPbn57a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcScjeBM45PmOjxg63xhF3Yqsbwwwxdsd98ZKwmZcCObhd5x7dFU37bXsest68z'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcScJHorfrSgvvaxzizVHTxcuA5thjehsZQG4RAO7azbdbdgdVGPYYBRbyb3pyz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSciMGxphOygvs8yqum545TweaQ9u4cwppVynh3vVnv88rc83QRqcMcNOym8ya'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcScizCsXcp34f3sc8f3jKMp5s3ycw9evdC3BXjAd5Va5pam5Tc6BQ6v5K3uvsi'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCJx79tgv7YWqqjzUQAMtVKThhrk5n3FAamsrrD3sfbyrk3HW89eu9hsWNfgr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmZ2TGpauVUoTTTPwmqNpwmCLcDavKr4utUxdJAmHXZfXE'
id = 'kanban-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmbL8eFNsa9UYtJY2iqRPWVfhHok46fdoYCAskt6gakegE'
id = 'notes-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeqVu6wrMg1KapacXdZDLr5CC4WkjMKYUMXdjubuHeDUE'
id = 'tasks-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmap2ypwmfw4DccYDrJDDZF8iGRbKNsMbcAV69NwRLQ5hG'
id = 'fields-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmU32GFCLGxqnoueC5L9bBjBiqgnzS5i3wCgRdkRCu1WKg'
id = 'personalinformation-test::ae6a3e47-f14c-4f5e-ad5c-89a2755eded2'
uuid = 'ae6a3e47-f14c-4f5e-ad5c-89a2755eded2::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmSNFSC8iDvsCT8FUiFUFY97EZcTLaAnHmX6UsysFtzbdU'
id = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
uuid = '59280fe2-f7cb-43ec-9f20-e4d7cd883a8b::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/em2ABI/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/em2ABI/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/em2ABI/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/em2ABI/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::ae6a3e47-f14c-4f5e-ad5c-89a2755eded2'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/em2ABI/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/em2ABI/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
