bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/mWqmxy'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCiN4Pws9YQdzbnc4c5nvVgx6sFq4p8dt9fRUDmU63nkyi7NGUd8hxC7ftfkr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScItiyhpP74qwte8rVrudJmZt8dqu57jk7tn9v9Zz9jq6vkp9JONjNxkhg6ir'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScJb95C5bKsmvdvsibZ3M69Y5VKTaxs3Nf3JvMN85IPhzhpMXtoRzYnbsbj9r'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSciIwH96ocUwgsdgfD8ZSF3KeAt5dcajxJt3IkPBrc6xb8JhZYm4R86Sj9jei'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCj64tozD4G7Nosu3tH9erK6fC3Uq7jsMK8Cwq5SPjdy45uuHqTtiB5wixh9i'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScJSzmWPen8j6f5e3hZ47Cv3CV3pMkkqu56GJn56V5TKkn5YrABA7H4SFfy4r'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmedGmoWrgruqTQo8CCbueViSHtygNqDGUe5UDuNMBw49J'
id = 'kanban-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYj38vX7snVRgUbRiYSnCSTeQ7rfXRTzPZnthyMGPVuy6'
id = 'notes-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmSkMFYYPAvptbPV4oHMR4jDRR1EZVjrHJy7xE4fqz9jtN'
id = 'tasks-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmZV4fqhTA68pJXXSwLqgDDvj9C4QE2in6H6Er8rk6n5cc'
id = 'fields-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmaU3u8VCH68cVqNFKC6PJ4TBtgoGvtE9Bbf2ttc6HV3CL'
id = 'personalinformation-test::821ce0e4-271e-444c-a2a5-2bc5c73483ca'
uuid = '821ce0e4-271e-444c-a2a5-2bc5c73483ca::460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmQKynt27wddsW3qw2SpKgXtToZBEFUZwvrUmHoozA5uN5'
id = 'freckles-test::cd82d866-2022-4b03-a303-35754cdab152'
uuid = 'cd82d866-2022-4b03-a303-35754cdab152::460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/mWqmxy/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/mWqmxy/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/mWqmxy/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/mWqmxy/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::821ce0e4-271e-444c-a2a5-2bc5c73483ca'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/mWqmxy/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::cd82d866-2022-4b03-a303-35754cdab152'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/mWqmxy/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
