bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/e5kK1G'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'lucy::tags::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCI3Z6PzhED43oscfTkujRc5Qvzeyig6zaIkQB9P7Xqcrsbp7eNDsMoatd97i'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'lucy::origins::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScIsE6xtZkqyw7tyrRTakMZw78ikdzxO3o5VJXBUfjww34w9GXJhhiUhmtsaa'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCiEuAvUpqu4uwpe77dEy9wgzcAywdv9k7FIqOGcutzh7b5WH3I3tRTkEfsmz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScImZzEXV48kxz3f94ZaEmG3VXCc4j9k8C9hA49AdVuzevrvuPzqyOmzkcp3a'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCJ9Zet3n7b8Wt38X66kHPpfNpsjrk4xuB558RT8sHywnv5qBd9nTx4FWaoka'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCIqcTPRnqv8vmgeS74bmKF3qStnyjr5sRBeHOdbwrv3cxI9Be8UEjU7Ujotr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSciZknXHCoffbgwiNmUaI8wTxfctjd7jZDZ5m6Hk9MpdsyT5saTg38Kh5Ywrz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCIj9piAZ39JmijzUzF6VsbbD8kktq6qwvB54HATC95kd8XaB67JkKyH6qkhi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmQFJhm63QCMcxzvbMjz2FyMabNieFXaYqtdYgSV3BhirP'
id = 'tags-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmPBaGbmisGCYgPqV82xZUX3ozuEmJqmtbhDCRZkjzF1t2'
id = 'origins-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmPHWJrJV9M8KhEkRQZhwqtC9cjKc6VUQG6axBVFwxcWWx'
id = 'kanban-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmP1hHTmSf77Q41E5Z8tvoyEefgLHBCWQ3wTBDucDAsMGf'
id = 'notes-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeJz3YttC3m6QKpxkR2saYnLPpsoUUyB8Cf6nvftnGMnU'
id = 'tasks-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmP3JEF2b3JnZ3iqY96pq3hDyKMr2HLShLT2qojFCMbNHo'
id = 'fields-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmdTuDHP5j7PjJxCgxkXTVNwSh98CWzH5tdBwfk4Ah3SGy'
id = 'personalinformation-test::f545f76b-fd49-4b11-b9ac-556d57f65a75'
uuid = 'f545f76b-fd49-4b11-b9ac-556d57f65a75::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmV4kNmjK3i5yWb8HbAXpnCsdhLaAs5LjfGZBZadRRnT46'
id = 'freckles-test::a794d207-53c0-434f-b1a1-16c730db9017'
uuid = 'a794d207-53c0-434f-b1a1-16c730db9017::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/e5kK1G/tags'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/e5kK1G/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/e5kK1G/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/e5kK1G/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/e5kK1G/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/e5kK1G/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::f545f76b-fd49-4b11-b9ac-556d57f65a75'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/e5kK1G/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::a794d207-53c0-434f-b1a1-16c730db9017'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/e5kK1G/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
