bridges = []
persistence_dir = '/tmp/tmp.OWNPLglEr7/tryorama/8zBCt9'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSCjZ6nQB3F8paopvU8r4V9wVEKbabqit7Rd9NZ59kQB35fYVNDzMW7zwcqswr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSCjcNeI9D6Kk65xm58GkYBi36fyaojoMSk99X9D368vefzRZDHOEk6zs4gpfa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSCI5sDIgjYphkeqnDdVWIw9Nq5f97qhNXyMwr3SU8nt4xjj8ZvK7S4V6Micmz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSciWJvaQCsyiq36xp3jKPH7pm8OambcX9EXr3MhK7c4y886dPER7EoKoxnnwr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSci99IJIoH7h8gtwRwqtVm3B3xmirbz6JCjX85PzkafniuakgWsjUY4sb6kzz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSCj9eQB64OyW6mgaJXzsd9nYRchdpu3QioZPVDKka6jcja3yhHuoeuPrzyvai'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmYVdbfytqwqkM4Mr4gmqm6KYuvkoKmHfCECpnmZkjHMyr'
id = 'kanban-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdGtdWeCoYbiz1qCU2hZmLa2AjUiA6gJeFyKvpYNLyngA'
id = 'notes-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmVWBR6YCNCVP7gCosgv6e63drYiwJaQuqKMnNqizT4aFs'
id = 'tasks-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmWzE9sFyPxuSGK6bBRovcAK8d2sMm7SKVaED7T4FT3dDB'
id = 'fields-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmVLEZiLGgA9eoFS1rL7Dc4tZhfzeXkXdUm6vYUxhiMiLF'
id = 'personalinformation-test::363836c5-a824-4085-a8f8-5d9f644b71a0'
uuid = '363836c5-a824-4085-a8f8-5d9f644b71a0::94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmNUAQoevAXBaDef2eMRzy2N4mpEpiDtoqayeL7a5aQnzp'
id = 'freckles-test::9738bc47-ab84-42c7-98d5-ee6537dc69b6'
uuid = '9738bc47-ab84-42c7-98d5-ee6537dc69b6::94d80625-7315-41aa-9beb-4ac94b237877'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/8zBCt9/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/8zBCt9/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/8zBCt9/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/8zBCt9/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::363836c5-a824-4085-a8f8-5d9f644b71a0'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/8zBCt9/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::9738bc47-ab84-42c7-98d5-ee6537dc69b6'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/8zBCt9/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
