bridges = []
persistence_dir = '/tmp/tmp.aszRTGxx6O/tryorama/X5dH9L'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'bob::columns::226be721-d8aa-4a89-b7a3-b617b6ae2ff5'
public_address = 'HcSCjHE96mmYcrwwtb9zngux8DsBtyw3z3Byv78dP77yaJknR59EYPAvchqfosz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'bob::notes::226be721-d8aa-4a89-b7a3-b617b6ae2ff5'
public_address = 'HcScIAuAUFQ3g4abtvdi58jm75f4m54v9Qf99NOwAdxfupcj79mnEq6iRVekw3i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'bob::tasks::226be721-d8aa-4a89-b7a3-b617b6ae2ff5'
public_address = 'HcSCjfR9c6ITvvincdp5ntB67mxTahd45g7yAGW8TGDweb7k7PeRagHgun6kxzr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'bob::fields::226be721-d8aa-4a89-b7a3-b617b6ae2ff5'
public_address = 'HcScjenRbxDhkzfmsdbtNV6fAETcekqq8wu38k6tt456s588f64uosVOo5tqofi'
test_agent = true

[[agents]]
id = 'personafields'
keystore_file = '[UNUSED]'
name = 'bob::personafields::226be721-d8aa-4a89-b7a3-b617b6ae2ff5'
public_address = 'HcSCItkW7a6Ej3955cafuNSpjRaw83v4s3FA4g8gs6cZSgpofEPFdv9YQgtvzfr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmbM8tramuzDtJK8d1K2KLLpbgRg9r1vsqhbn7LRR9pLYo'
id = 'columns-test'
uuid = '226be721-d8aa-4a89-b7a3-b617b6ae2ff5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQLtf5TGSQahsYTPBr6v22CDpCnPtcdz34PVUN9CznLBt'
id = 'notes-test'
uuid = '226be721-d8aa-4a89-b7a3-b617b6ae2ff5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmQ6G39mnxT6fQoVrXGuhtjhB68VYRWiXhA87oBcLEuWfC'
id = 'tasks-test'
uuid = '226be721-d8aa-4a89-b7a3-b617b6ae2ff5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmaKtTDpP1D1RQooGqkUkuEtNewTU3H8Wbvco5VDFVQTJV'
id = 'fields-test'
uuid = '226be721-d8aa-4a89-b7a3-b617b6ae2ff5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmWx2M4aBvQ8awF4BhCMAKXBZPmGE1qNSXYyf3vQDJSrTv'
id = 'personafields-test::e375ebe0-8a84-45f8-8b2c-df6988b51fc0'
uuid = 'e375ebe0-8a84-45f8-8b2c-df6988b51fc0::226be721-d8aa-4a89-b7a3-b617b6ae2ff5'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.aszRTGxx6O/tryorama/X5dH9L/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.aszRTGxx6O/tryorama/X5dH9L/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.aszRTGxx6O/tryorama/X5dH9L/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.aszRTGxx6O/tryorama/X5dH9L/fields'
type = 'lmdb'

[[instances]]
agent = 'personafields'
dna = 'personafields-test::e375ebe0-8a84-45f8-8b2c-df6988b51fc0'
id = 'personafields'

[instances.storage]
path = '/tmp/tmp.aszRTGxx6O/tryorama/X5dH9L/personafields'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personafields'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
