bridges = []
persistence_dir = '/tmp/tmp.udyD72ci2B/tryorama/AOmG8O'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'lucy::tags::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcSCJdbXzy9ii4jb5wS6RMa7Rr9mQnf96569h55954sbxtzdyWhXWSJsdt78usa'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'lucy::57c01ed8-30ae-4fca-b6f9-40192821fed2::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScI57VvCz7QA43we7nfd7sJKez6dsdraarTVC4Fwnjwny7WCIv9f9bJNvzfea'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcSciCF3YPGZz4zbmvxndPwhHtnsbpjttzJJ5ZgU6Gk37wxvnG4yB6nG4j7Hrqi'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'lucy::a23de7fe-bff7-4e6e-87f0-f4c44d038888::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScIh9wCSkbbnqt4yE5aZHw8mGQkgguq4w4uW8r5VKKYt4tNqzgpn5E5Wq8mwz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScjq6HV9CoC3xpavi3yQ55I3ggvk4n3w8sfYng9htkni83xR5MceEA3Dpp9wa'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcSCJnD99s6VKAr9omUaYOsmT7mmztpu9RGNXzXpMdnqeupjk4a9NMnwbjmbj9z'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcScjvdcwFQnxv9gykAhSrcbt64v9tm5sDgTJdmMk64uhc4oXyT4D3O9mP4Qomz'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'lucy::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::24841c6e-cbf7-418d-8642-c208c65a1bd9'
public_address = 'HcSCJfR5jRT7qcvpw4tu5sW6Jw9E4vtvj7ncBKJBf3srmr7nDAIwbx8FDd43ooa'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmZPu59FnR56CUTnFZvEBS4uU1ekZiqyoCvYdUTY5WENjs'
id = 'tags-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmVdciPiAXvKLYQdpu1MEXCShosoJh3qwAkQiFopuEH7bK'
id = 'origins-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmdMAGGTeW8C17VbHdWBShM9FuyT167BAdN8xJEFfN1S82'
id = 'kanban-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmbgQ6uZpVAYAnVVi3CKpBXWfYzqdvrKGNpysRSziTgAao'
id = 'notes-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmfFmFoBkQChYxAiXVVhJtWz3viF3LJyx2NHMAgAKSkduV'
id = 'tasks-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmakUGYwtXaWw8tDRzwPuZxFnqZuxEhfSoKis9QXHtYC2u'
id = 'fields-test'
uuid = '24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmYbW8mUTNgCunGNTNd92YRqDT5ZzLmYMzHXey9YSGLc6T'
id = 'personalinformation-test::ed0c1238-f176-4b9b-8e8c-545c3df3064a'
uuid = 'ed0c1238-f176-4b9b-8e8c-545c3df3064a::24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmW1xG1VLF3XUaDdCxWKmedHANNTdH3KNxR6u4XpRC9zKz'
id = 'freckles-test::74db425c-8d9c-4856-b101-dd055a7a89e8'
uuid = '74db425c-8d9c-4856-b101-dd055a7a89e8::24841c6e-cbf7-418d-8642-c208c65a1bd9'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/AOmG8O/tags'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/AOmG8O/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/AOmG8O/kanban'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/AOmG8O/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/AOmG8O/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/AOmG8O/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::ed0c1238-f176-4b9b-8e8c-545c3df3064a'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/AOmG8O/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::74db425c-8d9c-4856-b101-dd055a7a89e8'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/AOmG8O/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
