bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/N9lEYn'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'lucy::origins::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCJeciuz3ArthcvmxviBNe3RNkgrrghNCDGSTUQ3e8oc3nvoOH38BcsHnb8di'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSci8pjRn3t3dio6hrWpn4qPq3373Yprq7Ez7Sv6GH5Ziofi95cAFyoNqdsesa'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSciRIW8AR3hxgcf8pwOgFnF4XwwwnuiTn6OV5Ma8Sf56tpTSEeQXtOsqjmaaz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcScj7QqIcGTkxqahq9kHAI693Wo969wqspw8yIqm3Yzh8sh5IHrTTfzjoqkuma'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCIFMtZDfasekegg59N8D4hRQaSRz8v5mJd6WNqoRh8fu8nyQO8M898Kaod8i'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcScio3WGwah475r5cynuVDg4fT6vaztisCVXPmWThfup4grXPom8Yo98qji5vr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcScIzjC36u3UgiuvcJQOS53wN4HYtavtqktvMD9BgddscfkkksjYTyhm8gfckz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmYMAuBtwh5tvEWoe3CyMygGZvGM9qN5Q5yUx29xv4FhRC'
id = 'origins-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTEe5g9Na1cuMG5MefVBFAgWJ7E3t8ThM6GxXaR1jmbtA'
id = 'kanban-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdfNoBr3Ct9SSKcuEjbgqZVwDMyNXRy3BUGFBYcNd94kb'
id = 'notes-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmVKCr5xhBrmdikE7aeBVCwC9ds38gbjRoSrDn2Aao96tD'
id = 'tasks-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmcGm2V8nrSdhT8iQusSg7w5hpPxeH2jR534ptP1FiTwsC'
id = 'fields-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmevUwVANzGN64nfXZMviAitP7GCiGzeGzsMTdnQu4vFqQ'
id = 'personalinformation-test::e8aa438f-f34b-4069-88f4-ecb29c8975d6'
uuid = 'e8aa438f-f34b-4069-88f4-ecb29c8975d6::a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmcufKtfPJjH25ncN4wb2g7qWRNMpBkH9JU5mrRcrbAwQ5'
id = 'freckles-test::c3114f14-45dc-4f92-b539-0c7ce6c40e63'
uuid = 'c3114f14-45dc-4f92-b539-0c7ce6c40e63::a18e62c6-4277-412e-a730-b8a327cb4367'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/N9lEYn/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/N9lEYn/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/N9lEYn/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/N9lEYn/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/N9lEYn/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::e8aa438f-f34b-4069-88f4-ecb29c8975d6'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/N9lEYn/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::c3114f14-45dc-4f92-b539-0c7ce6c40e63'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/N9lEYn/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
