bridges = []
persistence_dir = '/tmp/tmp.udyD72ci2B/tryorama/MB8hdv'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'lucy::tags::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScIz5iGvq6H7sdpgZ8YpY3hPSujwxtozU4vrESDXbgkajw85TVBo9Q8aQJasi'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'lucy::57c01ed8-30ae-4fca-b6f9-40192821fed2::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCIoi4KSQOxjzrkmR6Q95HbkaeUoffrQfEO9UdiCbcjjc4b6dfqzSb6J6wwnz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScJZu4gBbr6k8kcjYYcjVrAU6dkusjsotg7TPiyH5pdedyAINP8VPJnqhygiz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCjECV3ytGgq9do5vS8gH95Hi7X5Cm9PqXyWrKfjpsf7skKNvRQsfOzjw9p4a'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScJIaXOGngf4epfaKxOEtJg5Wxyo5jiX5OjIKxkypz3aiwnqhKvawziw6ouii'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScIKCRHs7ugrpeonQ7t8597xR86MMgN38hU8rbRYWa9oc6BeugrTi7Gyrft5a'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScI98IPGviDggwdcizdjg9mO4qf8jwumXPYpXj3Evi4wr3KhykcNPxxioke7r'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'lucy::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScjOAbn4kPnnkkcxS5V7HREPp5RovksQT39NmwSh4Nb3iq7vXPfk5933Eyuur'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmZo537cguMkGZUEkETBcB1ytGb4w9zkghtf2V1MmqUCzi'
id = 'tags-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qme2fURTTGenmv4Q37AcjRPszaptc8WxZLBViCi7rHqg9G'
id = 'origins-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTvKjN6pQiYqgY11JtQnxMQbAp1TfK8TKUyDn9uLus8G6'
id = 'kanban-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmXdA1jW3sxFMM9YiPMANSCpwoqK5bRKaRj9E9DWVLxsBy'
id = 'notes-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmaHRhRZozYmmjkJiavN4HANP1yfbE7r3Wp1AAaKumFYoH'
id = 'tasks-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmZnfNNAtPEx9dSkwtzTqE86u7GzQ3KUvzJHk8is4ggcAK'
id = 'fields-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmZbQBdQDvxyWSGowXrcWtTHbywUJE4bDTh8QU9ghquPU6'
id = 'personalinformation-test::0152b97c-7819-4828-8187-433f6dab5f32'
uuid = '0152b97c-7819-4828-8187-433f6dab5f32::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qmddhy4DaGnyrp1ZTn62duJbMh8G5TnX15kJWFxQPuKENy'
id = 'freckles-test::fd4840e6-f120-482a-beea-334d911eae38'
uuid = 'fd4840e6-f120-482a-beea-334d911eae38::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/MB8hdv/tags'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/MB8hdv/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/MB8hdv/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/MB8hdv/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/MB8hdv/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/MB8hdv/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::0152b97c-7819-4828-8187-433f6dab5f32'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/MB8hdv/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::fd4840e6-f120-482a-beea-334d911eae38'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/MB8hdv/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
