bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/BtFdqv'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'lucy::origins::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcScIQUKbsJ34z9vkfQW49xBYivgcumdipFXEaDUesjm6ubj6hd3dVeumQkvmqi'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcScIrWpd8kMew8z4x8daAm657kKm7qjb7IjjhRSwkrpxvrpIh8ftNg8Vevatua'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCj7fwE7UTO3x7v5eGPX8O9pwVjph74HTfrVBwTqjxnmhayUID6Cd4ADy6v7i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcScJby3aRKwchqy465F9v5pTaR34unp38OfWno8upQ6usjtuZs8HA44FJAssxz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCjhc664TtMS56wtM6C3fOyngS7m5mb4mGtz3xAMJoig3y36baNRyGU5Rfhjr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCIawsc9QIr9gdtcTEBgb7naXyfmcaaNzXUxYgnryo7f3jbvB34c488v5JRMr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'lucy::freckles::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCi5IuEaqIvmpo3zXJMQnbD36egszcj3smtUkP74qohmpxX8jF7fM5c93dYzr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeKjDnW2RYQwTguAtiaHyhBiEkroP4QcHSsWdnztaGmCT'
id = 'origins-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmY5hzbvPET4W2ZPyzhdpbNd1tqkUSvAwSnXQWw44jMbyU'
id = 'kanban-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYULeLPPfiC8yAhvwvxcjYgAmzajtezuWB3JiJ7XHCqe4'
id = 'notes-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmaBbotBPBSgLiqmFwgqX2Tf65rQ4CrdKKwuemDtDjwqYo'
id = 'tasks-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUqFKMUNmgZdMvsK1jdBwZ3MtEaJKurPFQRFG4MDDioVN'
id = 'fields-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmabuH8z6RYxQq8iMhGkiahS6gSvsVSG3ZxCwaMVfQAbLg'
id = 'personalinformation-test::c5d3e3d4-e12f-492e-9261-ab6cf337f3fb'
uuid = 'c5d3e3d4-e12f-492e-9261-ab6cf337f3fb::3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmY5iSifHVjZwBYheJzX9zrZwJBxVtjkqos1jksvkub8ox'
id = 'freckles-test::051792a2-1184-42ce-9f84-a8b80955b413'
uuid = '051792a2-1184-42ce-9f84-a8b80955b413::3169c5fb-64b8-4668-949d-ebafc253d684'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BtFdqv/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BtFdqv/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BtFdqv/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BtFdqv/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BtFdqv/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::c5d3e3d4-e12f-492e-9261-ab6cf337f3fb'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BtFdqv/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::051792a2-1184-42ce-9f84-a8b80955b413'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/BtFdqv/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
