bridges = []
persistence_dir = '/tmp/tmp.z6wMAi97wa/tryorama/PSFbFx'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'alice::columns::449918f0-8b1f-422b-857c-808c1ef2b3a9'
public_address = 'HcSCIZ3UAaZ8Nvzqwo6fR9j9qkNGcysq5wdAIVcYBdgmscepyxU6DD5Un6cii8a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::449918f0-8b1f-422b-857c-808c1ef2b3a9'
public_address = 'HcSCIg5iXP4tQexoqmoebxUrW5xn3xgpqJyYpxwub4hudanxqBqoanTD4yeodha'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::449918f0-8b1f-422b-857c-808c1ef2b3a9'
public_address = 'HcScIK8M4yqOrtoa97b96Qn5c5jbRNv6zsf7h7F4uarMh74p9sU7rddTEdzohoa'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmPicjELUMp91S8thgcqR6hUKQKRVjniDDxvc9JWeYbhFC'
id = 'columns-test'
uuid = '449918f0-8b1f-422b-857c-808c1ef2b3a9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmX21oRkkqa6uEJeGVqZUiy11ZH5KzpTqbvh5LzX3c94SX'
id = 'notes-test'
uuid = '449918f0-8b1f-422b-857c-808c1ef2b3a9'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmSz3ZsMkNUiBTPMb7HygwcfJ29c8f5Y3qR2GbPjMkjoF6'
id = 'tasks-test'
uuid = '449918f0-8b1f-422b-857c-808c1ef2b3a9'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.z6wMAi97wa/tryorama/PSFbFx/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.z6wMAi97wa/tryorama/PSFbFx/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.z6wMAi97wa/tryorama/PSFbFx/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
