bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/rjIRA7'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSCixMDUSVwbpajk6M64Np3vbPk7Dk9zi45f8zwU4Kumpt4gGKtT8FZxcp7eoa'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcScivoe38O34G69Sod7Z8iBTYZkb9yh9yKAnmAHgbnkekgsp4n9coOcAmzhabi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcScJgQNGFwap6gexvHmrIAuSN6jyfyxfujS6JJcc4abvevnIGPHY5CdJqosdgi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcScJyUhW9wx44zx8jfq9FoETc3a3h9hsDu34D5N3xHuFjdqaTHXFWyZwtrxw7z'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSCJitKGq5Umdxnwm6Fy4RGzN9d5jeouBj44G99yhwPBssmZ5SFu9HE3mKv9ci'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcScJoqSTMrtuvthdpoGF7Gv4j6qAirnko7TJDGVQDxxgk6y56TC7cHRZixvfqr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRkZXAU5eLc97AT1VHyh3AhfAs2AByVhwpV3rxr11zBna'
id = 'kanban-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPhVNhYLSezQ38m2rj61gJpHZu5B51oEAcVHhGhNEaMzy'
id = 'notes-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmdY8guqM7UnX1RReGfpsVLJSiwvXUa68FvuZurdhhSSmW'
id = 'tasks-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmdwWqWuiSe6EFvkX5zhfD3T4nJPZGKhpCZYJW64gc891e'
id = 'fields-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmRS5QH4G8oPqjYfvxfmANFF8wTY5iDwnp6wM5ocWuCYd9'
id = 'personalinformation-test::02719631-6303-4d8e-b8c1-611155ce2aad'
uuid = '02719631-6303-4d8e-b8c1-611155ce2aad::98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmVLY4FKCq2Lx6M8pVUDJpEAoAJ9PrWFXMzf25cD2YRTWt'
id = 'freckles-test::f6edce91-1156-4adc-8517-442c564a2dc4'
uuid = 'f6edce91-1156-4adc-8517-442c564a2dc4::98ca96a2-3e14-4667-901c-7749cbf91902'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/rjIRA7/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/rjIRA7/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/rjIRA7/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/rjIRA7/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::02719631-6303-4d8e-b8c1-611155ce2aad'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/rjIRA7/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::f6edce91-1156-4adc-8517-442c564a2dc4'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/rjIRA7/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
