bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/nniqGH'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScjzez3fz9k5exsx6N3awmwkEEadjmagOBXJAQVq533dwuBE4pv8TArgryodr'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScID93Iee99ro66pKTP74gIu5I8zcxhq54RE4yYhEcrcr3ZhA834WXAsx8cti'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScIIuIuNy5su9agxsaMpmU77RJradm6hc4WqEK5ROh6k6h6Hg6OVQkRHb9rvz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScJ6yM4j4Pmk3r7vwYuZih9Te5tcn5nGO4ppSN3mtivy7w6JaXEA6y6ZDzhbi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScJX49dnxkShv5gw8QoPDTeur7xoghk8v84hph84894g33875cRMpXZyO5b8a'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScJxKMoSWg8h4mireirsAzeyei763hyoeU8oA7Sovb3bxkJf8U5EYvvJqm8qi'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSciJmiir4rqf6bp9P9PWAitRIwc73carKpmyt6uPyusjobhqRfveIJqvdztci'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmWyriGuATgo1GFQgTptmfCxeLZXGMXyadLtCANQDkY3K3'
id = 'origins-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmcDhhqTmDs23m3Y5BkdBzQfGL1eYDSfAnnsBMQoCwMqvG'
id = 'kanban-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQ5y4jfcu9qXKPp5ruu8ooAzvJ2Lb4Kzwmr9UpQLAoobR'
id = 'notes-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXDkj9aqA28zUksXSwonAF3nSzPvgycUnZEqsyAvJ7CAu'
id = 'tasks-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbWbsBwqnuGBUvnBhVXSQ3f5qMGihdEFPsyDp4eK3ognT'
id = 'fields-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmY31vGpqTcJSQZypvNpXk6tu1WgRFAugpbY4WeGMvsVCi'
id = 'personalinformation-test::ebba7f35-a159-4990-96b5-e6542ead9b28'
uuid = 'ebba7f35-a159-4990-96b5-e6542ead9b28::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qma8Xq6UMmagyzuug5iM8YjrVe73caRyNrQrtXHMWBoVU7'
id = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
uuid = '33fd973f-e5ec-45c2-b4e6-bbd294cae814::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/nniqGH/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/nniqGH/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/nniqGH/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/nniqGH/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/nniqGH/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::ebba7f35-a159-4990-96b5-e6542ead9b28'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/nniqGH/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/nniqGH/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
