bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/Yuc2d9'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcSCI3595efvpV4EbwvRf8oH559JOSizj4YW8m4c53zv6JpnH87oawCxpVcvmoz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcScjuyFJzvyc8xnoj669fAsZMjcQgzxka8yyRPh4pPg4yqf8T6aZkxhP6dv7hz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcSCJSIQO35depqsy7AXFPiTn6Cgf4qww6HGfXTdg78mgcffnqUG3kOgjr9evor'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcScIs9i9vU9GY7rpkJ4NXJU38OmBzkmnFjWpEKueaebg74o3kDUhab3sCazafa'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcSCj4jZWm6u8amr5zJbUg9oKj5ua65rxMwSJEC5Hh4zo6onm4g9k8NCtjB9mcr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcSCJX6SCcFQesr4zq36fKd7d7dsXZb3i5DfvaWr4HyjecfpUpyXTqSomoj4i4r'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcSCih89PZ9MaWujh46KJF7XR8uory8ya7XYjwDsOT4xi34piQMfaskMu7utudz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmUZKwT1QApwdHFZ5XQEsxUZ3ntUjVNg89qyx3buPqv3mq'
id = 'origins-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNhagTkPhU9RbPLbWDtgF3F5XGUwn85Eiqfqd6UkQQzHH'
id = 'kanban-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmbBiX895f8YvFTAfYQj2F1TQBDMSQdVotJ7hcdV31joSx'
id = 'notes-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmd1hXdddUDpuA68CGiJuAvj3mRGNbwFfUkTaLZknZX1dk'
id = 'tasks-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmXYEbqL2Z5QLrbudxWhHpZTm1211QPbaB8ShcXfLKXvkg'
id = 'fields-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmSPH6SHXWy8jmrJwdfivXSd7Rrtj3nqGu35bQBTaGPL4u'
id = 'personalinformation-test::ef3f80d0-fff2-427e-b1c8-a519c158f494'
uuid = 'ef3f80d0-fff2-427e-b1c8-a519c158f494::89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmYJkRfam91Lrq2gnsYCEg3uxBRZiMFGgtDoKXc3dvdLXW'
id = 'freckles-test::15964c9f-a39a-4c31-8bf1-0bf15dc3d289'
uuid = '15964c9f-a39a-4c31-8bf1-0bf15dc3d289::89ccc799-816b-4283-bfaf-af070e28e47f'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Yuc2d9/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Yuc2d9/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Yuc2d9/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Yuc2d9/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Yuc2d9/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::ef3f80d0-fff2-427e-b1c8-a519c158f494'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Yuc2d9/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::15964c9f-a39a-4c31-8bf1-0bf15dc3d289'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Yuc2d9/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
