bridges = []
persistence_dir = '/tmp/tmp.2oszwWo19C/tryorama/FULfJu'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'rudy::tags::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScIMj4aeAfexczdtKKfWMEjcvpvur9nMmuiTQnRhofppu9keQrc7P4H3zhpji'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCiFJYaJQtm6hcqkWzW6CZ4Vocqb8ziNaAk9DbRS9cd5ukHrXO3H4tYmd87da'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScJHfqTvkyetb7thedp3A6Rdajqvmvjx9aOwGURuqzafgxFbER9Q3vsDxo7dz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScJEnFoUv3udm73yj69AXm45ezVGvj9yGQxRamVyofi5wep6EBPbdjxqzwaai'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScJY7M7E7mW3IkhqHe6q9UdD7jAs7u5JpxfUg8ym59an8bQF6rRnC8e9D6gui'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCjdr8P3vK8jpqg3udmFnWfgf4pzms9R75x7CiQ5kSzjkev759gM3evRIzgii'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScjjucdsjhbvemqbH5jTkh4NiEsvkt6YPxTWfPO7x4ceu48b6GVeut9zxthka'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScJH493aXGX8F3tjoWc76Nwm6sSbsqin788jqoARTjkcrr6a3vAW5QadRasoi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmTpGrkbrxrHT7gHzUKYuLJcer1TwYj8HCMKiT4GSu5jHn'
id = 'tags-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmUnZVzRcXX2nBYgfpTJDVQVTYHnX3R7bwJ1WRdUn4JmPF'
id = 'origins-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTxSTHTjwMwEW6sUizD8euRk2RV6kLqkXCT4NBXxMkgzq'
id = 'kanban-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQDHS5v5V1cCtik1RiZzBiZLdAmrFqCffe74oHWh2DqSW'
id = 'notes-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmdHzqRj1X2woEa5wxKVx4VHx8HfEK7jKyoXdhZFPLvFpN'
id = 'tasks-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmRzbVi6sBZ15yAS3ri7WXakpJ9XtbTMpkdbYhGS3qLcVU'
id = 'fields-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmcFyrBpYChZ34CSLk5tmp1LiQNmWYRh249xSfSVYT7xfE'
id = 'personalinformation-test::83dd0ea4-4834-4674-830d-61cb4e5fc029'
uuid = '83dd0ea4-4834-4674-830d-61cb4e5fc029::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmeYjU1hubDJth1NWHCmgPEddPzhnFQDkjoY99ttg9oV67'
id = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
uuid = '93309f35-de11-4f62-8af4-af46a19ab638::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/FULfJu/tags'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/FULfJu/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/FULfJu/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/FULfJu/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/FULfJu/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/FULfJu/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::83dd0ea4-4834-4674-830d-61cb4e5fc029'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/FULfJu/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/FULfJu/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
