bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/sYnFmQ'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCJV7qibRGso83h9x3dbHcTq76JrhmxrOOGSXpH4gkghtjoqaKUkoXxm4mxpi'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSciCuNc3N3vyse7rG7uDt8rrpuscu8rC5QtW9YmIVu6dypqc5Or963Yp9pDxr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCIT6DM7Fwdve34wJ5Q9KdQIY6jy9njimoJRbIe46yyryz4EQdkr9tMhsax3r'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScJOI3KRzHte7fz8CMe6ouc9OGitw6vND7tYQVFnoi5qnrr7ekE6K33PKwzfz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCjYmstqYnhz97vu59qyGD9TyV7Nde7Yw9Sto966P9YI38WpOnZqUsyzbnnoi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCIz4WGjDKokq4n8y9U4aw8NXPYpm9vZQI6h5o73T7fFgfF3rga747bdhdbsr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScJ383rgMvnb6he9ByDp9M7xbUkbnizNew8m8FjNV78ytgNn3Vj84t3M5GXaa'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmPFZhyBXvh2hQ5PS1owunyYQYXtYdgQiqvqPddeF3XkoQ'
id = 'origins-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmeSXu4dswfLrsRyzNTbymk8sKpkzwbRxAYRpfhv7GVRit'
id = 'kanban-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmUXgNsmbaFgMgBzaQJSAfaCyKu9iYGJqoi9FozngzLTy8'
id = 'notes-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXXAi39ozsnt2VevFJXXbfosLbd9H5GXBuGmT9kEoh4jt'
id = 'tasks-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUVZeALCVgsXi1cwvFJNtxMQYLvfAg3v8WSQ3pwGvT71f'
id = 'fields-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmYGqCv18T8F5J3qMbTSyZws3BPtqrss9RhAkSnJmegwAJ'
id = 'personalinformation-test::00d24dca-b2bc-4f2b-bc40-5bb1a4200f5f'
uuid = '00d24dca-b2bc-4f2b-bc40-5bb1a4200f5f::889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmVYSaV357KD231hRsiHoRnxtTh3yAhh1qy8XDYmFJ8JLj'
id = 'freckles-test::4b691b60-1794-4462-a39c-ab8fd0038262'
uuid = '4b691b60-1794-4462-a39c-ab8fd0038262::889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/sYnFmQ/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/sYnFmQ/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/sYnFmQ/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/sYnFmQ/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/sYnFmQ/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::00d24dca-b2bc-4f2b-bc40-5bb1a4200f5f'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/sYnFmQ/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::4b691b60-1794-4462-a39c-ab8fd0038262'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/sYnFmQ/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
