bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/BSo1A4'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScit45y4Bkbdnb7ponpphKq3C48opo78a7RJD5ynvFybsrGINr5696yYp5V7i'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCi9pvT68BA5i3dfT9Wp69mHtZ4dmww7MEmax6SZ8ymug3e5eai48637CWoNr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScI7T7t9PpeEw9ypJe8FobyYNbv69o5uY5q7ktDGbysdvtG6DW3Dj87dW4wti'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScIto73SHxAryjmnHDD3TBfMPkstdiweZWHcAtKmtrzqcc86ffF4SpnM9Heza'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCjWR4Ysjoo9q8srPT4qoJPDvqgjpdrXjVCcAN55ArnmvdNB3uxrBbtxxtfzz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCIX8SEmbpeiusdtPwujmBHZavfqxjp7OK37RG88CGtWxwTRReN87XgRb6scr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScJ8p6RxNNgcr7cmrGbms9s6gmmruwc44a4Euq3Fj7VofksStsNCyhtf6c5ja'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qma1JTKpyG4URmDcgPANiRVBr8TneiTXhipMMFE5kPNnU2'
id = 'origins-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNW3pea1AdCue3cNx2cmgD7F2Cpajbu45t3jmXMqfVpL6'
id = 'kanban-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmV8fqNo5sD6Uz86JnFbvQJE6BXcTnhozwm5WF4FoenDL6'
id = 'notes-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmNp9Bw3XNDAHHcBXJn2w8XfdH1QxZ7QXStRK9KUYpzdQa'
id = 'tasks-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbcZ4twcVVNPDwg25HwfzkFaN4w6xWzTctbjf3gn45krL'
id = 'fields-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmSviwAYnPK1hm7aU9VkZeE99AarpCfSWDMQ2M7mTBCnrp'
id = 'personalinformation-test::8d283709-0ac9-4e8d-9338-30a1ab813019'
uuid = '8d283709-0ac9-4e8d-9338-30a1ab813019::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmWLNDe1gYhjEcNzKmFKPYfsYPbHa2h7YZCyMMrgxPW5uy'
id = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
uuid = 'cda1197e-03cf-4b98-8fd6-8a713f367342::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/BSo1A4/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/BSo1A4/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/BSo1A4/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/BSo1A4/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/BSo1A4/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::8d283709-0ac9-4e8d-9338-30a1ab813019'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/BSo1A4/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/BSo1A4/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
