bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/dqlPTG'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCiU47dx7QmAppbfrSkZhCVi6wtyfqfWDwKGZn5r7uts8qsq8w6tH9ekYi8bi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScjXZ6JYQIgo8cfu9MeebZ33FZxxdd45OkUOQ9nntgy3vjyBnFofE5S5jtr3i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCiD4shabOtkhac4nrc9pApC8v5pcopKNn8Sx65wTAwuk9nqIUB8dkDsfk8bi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCj4PZgr74M6Oy4ijwSQvrAcked3owrY43pcR6r7Rwmycq56PGSVvdWm3k7wi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScISmxQpB7nx7t5zrggoXQUmnaxxkscMCA3hjJEseuxnr5r6F5Ed8533tdGYi'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCjfNrZ7h9mbviwraKNei7mW9zm49wyVMkinCdMf5ufdeaG3wPPXsu8qh36yr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTvEQoxuEYwvZgt4QRv82SPBEMAbv4pGa5KF6TJUdArZV'
id = 'kanban-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmfENeArJWfouiueEiFJNktR79wd7iEwxmBRps8ikVZ8xs'
id = 'notes-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qme7HaKn5K2zZARtCLWdgvkxzCGLpETeue7iPStGV6eGMa'
id = 'tasks-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmeXdovo2y5QMKi3eGE13tcLuuDB2vjDcCxtL9dBB8y5B5'
id = 'fields-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmPfYCiNLekSi11TKXdNdBZayoFYKQgXfJikscoJGyPi2e'
id = 'personalinformation-test::5f206656-585a-4c72-8d73-97d11e82529b'
uuid = '5f206656-585a-4c72-8d73-97d11e82529b::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmcZthhqvMS1UwzPt8YakjRTV65SnfRmsRLyfhEeW66oJj'
id = 'freckles-test::642d38e7-c187-4e56-92c0-f160fd5afa08'
uuid = '642d38e7-c187-4e56-92c0-f160fd5afa08::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/dqlPTG/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/dqlPTG/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/dqlPTG/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/dqlPTG/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::5f206656-585a-4c72-8d73-97d11e82529b'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/dqlPTG/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::642d38e7-c187-4e56-92c0-f160fd5afa08'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/dqlPTG/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
