bridges = []
persistence_dir = '/tmp/tmp.4OYPJetHpj/tryorama/DFOxL8'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'alice::columns::5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'
public_address = 'HcScIUZK59n4AOpsuiMfX6eG5FTzndg99XiYqJFJX4yxdphkJnO6b479uccDsta'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'
public_address = 'HcSCJqP8ZqAbogkkde4ma6t4z67Ocu5AcfbYEqT6RJhrcz43n6w3zpo9psCet5i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'
public_address = 'HcScIjW6SFReyw5shrPn8IsIGq5G9xu6sY9Aq5EZAxvnn4bsRbf8uSGt7ftiuwr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmYYJmyGErtD88cFTTUsf48UeXMSwBLMLHakbTduHZg2U5'
id = 'columns-test'
uuid = '5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmZHCQNULeC2hhTvE2gk4kLN8UCArZm5ybYHTxYiqv1uZt'
id = 'notes-test'
uuid = '5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmW4cHiM2qeVjYuWgkVbB2YHAoP917yqHxxsxDAhE34sZr'
id = 'tasks-test'
uuid = '5e4a15a2-d2bf-4f87-ab91-4db91b1348c6'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/DFOxL8/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/DFOxL8/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/DFOxL8/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
