bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/0ekDjD'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSciR333O864gce7vPHQehBPGhma9gjzIj978ZMiw6pGsun5D3jy9g6VX9bZbr'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCi8h4cCD5bq3bauoo6pweT9Iy3eomzdiqnQ3mdufozjx9oUfGDYGwzgwhsji'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCjG7EXPz73Wxik6QD8A6kU3dYBhc94iSARyQ58zy4hxixmu3qhwWXFoc6aoz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcScietQOOEv937rbqcuFxO8C8RIi7kubH9Oq85CkQXr946oBiuufRZvjfiee3a'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCi4j4jNv5Wd5gvs8e3mqGw5i7zso5wmTNoIv8u3Xp3un6ww4J96vHSVNjw8z'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCj6nrki593eUfrvtWfIWhRB9d84u8zHxFIsTVXkugic3h3vb5cVA3vx5Agta'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcScjVARExU7yrsb4f8XqRn5X5XOMvnp55Xzy3OfOzXw4p6adW9MEDIttayo5na'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qmb7p6mBV37tfhmhX8XYrVWGKtRvCcT5DTnFJgtdpZ36aQ'
id = 'origins-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmeYSH4uiDD1B7FxFpYishKeRbHy4PrVXUH6y1pxoE9N3B'
id = 'kanban-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPwfAmvYZLXHnXcE56XCLYd7iSZUUbcimp9WqaZEKjPuz'
id = 'notes-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXbj16YVJEEsvnueYT9rLNPYpyu4WvQKVgL5HJ644dvWi'
id = 'tasks-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUx9DQeZrXmN1PA8ahX5VVyQa8pR2hfREgJQqyD5Jja1z'
id = 'fields-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmQcsrDZH8ZyG8YEjxEC2cwdgEcKL372ebMC8iGAvHRmyS'
id = 'personalinformation-test::8de31e19-bcab-4790-ab56-4723e53f6a40'
uuid = '8de31e19-bcab-4790-ab56-4723e53f6a40::40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmWJ7PP9r5YLGVadVUNVa1Hor9WrSpSDcgj3ucMnseC1qv'
id = 'freckles-test::2a056bee-03fb-4871-a9d7-07acc3002515'
uuid = '2a056bee-03fb-4871-a9d7-07acc3002515::40c9d725-fb55-427b-8480-b4907c2e07ef'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/0ekDjD/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/0ekDjD/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/0ekDjD/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/0ekDjD/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/0ekDjD/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::8de31e19-bcab-4790-ab56-4723e53f6a40'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/0ekDjD/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::2a056bee-03fb-4871-a9d7-07acc3002515'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/0ekDjD/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
