bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/xFc7ga'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcScixkNTo8v8n8qc3CmwiSrmb5vh6hz45DSMGz4itoqfqus3FoYgvjgMvw9j6i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcSCjFU6zi9dtytgdssvOhzR56GMxu4rxS7cVjsKR3Mbqq7dbMNWf4iHfei545i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcScI8WYyawvypdd8beed9SbM7bVqtvzfFsVRsSIrte37p5dff76uF49GQonv8i'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcSCjTzayEE4erxbecqfrx7yAdI435qy968SO4HMQufG35nrO4FvAVJWN9spczr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcSCI4uFvuRHyi8ybtVsGYo35onu4mzo7BI47MufNbuofrkfudDW59tU8vdsh8r'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcScJCkR3BRigynknfVs4cKUf4wGrgtz4hY75pOM6ibv5a6t75Oudjbqzrtptii'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmem7H1NSpNJUoLiNdbwUgFFpc8aLyZWiay1Qfd8s2NRrK'
id = 'kanban-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPjz9jKtrrN5DLdUEvV8LdZUm9MZKcMJTZM6omS2Vqh6B'
id = 'notes-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmTabiqZ457XGHP7Z4v3vnce5JzLaVGc6fsrzFrY4A2Yq9'
id = 'tasks-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmQLMMUFJmtAEYzFe8rJ4ZUU5r5944ewJJZc7bmsG9mBAf'
id = 'fields-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmRTLJnnnn3ArSXMkyn7jWQTDeUDZz9eSuw9o5CkmkdP8Q'
id = 'personalinformation-test::09ac7739-f043-4a77-a10b-0cca65724eda'
uuid = '09ac7739-f043-4a77-a10b-0cca65724eda::a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbMT7N2TT61iUnFNfMddRCKHFr6MmYXzYUwCd33iH9rXK'
id = 'freckles-test::9307f75b-710f-4ea6-a067-0f414098b3eb'
uuid = '9307f75b-710f-4ea6-a067-0f414098b3eb::a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/xFc7ga/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/xFc7ga/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/xFc7ga/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/xFc7ga/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::09ac7739-f043-4a77-a10b-0cca65724eda'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/xFc7ga/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::9307f75b-710f-4ea6-a067-0f414098b3eb'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/xFc7ga/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
