bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/CZemUe'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCIdtVKSP36xnkd7XjbF4JQqWxbxcfjByGSq7qwUymp9evXMsiVOoM6gi47pi'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScis6d8AcCnvdpgcUcUEPwEJgyzfmdeVi9p86owJOedr6mfNTFK8ARXttfksi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCjFbBPo3HameoeoBy4486t4YcIzCgrBg6ah35S9UiDrctKOE98pB9BZ33spr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScJOqQdRYq9jnqw9Q35iiJg3mzunsdmDhEoWAzsrozbdbdUopM8cdCi8yn7wi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScj87X44fO6CVccpJwXueIVrz8sjmgp7xdqdumXnfw5vtyK6oOIIKUfafvq7a'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScJ8MEI8CGof5minx68y3Hxg7XdcdxgEC7UmxEUiiyde6k6s7r78pZujnSijr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCJ8yQb7OOas3hbkUDj3uponBqxiibwjsA9bV6ddurvx6puSiGcEakvifncgr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmXY5ei2q8tCvRBGb2diHjTj7jQ7pFnwiMf4ERvBSyyLBc'
id = 'origins-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRv9ga5obxctQqz6DPxVkJbyo4ZjadiwD49Hcx6ML7833'
id = 'kanban-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmTujJA3qJUgy2XhvjvVxWSYbegUV8n1GDuRmsSePfL5YK'
id = 'notes-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmf5CUzvxThU6C22RsBKRBZTf8spmynjavtWe2d9dgqXjr'
id = 'tasks-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmdzu7EiT4eM89tDytzJ1SsJLPPMdJ23z9aCeYnwniUumW'
id = 'fields-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmNbefGJ4cqrWnM7UqHAbuxgA5jBw3Q756ZECpkBgN68sV'
id = 'personalinformation-test::cc5e0eac-fb9e-4f11-8ce7-2affb7149d10'
uuid = 'cc5e0eac-fb9e-4f11-8ce7-2affb7149d10::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qme4LkdURYs1nEpK4VhrmvyPbPpPDw6ZCkVHYMFgMa9VBT'
id = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
uuid = '84b0e8f9-cc77-43b4-94ad-a41582d7b704::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/CZemUe/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/CZemUe/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/CZemUe/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/CZemUe/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/CZemUe/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::cc5e0eac-fb9e-4f11-8ce7-2affb7149d10'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/CZemUe/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/CZemUe/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
