bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/nJdVDB'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCjH7wToTots6cqzbA7K3gQoBJhnzssiUd7w6DDTF5swog4AfFb5g45Ayivsr'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScIfkdrBTyx6ehcqdaZmd3Tt55Yfuw437Oo9BbSXDbmhswW6GvoMbUvdp7nca'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCJHmvIB9yfhte8aCH45rXXhJ6Vzvawxh4zFzno5jusx5xGzjJ3E4rdyb6bka'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScJpoQ5V9d8tiuryFHRmU8o5p3Fs63yX6Y89vTMKHx5fr9OM56mRHfz8z968a'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScjdEQnn8jd43v3g7I5Uw867FrN6szvyt9j9ezKr9Dhrv8VtIBNd494VSagyi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCJzvXgjOmtifahhxg7hr9ChiE6uq3b7maAx4wSBn34ttz6xyXK5FQwEbnk7a'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScJ7N4cFsrinptnmyCVmKx6Rhmvvky6ZDZAnsXwr65497a5Gs38gjFFAYwpfi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmRxkGsNZP2Q1yXhwiRfxTotEicNzDRDn5TNL7bGUu5mvy'
id = 'origins-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmQvpxoiR4zLcbZgJXPGGm7jWnnLPN5nZRiV7mTsT3Eyqb'
id = 'kanban-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmVBYv9DcLc6fju9AXUKbpp5guuU3Bae14j7KpC6GbrsEM'
id = 'notes-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmU3pxPmfoaRdcmsDjcZigBDq2xKLVmYq8234Fp1tYfSxq'
id = 'tasks-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmPMyZn4P9iB7KcCLt4u5NkAJ9muQJc2qFaLxAScSjwp6c'
id = 'fields-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmQbvMFJggZDMPxTWMojpD4oymik27dZHaq8C76GaASVGe'
id = 'personalinformation-test::2a619e60-f277-49fc-b108-7304b80a7828'
uuid = '2a619e60-f277-49fc-b108-7304b80a7828::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmPpencuh7jGURJFSTNAZMM6UTcZSLhgrCg96E8hWb66of'
id = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
uuid = 'a66e1d3a-6ad0-43d7-9619-e3b4a622690b::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/nJdVDB/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/nJdVDB/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/nJdVDB/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/nJdVDB/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/nJdVDB/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::2a619e60-f277-49fc-b108-7304b80a7828'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/nJdVDB/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/nJdVDB/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
