bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/RgnGrV'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSCjpIRqapik9ihycYScN5iKuRyj3e5e6Np8iMo3egHdbtfcQp6Q68YTK95Taa'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScjYh3yieRyenmbrpE5fDoD7b3uq3csUKuFJaK5Buowstp9Y9AOBzNms45ehi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScIMPYRJpzd378d3bNqovxEikr4obudEN49p8CdVRG47wpxNVKoHKNfwfcifr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSCimcs9BgPokuiju693ghJzHEnTfniwRJqu76qdzVdocyqvvO8uNxBke8cb8a'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScIyxz7EQM5ifsevFRKG6vsXTtqojkndH7EYY3VWAtkgpfzgI86j73XpSam8z'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSciaOYn53u9kvvo8fOsz93nsh73Ajyom85o3neWPNporegIqfM8KfrA38m6nz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSCiGNN3vcyj7f3mczaSHCymbqqfbnhua9w977aIooMX5y9zkupkQVq3ng8miz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmWhapg9MKVmqX8oHFvLizv6gCL7Gzjep8fFgqdv4waiZX'
id = 'origins-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmaEK8Gr61M18zkMpYCW1GBge43SJi312yPPm3zNixVaB3'
id = 'kanban-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmXMyGVJrUGD2uveJEjzrQk4FQy5jPYwUTHhPJ8tSsZjcv'
id = 'notes-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXKaDmdKERMJfrreQNq6BSVtEwedfiyeMrjBhcx8FYdrK'
id = 'tasks-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmPVJJiiakMRi9hfz7YXJcuUjH8eDDwgjtoGYt1j4n1csA'
id = 'fields-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmNTtcWzEdfswLkTPGXf9kMUnojx5BUgUH9rW6rcQz7imE'
id = 'personalinformation-test::0761ff07-384e-465b-a5a9-9f2a19bfe18c'
uuid = '0761ff07-384e-465b-a5a9-9f2a19bfe18c::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbHXCgGeVAVNRTNVGTEJevtYx7zmtnw3Ra6g6KKvf9Vt2'
id = 'freckles-test::633afb47-8f96-4d88-97c3-6b05ef95752f'
uuid = '633afb47-8f96-4d88-97c3-6b05ef95752f::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/RgnGrV/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/RgnGrV/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/RgnGrV/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/RgnGrV/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/RgnGrV/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::0761ff07-384e-465b-a5a9-9f2a19bfe18c'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/RgnGrV/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::633afb47-8f96-4d88-97c3-6b05ef95752f'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/RgnGrV/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
