bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/sA3Dri'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'rudy::tags::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScjf8WiHQrrzpuymVNm6IbCfHzbu83eiC8W5DcfX8C6qynMwT9ZoBR83Nbqgi'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCiIYFKv5jtjcco446gZ56oWn37v6SFyfAkWtt7Pcrrc4q8797Nmp3mmnB4Aa'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCi8rPYSNS4s7t4s7SJcMwFvOjgrgwe5EH444SNgz3aSd7EMU7aW4KXEo5mha'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCIv7H7jxIE4gdtiraJWM6s5A8bmmkhiPT3kzcf8oiadmpujokWMuEfcyrc8r'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScixYESVjxe3djqcijoGNcjua85hrzgwj4jD7BH8HAjtprkVqFZAzBarbsurz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCJrGmNrJvmssday86FaMekwEY36g59g4imruDFSfafkqfTKfkiJ8pwyrfs9a'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCivXA86wS993nujp5vEzx6AdytjfsdNZ3g5AThFvktofoDzDVmsdNiagsimz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSciRy5dzeCkofmk8geOx9XM8Wsqdf64g9reIpyUXvidgsy8qhoB7A6ZE6Zmdr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmU4CN7gvvxpx5p4FZobR1cmSjpKPDnfhhAxEG5Tq8uniQ'
id = 'tags-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmQutjyu1gmtmBmAysKi97J7zWFGZ5vd4qswrqNt2RU7xq'
id = 'origins-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNnYtKAEggRsuFufbRZyPmKYgRVtTHNVWHmGMmsYPu7C6'
id = 'kanban-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmaNcK79mga5ttAcHDfZT4KphgXsdYLZeFhM2Vw5UL5euF'
id = 'notes-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWkkYJaZxunVzn66Sba67XRqsvCrBKuYm7744TJwyrK49'
id = 'tasks-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbA5oA41mbtKNCSUaAyhvc8NUjzidT2LDop1TqZETawmu'
id = 'fields-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmNmJt7GUuBFYypJr76drtNqfkvTLkmWBRRM89ZxfPtZDt'
id = 'personalinformation-test::63c93a7c-637a-4b94-a87d-1313b20e2423'
uuid = '63c93a7c-637a-4b94-a87d-1313b20e2423::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbrwEAXQjS1b7fqhLFkmxusDXYirSmATwMW9nE9egS2t4'
id = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
uuid = '747c6bb9-c2d1-4b5d-9927-b3ffd4174748::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/sA3Dri/tags'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/sA3Dri/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/sA3Dri/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/sA3Dri/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/sA3Dri/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/sA3Dri/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::63c93a7c-637a-4b94-a87d-1313b20e2423'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/sA3Dri/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/sA3Dri/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
