bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/hhAdGg'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcSCjGxqTn6Mnqvqgnm4hiTUIxerz4drfDRtzM9OEfb88ztqA6ayGOGJ8k4sy5i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcScIevbNS9Zm5nggcDnMt7XqezdvwtweH5Y7ADTJOWpz8kcE7KbvGhaG95cpgr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcScjad4PK5PjgubdnYsfaj3omXi4s4s3TshisWAjj57po5o6dH5bOcPU84X3ez'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcSCicYOQ4HUut6czpObywB6sQtizrt6yZn5dQOWUJnsw4zc7Y5ra9f4B9bcama'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcScjJ6vhYMbcgzqfyG9IFT9k7UCGyi4zqGotiIDqbyjgixe9fk8yn3sP4jKtxa'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::21502273-7cde-45a7-ae26-c1d335993a21'
public_address = 'HcScj6pKUdPE84z83cSnyPIW7vVuix8nypOrRjhmg5nzm6yehcENZX4pTy3t49i'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmcepKbsTX4PSPw9okiHXp3x3seMTVMZPdgXzWZMgJJAEt'
id = 'kanban-test'
uuid = '21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSrFy7gAG9JKk4sAYNG5iva5kqhuYTdMVexDdfXr29u4a'
id = 'notes-test'
uuid = '21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmRHLxDTTnYmQjzwaskGM9vkcgVRBGQ7qmMXZUVx4nby9K'
id = 'tasks-test'
uuid = '21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'Qmc5xPesmzFhAuuPh7FVssiK8k8Y5NcqHgDQdofZBay5Ux'
id = 'fields-test'
uuid = '21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmawNKb8dVDw9bhDkhrqPytPZGb5PcFdsuJK5tmTWUYoDh'
id = 'personalinformation-test::84785b78-2379-4c11-9e67-fc541e6f6c37'
uuid = '84785b78-2379-4c11-9e67-fc541e6f6c37::21502273-7cde-45a7-ae26-c1d335993a21'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmYt6hRTdNy2yd6QvkCY6HfRCSV5CgJ6izH2g7498sK2a8'
id = 'freckles-test::e1117c58-52ca-4564-9d55-07b0a876f643'
uuid = 'e1117c58-52ca-4564-9d55-07b0a876f643::21502273-7cde-45a7-ae26-c1d335993a21'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/hhAdGg/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/hhAdGg/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/hhAdGg/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/hhAdGg/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::84785b78-2379-4c11-9e67-fc541e6f6c37'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/hhAdGg/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::e1117c58-52ca-4564-9d55-07b0a876f643'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/hhAdGg/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
