bridges = []
persistence_dir = '/tmp/tmp.MjOx6luAGZ/tryorama/0GMCx5'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'rudy::tags::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScI395XCBxTde53iOc43z4uqTQHqw7vZ7Xo8m5Ek6yKt8rEyASj3syxbiijez'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'rudy::origins::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCioVC8O9CDgykk94zCvqH6QaHqgbx3BV6z8Rd8OW8K7as7m8z9s9Cp9f7Fuz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScJs33NPAXR8wccoaIQv8BA66Vag9ek8NB38Kp87FjOyqoUETQTqYcq76k3br'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCIw67SGP3Sbv3tvZ33Fp6rZZsiqs89wRdG5S8IV9Vd3piqWAovZJogvgybkz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScJV3HFuCjye6wkaWXgqANiBkrjdhfve5cSzum7BCnkz5dAGVXobZUipyeghi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCjkD54baPWpaek5TweXZuGBhrfhuwo3e6WSO4xznG3z5h89KEWbvaV398Cnz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCI8X57V5ey54efawETx38HZmeo5fcarucft9XNC4pbst8Az6mEC9UR4Y8hqz'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'rudy::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSciTh6Bz85SKc9bi5WC76t9GAEtsgyjywUqhbBoj3ank5bx5fs976tou694Ir'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'Qmf3yD44i1RdwfLbavejVRaDW2ts6oyTbKhKq6t6PzhXdf'
id = 'tags-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeY3adbehJxnTaBKudvdknhDhpDA7PeaHfSmWVUShU5K5'
id = 'origins-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmb5F5DqPpjtXZa3bcUJSqsy2eD9Q8ZAFKGqjaVWaxs86f'
id = 'kanban-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSqxSQ9EGh5xMNjmoL3AAc24rHUsdJmrdAGfYJ3DwMruc'
id = 'notes-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeuwMKfLwq3GTows2oxEDrnV57dbXVgvWhxpJkLdwzbUZ'
id = 'tasks-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmdrXAi1JaH1WzGZ9gffDmUdq4zcx2ZpDw2R6Bsywb6qAk'
id = 'fields-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmS7o7cUdNh7eXj9w64VDXdedhgG41eRyqEs1MR1BSiPNm'
id = 'personalinformation-test::4a5c5c7a-06ee-4d7a-a7b9-548dba41962e'
uuid = '4a5c5c7a-06ee-4d7a-a7b9-548dba41962e::a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmfTpUaoqtzHH5ziER6xVWCzHWGun3qViWwTynGsXdXgwc'
id = 'freckles-test::ba5fc91b-5602-4eff-80cc-34801d511e2d'
uuid = 'ba5fc91b-5602-4eff-80cc-34801d511e2d::a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/0GMCx5/tags'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/0GMCx5/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/0GMCx5/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/0GMCx5/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/0GMCx5/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/0GMCx5/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::4a5c5c7a-06ee-4d7a-a7b9-548dba41962e'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/0GMCx5/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::ba5fc91b-5602-4eff-80cc-34801d511e2d'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/0GMCx5/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
