bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/ZZ49vM'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'rudy::kanban::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcScjKIUZyyfxw84erNMQhIWQ4Bwnh6cs9I73uxjUJk9pfr6BHr7X9cIu5Kn9ui'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'rudy::notes::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcScJfBwzVq767fbfox8Ve5Ezw9G8Kz9qQ6dezrYJ8ix75chxImAI8sc9H4mcdr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'rudy::tasks::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCJ4tHwJP58T3cej5hhIhoApWqw65dc3DTR78YnpxhikhjDk7Hzmi8YGrq6mz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCJa3I9wyTysh8yrFr7Dx8nwx9ydhjaBmQ7XGqdOtofeufKpykx5kY3Dqpv4r'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSciFEd5Rww87iztcemdQQ9HDwhxgdj3qYHV7W6y5DFob8tiUKA884ZjEVt8wr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'rudy::freckles::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCjV9gQy7bCymtna8VxtcKOscwwvrqx3Xug53xq6ChtsgcXoI4IUIY3U3xrwr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmZ2TGpauVUoTTTPwmqNpwmCLcDavKr4utUxdJAmHXZfXE'
id = 'kanban-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmbL8eFNsa9UYtJY2iqRPWVfhHok46fdoYCAskt6gakegE'
id = 'notes-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeqVu6wrMg1KapacXdZDLr5CC4WkjMKYUMXdjubuHeDUE'
id = 'tasks-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmap2ypwmfw4DccYDrJDDZF8iGRbKNsMbcAV69NwRLQ5hG'
id = 'fields-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmUn9qD8f2YfcBJ3xWv7WepiWQWXKNJTgwKkUvmB1kzbWP'
id = 'personalinformation-test::ddd0f407-04a8-4f0c-a6fb-baacdb5cea84'
uuid = 'ddd0f407-04a8-4f0c-a6fb-baacdb5cea84::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmSNFSC8iDvsCT8FUiFUFY97EZcTLaAnHmX6UsysFtzbdU'
id = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
uuid = '59280fe2-f7cb-43ec-9f20-e4d7cd883a8b::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZZ49vM/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZZ49vM/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZZ49vM/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZZ49vM/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::ddd0f407-04a8-4f0c-a6fb-baacdb5cea84'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZZ49vM/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZZ49vM/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
