bridges = []
persistence_dir = '/tmp/tmp.4OYPJetHpj/tryorama/D4DJID'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'alice::columns::e449de77-866a-44bc-97c1-cb50646d26f0'
public_address = 'HcSCIRkTVJnof9ti6qQSK6qe6NK8Nsw6oeDPOKxq5Unzimos8KEpfH5hw4ahokr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::e449de77-866a-44bc-97c1-cb50646d26f0'
public_address = 'HcSCJNTG8GMi9uu35hcKDMVg6659XMxyqz4mrSKNEPu9yjntIVoPiHegg5ymcxa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::e449de77-866a-44bc-97c1-cb50646d26f0'
public_address = 'HcSCIstUZmJwyx5bqdar3naAXI54n6rawZaH8IgIOi3frtpig4jFo57moS8Cwvz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmXywuvVCqTp63pkbxuMELPprDfNkJGGsoZ27LAjRxCkcF'
id = 'columns-test'
uuid = 'e449de77-866a-44bc-97c1-cb50646d26f0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQSRLav6CpjVipsgvRb1XqQJSCokFi31D6GtrCezeZprX'
id = 'notes-test'
uuid = 'e449de77-866a-44bc-97c1-cb50646d26f0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmfDwRTQgSJtT5hRad82zkwGKno4qNrKsVthn4yaaEq5s5'
id = 'tasks-test'
uuid = 'e449de77-866a-44bc-97c1-cb50646d26f0'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/D4DJID/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/D4DJID/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/D4DJID/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
