bridges = []
persistence_dir = '/tmp/tmp.9VlgWQxqgQ/tryorama/jyONRa'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcScIs77zJIvS3azcgCkBMskt9Cv45sj75akevDdM4ugc5xfUN8a8wc37eNMxzz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcSCIDy5Aumfpepvir45cygUWOQM3jua76R9HjBX947rWVwsa6Buhhm9Bzb4j3a'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcSCJTHzMOc64u674e3heSSV9gIPgobvmEygHeVUuap4erufj93H9TJoMBFp9pr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcSCj6R7PHONWo3reqJi8CsVGnQfkrrgxB9V53qirG8d65Ct49P76gmro8B8Ajz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcScJomswG7Qn7cbtrgYk565n5gx3Fcnrsp88XaEyn86P5w9uM7RzZSbTzkfvxr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmU4wjuHQmGr42z12U6zvMPYPWHjgced8XzH5SHw9CbuKG'
id = 'kanban-test'
uuid = '45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmTEAtWeMCoTmuFYov7Gm1ggKymWTTN3pFQ5ZEDhBqUoW9'
id = 'notes-test'
uuid = '45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmbZ9zH4BHHpadLDds5KN9XoNczGAuoTGUqiruQV7JSFYo'
id = 'tasks-test'
uuid = '45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmfTaEkSAv6RJm6piuxswbNrnN6CHcNGjajWhi47w5fmrR'
id = 'fields-test'
uuid = '45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmdbQTsxiTozzQaj877JeYbjentCsJ9Bt7bNFxfAQ14vdN'
id = 'personalinformation-test::14ba0f5e-062d-417e-94d4-9564e9013dcc'
uuid = '14ba0f5e-062d-417e-94d4-9564e9013dcc::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/jyONRa/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/jyONRa/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/jyONRa/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/jyONRa/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::14ba0f5e-062d-417e-94d4-9564e9013dcc'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/jyONRa/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
