bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/Vc2E4O'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCiVUVy6fNcbbrco36W4pEE8SZA8me3Ix4bRU7vGOhjizmge4bM6Sy6N7Ax3z'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScIoZHIWzoun5negqCZq5X4D3Cozcn83sbOWvEyP9oe5sgMR8pjg7qGU8w7yz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCInpxCmup3uwixdRv9VzH4vTqhhcxw9x9vzrnRPtxhvjyVe7ZcVfRaonw5va'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCI5If8teFptbd3r3x7OI98qpnQ6K7i4hxmy4GZamgcnngvgKAZRKSszkrk3z'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScIZwxbWih9i6zngu7we7Eg45hZgwdcCvw9hMY4m7PmggywF595xrK8TWdkbr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCiB5WKts7gpv8h9HGf59gP9Y9k4rihnInJ6JWoKcn5e77XVD9ygHKxgppx6z'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScIq4a4Fo8VYa8rmXi4tiRFH9Bv3c59iVKErMc3Erdfeywi5Rqbv9XtSb4eca'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmPFZhyBXvh2hQ5PS1owunyYQYXtYdgQiqvqPddeF3XkoQ'
id = 'origins-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmeSXu4dswfLrsRyzNTbymk8sKpkzwbRxAYRpfhv7GVRit'
id = 'kanban-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmUXgNsmbaFgMgBzaQJSAfaCyKu9iYGJqoi9FozngzLTy8'
id = 'notes-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXXAi39ozsnt2VevFJXXbfosLbd9H5GXBuGmT9kEoh4jt'
id = 'tasks-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUVZeALCVgsXi1cwvFJNtxMQYLvfAg3v8WSQ3pwGvT71f'
id = 'fields-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmZtB74deemFtQ5u9qAPL4Zg7CvJwfojzs5SzpJNigE5JB'
id = 'personalinformation-test::f76445e0-1b62-4c63-b6ab-63fd01bc9c4f'
uuid = 'f76445e0-1b62-4c63-b6ab-63fd01bc9c4f::889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmVYSaV357KD231hRsiHoRnxtTh3yAhh1qy8XDYmFJ8JLj'
id = 'freckles-test::4b691b60-1794-4462-a39c-ab8fd0038262'
uuid = '4b691b60-1794-4462-a39c-ab8fd0038262::889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Vc2E4O/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Vc2E4O/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Vc2E4O/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Vc2E4O/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Vc2E4O/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::f76445e0-1b62-4c63-b6ab-63fd01bc9c4f'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Vc2E4O/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::4b691b60-1794-4462-a39c-ab8fd0038262'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/Vc2E4O/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
