bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/ZwPqeX'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcScIGNIkrrcpnuyv4wuc5DRCp5Nudn9cej9HwNzVrvkadktEUVMf9yA4effksi'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcScJJ5iISGn9y8s85pWds8uC6G9Eih8xE95VpHx9p9J89MoAEoZc86QaYt4p4i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCihn8yPEX58kyf585TIF4XKGFvexmo4s5XMQ4YED9UajcN5SsE4XFfHwezfr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCiDZwhZWc4sobhmw55ebXXvjhvbsip8TxxDadUa5so5tmnJBkwkREb37akxz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCiEQMAddkphcgf4En4JNt75dkdfbv4hj8w95744on77tjfKVzYkkRmdesk9i'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCiwJ78QYp6Bon6uuNPEjYN3Fcbr7ts7Dx8KPwfzB9tab9waXPpi3Aehg3z3i'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCI8rsA5S5ref5ybUiF88U5een5dmu6kFsN3XayMtngpnmidwirW6Tk4zhjkz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeKjDnW2RYQwTguAtiaHyhBiEkroP4QcHSsWdnztaGmCT'
id = 'origins-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmY5hzbvPET4W2ZPyzhdpbNd1tqkUSvAwSnXQWw44jMbyU'
id = 'kanban-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYULeLPPfiC8yAhvwvxcjYgAmzajtezuWB3JiJ7XHCqe4'
id = 'notes-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmaBbotBPBSgLiqmFwgqX2Tf65rQ4CrdKKwuemDtDjwqYo'
id = 'tasks-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUqFKMUNmgZdMvsK1jdBwZ3MtEaJKurPFQRFG4MDDioVN'
id = 'fields-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmPzqjDD2QHeB5LGBCwqgEEn8gqm2roGmxjAAuPQnwuwoZ'
id = 'personalinformation-test::7892b06e-e228-4b74-85aa-aad200762a71'
uuid = '7892b06e-e228-4b74-85aa-aad200762a71::3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmY5iSifHVjZwBYheJzX9zrZwJBxVtjkqos1jksvkub8ox'
id = 'freckles-test::051792a2-1184-42ce-9f84-a8b80955b413'
uuid = '051792a2-1184-42ce-9f84-a8b80955b413::3169c5fb-64b8-4668-949d-ebafc253d684'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZwPqeX/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZwPqeX/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZwPqeX/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZwPqeX/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZwPqeX/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::7892b06e-e228-4b74-85aa-aad200762a71'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZwPqeX/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::051792a2-1184-42ce-9f84-a8b80955b413'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZwPqeX/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
