bridges = []
persistence_dir = '/tmp/tmp.9VlgWQxqgQ/tryorama/tBv6bY'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcSCj6Xb9bj6eUbzvbH68UNBpOzy9j84t5Go9Vr9t8Xfxohf3ZoDmj46tUarpia'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcSCI9v6GvJO3Z839dBt5OcrH7j8NoojvpK8UNyohqz9fv5hByR88jo5MWIbd5z'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcScIa48dyPIPotoyovoBBDeir5bfany5yYgv5BRWNho5on5c6N83PhkNyun6dz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcSCiIaoc3qQjevjwncySQWCt3Rv3xy6a5S4QeqcOeCwjcue8vbRPC36b6Si6qa'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::a08ba0a0-027d-4239-b608-88a225cf5533'
public_address = 'HcScIa3KXiVfbmiyq3sJ55b56HKin84zj6weTNmmreisw47iz4fg3q6SJiZfgpa'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmaFZ9hSpG3Vza1QsXAqtm622Mz5gXDbQUXreaDfLCFvrD'
id = 'kanban-test'
uuid = 'a08ba0a0-027d-4239-b608-88a225cf5533'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'Qmeiy4HpFmEioqahyQq4uBzYc93YnLNZiagUQVmyrfiNVu'
id = 'notes-test'
uuid = 'a08ba0a0-027d-4239-b608-88a225cf5533'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeLboBHgzqKRGp3D41jMTN64w4m2RzrxfhcCFuzuawVH1'
id = 'tasks-test'
uuid = 'a08ba0a0-027d-4239-b608-88a225cf5533'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmVsXQFieDTqZkNsVyuQ35dfFAdfcwmh4AYuGRzJuhu7BZ'
id = 'fields-test'
uuid = 'a08ba0a0-027d-4239-b608-88a225cf5533'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmWhrxRfaZD7NY7srNrpm82NR5sDz7nEv8s21dZurfxCiN'
id = 'personalinformation-test::53dd8ba9-0383-4da8-b92a-115671da1ce9'
uuid = '53dd8ba9-0383-4da8-b92a-115671da1ce9::a08ba0a0-027d-4239-b608-88a225cf5533'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/tBv6bY/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/tBv6bY/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/tBv6bY/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/tBv6bY/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::53dd8ba9-0383-4da8-b92a-115671da1ce9'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/tBv6bY/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
