bridges = []
persistence_dir = '/tmp/tmp.MjOx6luAGZ/tryorama/vME9ZS'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'arthur::projects::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScJpI3Sbt3qgzs5yvK4ShVksCn7zydmu5PE7ebf6BZ6cb6DAbFstzjhzv7rri'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCIRkP747SmW4e4q8Q8EgPgFzo93a6obGCVdPckj5ch653gxaK3t3dB3Ixz3a'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCIsaA693mO5ijfeu94oiPkg6vgiuptoOg5aoHIgs3goyf8fhtm8jQcTcgxiz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCIBK5ciP6Yti8j6sME8JAxV75ph473IVGZUcgkhnwbdg6K6f5FN7bPg9arrr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCj5BE9rQCMmhiy6E549k75txvCEXv4VkFEB97edOa8xuusUwDX7ravacq9ar'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCjM37EnJcMpksvkvaf8cyZvostprg3J3sA374YbN5BGp3B3KVOmS5UAwchqz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcScJgKG6KUo35iqi3QO3nRBZjT7sgr3dCwTgxRNd56aawhmRibPD8Ff7Apdd6a'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'arthur::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::a043e6cb-e794-4163-8ac2-cfe2e58e760f'
public_address = 'HcSCJdA87UaGjz9x4vqsQp7VaJKso6nq7NE6h5WZTjnwz3zc3Nh96og7UrZ4Dyr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmTowXu1g5ovGc6jNVzshdPB3h1Y4wUhMq1LF5FXemm63M'
id = 'projects-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeY3adbehJxnTaBKudvdknhDhpDA7PeaHfSmWVUShU5K5'
id = 'origins-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmb5F5DqPpjtXZa3bcUJSqsy2eD9Q8ZAFKGqjaVWaxs86f'
id = 'kanban-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSqxSQ9EGh5xMNjmoL3AAc24rHUsdJmrdAGfYJ3DwMruc'
id = 'notes-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeuwMKfLwq3GTows2oxEDrnV57dbXVgvWhxpJkLdwzbUZ'
id = 'tasks-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmdrXAi1JaH1WzGZ9gffDmUdq4zcx2ZpDw2R6Bsywb6qAk'
id = 'fields-test'
uuid = 'a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmZ4s9Nya4auqLCbw3EXDWV68yCs1pdk1uKsrF2N7f9VC8'
id = 'personalinformation-test::f303d507-fc9b-4cc6-89e1-a03b7c2d948b'
uuid = 'f303d507-fc9b-4cc6-89e1-a03b7c2d948b::a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmfTpUaoqtzHH5ziER6xVWCzHWGun3qViWwTynGsXdXgwc'
id = 'freckles-test::ba5fc91b-5602-4eff-80cc-34801d511e2d'
uuid = 'ba5fc91b-5602-4eff-80cc-34801d511e2d::a043e6cb-e794-4163-8ac2-cfe2e58e760f'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/vME9ZS/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/vME9ZS/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/vME9ZS/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/vME9ZS/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/vME9ZS/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/vME9ZS/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::f303d507-fc9b-4cc6-89e1-a03b7c2d948b'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/vME9ZS/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::ba5fc91b-5602-4eff-80cc-34801d511e2d'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.MjOx6luAGZ/tryorama/vME9ZS/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
