bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/ztiU4Q'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcSCJW5URCVz6gbba3ox3bW8UYpA47vutVQjEZ7vECjgjuedHdu9wMy5a4v3tpz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcSCjVmEtW9nrjuzdt5Yr8dFf944IVs54BNjSpbdDtdddugvGryBc3GVYmn6atz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcScizipFfQ5uswseiwDRu6Fh4ufvi9379VxAoHpVR5m944w4VdreXrDN3yjirr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcSCixtCWHXcnoetikiA3zXvuAToqe8575yDV96brMazi4bmI5scI78hGog4mei'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcSciNatJhPbcerefxAqCSvX4uiknps5s893KJnZcaIPyddk7SX9T4HSJZtej8i'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcSCImD57zj665nTuhzRBkPzRVeyghd47ozDrmvWIwzv7nvc55pRrgWSTurwzfz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmbGHNTYEnW2Q9j6N25bYJWSaS1Gu3nCpr6qJcgsKEeSGK'
id = 'kanban-test'
uuid = '4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'Qma9UT8W1JG7B7bKCytWsAi1cGckSfABik11c1U59QLAo2'
id = 'notes-test'
uuid = '4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmZTX4sAybvBeZwTd4jos7UURizccWDRi3i7dJEzSYkfuN'
id = 'tasks-test'
uuid = '4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmcoU6Ht8kvYYQN4RSnY5brSJrQZyrSjemdVgmnVogMuFX'
id = 'fields-test'
uuid = '4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmR14nWC1jZtYsby23BxBRyLzfKZzvp4yrFwJu2CsZqr6h'
id = 'personalinformation-test::3e6bc263-40c1-42e8-8e4d-26b942b317d7'
uuid = '3e6bc263-40c1-42e8-8e4d-26b942b317d7::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbR5aoTdoKs8itdhvPzwd6CVEXmSS66K58c6ZwrJDY75t'
id = 'freckles-test::477b7602-9e49-432a-80cb-7b614a4614cc'
uuid = '477b7602-9e49-432a-80cb-7b614a4614cc::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ztiU4Q/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ztiU4Q/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ztiU4Q/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ztiU4Q/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::3e6bc263-40c1-42e8-8e4d-26b942b317d7'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ztiU4Q/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::477b7602-9e49-432a-80cb-7b614a4614cc'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ztiU4Q/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
