bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/cy6qW3'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSCJbbmc3m3rvxgpqu6jIn88nC5wNhf3n8mK4MYXCnqs97rQ6XwSQMEFfwa3uz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcScJnIw79eXMzysw43i8cgoKh5iP94cwWSCRhhiRz6h99yjxcm8QuWi3pkmsba'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSCJjVOo8p5B7as3fWMmqcmj3YdwzobmA4osnEXIWmye8mdTC8W5O6aVBSy4sr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSCIAR74EauPpukxqhpcRBx6N4zda753hJ4titHoKsr9mnmHjPPwQEhttdy3vz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSCjqoHO78sPcgy5sYxQ58Oo5bs7Gbt6eSEt9zgEf3hevx7smVi7UY9mc3er9z'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcScIFBIuvR9rti6gxiJVBMv7uTi9npv8ej5KgPTqki9vs75h4YuAu4Z3SGox3r'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRkZXAU5eLc97AT1VHyh3AhfAs2AByVhwpV3rxr11zBna'
id = 'kanban-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPhVNhYLSezQ38m2rj61gJpHZu5B51oEAcVHhGhNEaMzy'
id = 'notes-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmdY8guqM7UnX1RReGfpsVLJSiwvXUa68FvuZurdhhSSmW'
id = 'tasks-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmdwWqWuiSe6EFvkX5zhfD3T4nJPZGKhpCZYJW64gc891e'
id = 'fields-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmXnCFMazrGA91ySn873rNsurtQwmKsunhKfmErkLT5MaF'
id = 'personalinformation-test::ba619dd8-4760-46e8-a036-c5809edab7ca'
uuid = 'ba619dd8-4760-46e8-a036-c5809edab7ca::98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmVLY4FKCq2Lx6M8pVUDJpEAoAJ9PrWFXMzf25cD2YRTWt'
id = 'freckles-test::f6edce91-1156-4adc-8517-442c564a2dc4'
uuid = 'f6edce91-1156-4adc-8517-442c564a2dc4::98ca96a2-3e14-4667-901c-7749cbf91902'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/cy6qW3/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/cy6qW3/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/cy6qW3/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/cy6qW3/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::ba619dd8-4760-46e8-a036-c5809edab7ca'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/cy6qW3/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::f6edce91-1156-4adc-8517-442c564a2dc4'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/cy6qW3/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
