bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/ZQV7Ev'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSCISXAMRyv4rwny8hquBhVNx7fv4fyjnP8ZqvG7dKgphv4OxsE6b8EZsh58ba'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSciPA8rF7vnyqkkqwrSqidd5Qqwykyy6ZE7w568IACgwy3ttbWJV4Y9xz8tnr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSciqpbni8Cvvxzn9do6oiAe7BJo3zba8TVOrUWtXyscjxi4sw84zYO5VI6bzz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSCjjKiZwp7twxowxqKOgg8aDBjrfd8adrhD7M7eq7oehtg7uGoOnGBj7mbwiz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSCiPc76SgAYuuc4tQmiXO3xwqwzzp3aPIfoiGiqg6ky95i3IO3Y89YgizA63r'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSCI8KKGXSOs49adoCOjDi5Cspgdm4968dIc5ikHMquaxic9AJUyWPPOmp9yqz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmc3dAbkCZpYiaJhU6rvFeFRX3y94KfgRPajzyJmFR3B8N'
id = 'kanban-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYnYdQpsBKykziRFrw2c4e1SnEZrQkT52f5xnM7YZ84M7'
id = 'notes-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmc35riQquy3LLX26RmMS1w3PCeJSLMoNETuGANhaEh9X8'
id = 'tasks-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmNhQTwe4n7Mwy8ip8erF3zpxMeWFdeo9B8fgGsdtksugp'
id = 'fields-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmbSkPNEXFpZ7os7JFmvf9yQuVcCDTzTUkrEzkeFc6e3u2'
id = 'personalinformation-test::738f8ba5-a096-4458-9384-64b38e7a7071'
uuid = '738f8ba5-a096-4458-9384-64b38e7a7071::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmXE376k38bxBjudZ473CbgZo7qSb7uYRN8H2sPwjRe9eM'
id = 'freckles-test::f00ca8cb-859c-433b-a57f-c16f6ba2cce5'
uuid = 'f00ca8cb-859c-433b-a57f-c16f6ba2cce5::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZQV7Ev/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZQV7Ev/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZQV7Ev/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZQV7Ev/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::738f8ba5-a096-4458-9384-64b38e7a7071'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZQV7Ev/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::f00ca8cb-859c-433b-a57f-c16f6ba2cce5'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZQV7Ev/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
