bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/5MZwhx'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcScI9CJmOEF8h9no6RVB74tUh94dMndr5wap6ezibh4obwbf3KjJaJW49Gti4a'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcScJWsZ9O343eZi4ua5osdCdeMjtwesemztwpB6FNqo97hsO9tMpSOVu8ns5dr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcSCjWvhowS9kd69vjR3iNqQ67eJEfxewnMHD3KroAt6w8dzVWwJGBIUmqthxaa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcScjAB5WxqIsstucotQQAPH956X7Unt3z5a33tiB57dDcutZ5gUHFG55onn3tr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcScJ8KOGTF84Dxke6VEwGK6GGpo4vgyc3Ybkmjhdpcb5x5wDSoGix9PGhquymr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcSCI3vwP83I4W8Fvwp3ibm4dzW5nuyf66rtfZc7vNOe5dznjD5zs5YIFWvco9z'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::89ccc799-816b-4283-bfaf-af070e28e47f'
public_address = 'HcSci5hhZqN9kckg6defa57xZQEDhp6m9b5zbscOWJ363gxeIQRmdVbNayx8pti'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmUZKwT1QApwdHFZ5XQEsxUZ3ntUjVNg89qyx3buPqv3mq'
id = 'origins-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNhagTkPhU9RbPLbWDtgF3F5XGUwn85Eiqfqd6UkQQzHH'
id = 'kanban-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmbBiX895f8YvFTAfYQj2F1TQBDMSQdVotJ7hcdV31joSx'
id = 'notes-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmd1hXdddUDpuA68CGiJuAvj3mRGNbwFfUkTaLZknZX1dk'
id = 'tasks-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmXYEbqL2Z5QLrbudxWhHpZTm1211QPbaB8ShcXfLKXvkg'
id = 'fields-test'
uuid = '89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmX2W98mCyNNmfYNxqH6DaXzYc9ogsudJLmWEPVa2L9cqm'
id = 'personalinformation-test::c72458a1-b7d4-4c4d-a04f-30678ee05bd5'
uuid = 'c72458a1-b7d4-4c4d-a04f-30678ee05bd5::89ccc799-816b-4283-bfaf-af070e28e47f'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmYJkRfam91Lrq2gnsYCEg3uxBRZiMFGgtDoKXc3dvdLXW'
id = 'freckles-test::15964c9f-a39a-4c31-8bf1-0bf15dc3d289'
uuid = '15964c9f-a39a-4c31-8bf1-0bf15dc3d289::89ccc799-816b-4283-bfaf-af070e28e47f'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/5MZwhx/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/5MZwhx/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/5MZwhx/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/5MZwhx/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/5MZwhx/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::c72458a1-b7d4-4c4d-a04f-30678ee05bd5'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/5MZwhx/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::15964c9f-a39a-4c31-8bf1-0bf15dc3d289'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/5MZwhx/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
