bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/3Ea3oC'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScIPtkyZ55Ox44ahdbk4fAzMOsaousmMK49y8grs86roxsbxbgkc5Goemev5i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCIJI7b55sTFepanDK8rAMUs6ui8u7jFics9aMxtm5yjgrma4Vkmb3aszh9zr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCJs7u6E6ciYdwvoY6rEiKC9YZviaht6eqzgp7wJXu4mmtu6E8RV9JKvz3jsi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCixcZfnNvryaaxev3j3ogJV8h3Y4n8wCHZsIM8Gdogf6fbuE45s645r3V8Ar'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScifG46DY7d8IphdVttNKV4FZr35za56DP39HxHVqru8rkbdHyGUPFtew4yni'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCJG87j73Nz9khdkBwHtMmRehvfgmeu5Fg7IBifd7e84k9SzczHurcgmerdci'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmedGmoWrgruqTQo8CCbueViSHtygNqDGUe5UDuNMBw49J'
id = 'kanban-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYj38vX7snVRgUbRiYSnCSTeQ7rfXRTzPZnthyMGPVuy6'
id = 'notes-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmSkMFYYPAvptbPV4oHMR4jDRR1EZVjrHJy7xE4fqz9jtN'
id = 'tasks-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmZV4fqhTA68pJXXSwLqgDDvj9C4QE2in6H6Er8rk6n5cc'
id = 'fields-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'Qmdt6FYZAG6U5kix5SSHb9KCjEVpG2Jg3LWrvWwT1LcBty'
id = 'personalinformation-test::7eb5963a-6ab3-4c7d-9b4a-96a084aede7d'
uuid = '7eb5963a-6ab3-4c7d-9b4a-96a084aede7d::460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmQKynt27wddsW3qw2SpKgXtToZBEFUZwvrUmHoozA5uN5'
id = 'freckles-test::cd82d866-2022-4b03-a303-35754cdab152'
uuid = 'cd82d866-2022-4b03-a303-35754cdab152::460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3Ea3oC/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3Ea3oC/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3Ea3oC/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3Ea3oC/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::7eb5963a-6ab3-4c7d-9b4a-96a084aede7d'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3Ea3oC/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::cd82d866-2022-4b03-a303-35754cdab152'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3Ea3oC/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
