bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/KpSppO'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcScij74UNQr869DrpfhG5VFnsbbgjbzwMXuT48MCtc7si8ko9jT5TIkPYur5uz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCI7x5E8SuNN8m6u7Jf54A4DSH5xRztVHajuHNUfi3f3npPkq987vY9u44bOi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSciknQXYqiyqe3n8GUGy3aINMbr8j4q8gr3C8XoW3hNzw3ZKPOvUsK6akau5r'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCjwc7me9JV9ed96OhEBsdesjufvjj94WuJ5cYNBPhmotz69U9qhcacfq38hz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCJMB59tTk7Pi4pocj5q4GXTjv89smgbx67Mie9bX8v3vd4iFH4gJ66D9Yasr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcScImnVjwporfvq4i4Xj8P6pj5z4Xni6OvvhKN4potrkfm4z3OczWatbda3aei'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmZ2TGpauVUoTTTPwmqNpwmCLcDavKr4utUxdJAmHXZfXE'
id = 'kanban-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmbL8eFNsa9UYtJY2iqRPWVfhHok46fdoYCAskt6gakegE'
id = 'notes-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeqVu6wrMg1KapacXdZDLr5CC4WkjMKYUMXdjubuHeDUE'
id = 'tasks-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmap2ypwmfw4DccYDrJDDZF8iGRbKNsMbcAV69NwRLQ5hG'
id = 'fields-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmcPUUrq1VjyP5pir8J6xhSVKFCEFsYLn8ttEraWZtCHJo'
id = 'personalinformation-test::d0090308-8541-46f5-a31b-0f8060b0832b'
uuid = 'd0090308-8541-46f5-a31b-0f8060b0832b::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmSNFSC8iDvsCT8FUiFUFY97EZcTLaAnHmX6UsysFtzbdU'
id = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
uuid = '59280fe2-f7cb-43ec-9f20-e4d7cd883a8b::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/KpSppO/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/KpSppO/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/KpSppO/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/KpSppO/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::d0090308-8541-46f5-a31b-0f8060b0832b'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/KpSppO/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/KpSppO/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
