bridges = []
persistence_dir = '/tmp/tmp.udyD72ci2B/tryorama/serap6'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'arthur::projects::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScJwtSNfHftbobkusrzQp8NgE37wdmt7MofgdsgBym3mmzgdcQt3eSsq4idsa'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'arthur::57c01ed8-30ae-4fca-b6f9-40192821fed2::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCJ9CV7Gq6tB9vqgW9s4XqxX8i94D9cGnc6YdGgKejgqg7DY33Z4wtTkp43cz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSci6MTUqaNhtss8v7KrRERHUcsi57c34szim89gWTupueoBE8AKcyYweqvvcr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCjgbRf7y5Cvdvtyi37KcUM5QCJt6uiVpqi8PqE39re9mrBT8oeAvrbn5b3ka'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScI58V8eg8tppa6hQsT6UhhdQbw8on7RsiyImY4gu4pjr9HdWaM4Awsvnhyba'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScIPv9MM6PM7fbvffpr9uG9M8gR4trqcBy7gVFT7Xzc6g33TRsdYKQPhio7rz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScJjUKpGCf9ycrhq67sXe7He3jmjopy4JEpehJBa7chwtwjDedifP7Irqyh8r'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'arthur::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCjiih3Cgzopvbs86NevGZ5Ysbo9pzsxE8Ayoy7kXdc59v6d9z3da98uhZZaa'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmY9iCT9rspB34nVGD2RocQodDwbGefbZMye6DXJn3Lyy2'
id = 'projects-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qme2fURTTGenmv4Q37AcjRPszaptc8WxZLBViCi7rHqg9G'
id = 'origins-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTvKjN6pQiYqgY11JtQnxMQbAp1TfK8TKUyDn9uLus8G6'
id = 'kanban-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmXdA1jW3sxFMM9YiPMANSCpwoqK5bRKaRj9E9DWVLxsBy'
id = 'notes-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmaHRhRZozYmmjkJiavN4HANP1yfbE7r3Wp1AAaKumFYoH'
id = 'tasks-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmZnfNNAtPEx9dSkwtzTqE86u7GzQ3KUvzJHk8is4ggcAK'
id = 'fields-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmPToHSDx4v9L2vPCtRCLM72jriCycJgpwKQXRhYEwHpZx'
id = 'personalinformation-test::37687398-36ce-478a-866a-743a7c701845'
uuid = '37687398-36ce-478a-866a-743a7c701845::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qmddhy4DaGnyrp1ZTn62duJbMh8G5TnX15kJWFxQPuKENy'
id = 'freckles-test::fd4840e6-f120-482a-beea-334d911eae38'
uuid = 'fd4840e6-f120-482a-beea-334d911eae38::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/serap6/projects'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/serap6/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/serap6/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/serap6/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/serap6/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/serap6/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::37687398-36ce-478a-866a-743a7c701845'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/serap6/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::fd4840e6-f120-482a-beea-334d911eae38'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/serap6/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
