bridges = []
persistence_dir = '/tmp/tmp.4OYPJetHpj/tryorama/ah6kZg'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'lucy::columns::00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'
public_address = 'HcSCiHpBxBTi5ywrv7y94zw35zOpO493nAQ8SHrBrri3chjeUeqHESZ8dumghur'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'
public_address = 'HcSCI8qVaUy54ceamd8OoVCB4dNYdenmbGY8KOUqpVhbuwqz7eP96HNPo9xdcrr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'
public_address = 'HcSciBTy8dgbqjheym64TMNrbZqIgj986rUGrbKo7vrwhirx8RtDP684WkTNx5z'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmZYjp2AhrBnVHxhKdG5aQ4nvM6fiU12pUQr4m4bfVkK14'
id = 'columns-test'
uuid = '00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'Qmc8ocDJrw32uGY99fYzkjifkSu2154oPoySLLxP7EtniJ'
id = 'notes-test'
uuid = '00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmQHPDYeQ38gqbKQvciBp7xw8fdZx6B41F2BzU7irCPWvo'
id = 'tasks-test'
uuid = '00f4adb2-0a2d-44e3-b0f0-b4d94de9b690'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/ah6kZg/columns'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/ah6kZg/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.4OYPJetHpj/tryorama/ah6kZg/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
