bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/ZUo60k'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCis8GebPcea9cii6s6qv5TucA9Tvm9Sd6ohhH5CIytf54Q3UTu6B6YXZf79i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCiPjnZ9ex5k8gcfAhvMiwKStokdxzk7Tt5aG86DEfwvdn8mtMk8t5V448RRi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScjByhFP34gpmdmuSNDYq5d7Or5ykgzkFgHpZSuxarb3upvKNiw47fSpmbsbi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCIXx4RvJObk5sw9XBNDm7h46afhk7kx8xQYYOkb5fb6jaAIae8EIv7g86pwz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCIkKZEJ3ujjsh6y65pyMask668cKxa4536khG8XicJnpjwcnn38hhtzknkei'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTvEQoxuEYwvZgt4QRv82SPBEMAbv4pGa5KF6TJUdArZV'
id = 'kanban-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmfENeArJWfouiueEiFJNktR79wd7iEwxmBRps8ikVZ8xs'
id = 'notes-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qme7HaKn5K2zZARtCLWdgvkxzCGLpETeue7iPStGV6eGMa'
id = 'tasks-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmeXdovo2y5QMKi3eGE13tcLuuDB2vjDcCxtL9dBB8y5B5'
id = 'fields-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmQoKCM5DZB6sZ3JLBhoohW6tupZKruv8YqjKMy5BGgjz1'
id = 'personalinformation-test::56ee7534-d1bc-4866-a588-96558a726e1a'
uuid = '56ee7534-d1bc-4866-a588-96558a726e1a::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZUo60k/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZUo60k/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZUo60k/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZUo60k/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::56ee7534-d1bc-4866-a588-96558a726e1a'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/ZUo60k/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
