bridges = []
persistence_dir = '/tmp/tmp.udyD72ci2B/tryorama/koCk1o'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'arthur::projects::31473f8e-8e91-4b67-879f-e2fd29e1cca6'
public_address = 'HcSCJ9SV49cgZA5xsnEj7h8dm6QUZh8ryS9rfzC7bd58roc7oPy3ka4T3PO9nmi'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'arthur::57c01ed8-30ae-4fca-b6f9-40192821fed2::31473f8e-8e91-4b67-879f-e2fd29e1cca6'
public_address = 'HcScjmToy5hRge49b3pV8QMBm4ohnjbmf7jQ5Wo97e5IkSwyxhOuBhgq5nvyhui'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::31473f8e-8e91-4b67-879f-e2fd29e1cca6'
public_address = 'HcScJN975HJvJBwgps3arQBnt56IFgameWqdgKrYN9anoz4ecSMeexjv63riapr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::31473f8e-8e91-4b67-879f-e2fd29e1cca6'
public_address = 'HcScjY9n99bqhKyfuoV6CukwUOI89amc6nnP4cpeDH7sdvrgDWNhXR9YYuej74i'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::31473f8e-8e91-4b67-879f-e2fd29e1cca6'
public_address = 'HcScJ37s7Xk7xGBf5sEVA7Xt86sRm6abuDHBJzduuzb5mqoc4EIEH7mHAEhokez'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::31473f8e-8e91-4b67-879f-e2fd29e1cca6'
public_address = 'HcSciYZqXnS5xy7xvss3o4tPaCVyozznsoaRDICvVwd5mxen6OccwUoq7Eqz84r'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::31473f8e-8e91-4b67-879f-e2fd29e1cca6'
public_address = 'HcScicf4fcdSfcruc89ZVXRXIg4itg8eb8RqzZCH7Ek5me8aTqFgPhb6mf6h7qz'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'arthur::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::31473f8e-8e91-4b67-879f-e2fd29e1cca6'
public_address = 'HcSCIonJOc6wu3qn9oR7WhSkhdD6prmpz3FPZs6mUIEkcwpkTrJfUjA8Jvan44r'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmP5ufH1uMXvbKc1B6G59xQ8Jv97tpNT9dCQks15R9vjt9'
id = 'projects-test'
uuid = '31473f8e-8e91-4b67-879f-e2fd29e1cca6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmYhAPbsEG4qNsys86BvrNbLzXbvBbt5qPk5ibYr7WzYpW'
id = 'origins-test'
uuid = '31473f8e-8e91-4b67-879f-e2fd29e1cca6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmS8nifrLF34BDLyAynni6ZxUkiKH5XTwQQzQWUmw1A4uQ'
id = 'kanban-test'
uuid = '31473f8e-8e91-4b67-879f-e2fd29e1cca6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmUPm2jUimbauFXFdMFvYHdJSdRt5z6dvsQcnUtwRjDYFE'
id = 'notes-test'
uuid = '31473f8e-8e91-4b67-879f-e2fd29e1cca6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmdG9QTwgHmXF99Mx2u4h23qnGm29qULZUxRoRHfvFYt1Q'
id = 'tasks-test'
uuid = '31473f8e-8e91-4b67-879f-e2fd29e1cca6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmQ1PcpQFQvmpi8s9aG3BPDdEUBdzfohxSU5ahwM3RtZ1b'
id = 'fields-test'
uuid = '31473f8e-8e91-4b67-879f-e2fd29e1cca6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmTfL9Fmm9yVUMQYFvhcVBJCuFfFEhPebPLpB2Umij2R4d'
id = 'personalinformation-test::be89d290-ff1b-4d26-a316-ff13899376ce'
uuid = 'be89d290-ff1b-4d26-a316-ff13899376ce::31473f8e-8e91-4b67-879f-e2fd29e1cca6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmXnaCxkXnzBC1fdvTiizQo4zpUCXQyLnTv2H1NY6Ny1zg'
id = 'freckles-test::982e222f-5dd9-4c55-8ba0-c4d1b6cd7bea'
uuid = '982e222f-5dd9-4c55-8ba0-c4d1b6cd7bea::31473f8e-8e91-4b67-879f-e2fd29e1cca6'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/koCk1o/projects'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/koCk1o/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/koCk1o/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/koCk1o/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/koCk1o/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/koCk1o/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::be89d290-ff1b-4d26-a316-ff13899376ce'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/koCk1o/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::982e222f-5dd9-4c55-8ba0-c4d1b6cd7bea'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/koCk1o/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
