bridges = []
persistence_dir = '/tmp/tmp.2oszwWo19C/tryorama/2cNmmr'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'arthur::projects::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCIG3qKcTRxrj7mfE3W9e6f7s93EVVgHMU8U6rG8r4Ayt8pABukd7MKgsquca'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCJfkSs56q88vkmcF4YHP9qVvEv4wtyW6ZKAcBmnrvjhdqZcrZ5ywcknakdor'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCIqYQg9Uri6mt9aTWQCc7xrNgx9xzzgnmQW9cVu5m9pyaacuDZVg9D8xe9ei'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScIdfYwAKgzdpc863ownOCvS8Ti4cpykS6bq6eVjkoofn9y5teQAova74c9rz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCizHZDJ6vg3asw6TYxBhKiQp973y8ijarZEbT64mtuqv54Kw6pX79DRc9sda'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCJE6Ht6Gf4QjfcuM4Up87NbTOejmidPcHzostJqxryb4hxfBsdacedn3pqha'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCje6Xy3vnMakzxvq73pqwOATObuyh37kH99rZuMbF4kwnK3wkKZC94S5hbza'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCI4S5ojZF6hj9dgrMxYFK5sDbnujdsH7CagYjPpyh6m5p6fkqyOjyci53azz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmZy6baFVXRqJwEbTa2PzEQTAwSXLcFh8wjZLtUkYRBb9Q'
id = 'projects-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmUnZVzRcXX2nBYgfpTJDVQVTYHnX3R7bwJ1WRdUn4JmPF'
id = 'origins-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTxSTHTjwMwEW6sUizD8euRk2RV6kLqkXCT4NBXxMkgzq'
id = 'kanban-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQDHS5v5V1cCtik1RiZzBiZLdAmrFqCffe74oHWh2DqSW'
id = 'notes-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmdHzqRj1X2woEa5wxKVx4VHx8HfEK7jKyoXdhZFPLvFpN'
id = 'tasks-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmRzbVi6sBZ15yAS3ri7WXakpJ9XtbTMpkdbYhGS3qLcVU'
id = 'fields-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmTny3GZWFu32DNYNiY69BKywBvwcJon5WY4LofpbPsYpN'
id = 'personalinformation-test::6fab93ae-3f96-4421-8741-019de6da050a'
uuid = '6fab93ae-3f96-4421-8741-019de6da050a::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmeYjU1hubDJth1NWHCmgPEddPzhnFQDkjoY99ttg9oV67'
id = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
uuid = '93309f35-de11-4f62-8af4-af46a19ab638::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/2cNmmr/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/2cNmmr/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/2cNmmr/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/2cNmmr/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/2cNmmr/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/2cNmmr/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::6fab93ae-3f96-4421-8741-019de6da050a'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/2cNmmr/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/2cNmmr/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
