bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/iKulAY'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCJ3cYcP6M8gehhaHBXkN987B9rNnf784TifwSsDSmcmfxqrOzG564ENsyppz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcScjZJ5UFj73Fhqj96Kex3QVY4vnyh4vxoy7JoA8eMjdcukaKkgnwDrddrenki'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCj4wOHaWRzujaie4458YB4rNbE5HRiAyMRfwV9Bn8ac6beRyuM8kr5usccoi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCi5pF4B3FCUnrixvjWtm4viucmov9v7PfwRYun4Q6r3faans6oFjQb4izosr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSCi8IO7p4SQCcc8cPUvs6Q7wf4Q5eqsHSF8EU83655U7SSrm6KPa8qqBsk5rr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcScJUoSYmyxvvkisvae9MvZ8w7yA6z9bwUzZH9U7Oe4d46w6p3VfxypXG8y8sr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::a18e62c6-4277-412e-a730-b8a327cb4367'
public_address = 'HcSci4AO4gbZKpgxpnMYd55a8BSZwz3wnt88A9fE5uanuc6bjM4D75uGy8gC93z'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmYMAuBtwh5tvEWoe3CyMygGZvGM9qN5Q5yUx29xv4FhRC'
id = 'origins-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTEe5g9Na1cuMG5MefVBFAgWJ7E3t8ThM6GxXaR1jmbtA'
id = 'kanban-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdfNoBr3Ct9SSKcuEjbgqZVwDMyNXRy3BUGFBYcNd94kb'
id = 'notes-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmVKCr5xhBrmdikE7aeBVCwC9ds38gbjRoSrDn2Aao96tD'
id = 'tasks-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmcGm2V8nrSdhT8iQusSg7w5hpPxeH2jR534ptP1FiTwsC'
id = 'fields-test'
uuid = 'a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmY42myxuyDxWiKYn8Sdd8yX8xw1Gpd3eWip1a7Hn7s56M'
id = 'personalinformation-test::db0c00bb-628e-4513-b909-0cf0d42d6b93'
uuid = 'db0c00bb-628e-4513-b909-0cf0d42d6b93::a18e62c6-4277-412e-a730-b8a327cb4367'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmcufKtfPJjH25ncN4wb2g7qWRNMpBkH9JU5mrRcrbAwQ5'
id = 'freckles-test::c3114f14-45dc-4f92-b539-0c7ce6c40e63'
uuid = 'c3114f14-45dc-4f92-b539-0c7ce6c40e63::a18e62c6-4277-412e-a730-b8a327cb4367'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/iKulAY/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/iKulAY/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/iKulAY/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/iKulAY/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/iKulAY/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::db0c00bb-628e-4513-b909-0cf0d42d6b93'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/iKulAY/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::c3114f14-45dc-4f92-b539-0c7ce6c40e63'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/iKulAY/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
