bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/iAopiq'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'arthur::projects::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSci7mNaa6qBg4pmvCOYGGEUHtvbgng3hkoNjg7PDumevznFKa5SRuJ49Sgz7z'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCjm377ouGMqs3a8IJD45YcKJ9u5wqvBtAJve4d3enuii684TB9pAj3E6dJxr'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCJMeIy8C5GfdqbyEErqiBx9Dwzf7ogzPXYSXv6g4ksk7kGEtTqDK9U3y6acr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScI4S4ABFDVa4dts74yP7mUakWjf54mzVT868CdnguxaxsN7YnCbcW4Mnj7fa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCIqae6UAi5a5praKE37jm5YiMeri3tkvu3386vXjKffiyGv7I64bVsn74Yyz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCIp3Tz55Xv55ImrhOh8MUGrp7753n3fKuecHSkpcby4dsJ45p5H46ppctcbr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScI6e9b9FWt9g6cu7NnqmXZES8jcfvv3ar9vm5uH76cjwbQSQeGo588783o7Z'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCIww6FsPO5jj6g3kei49ibBQNcubcgarARgV4mpbrp43rv9OxQhCJ9Dbokea'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmTWPHy3wW8ykVXTzmFQCiXqZFf74wjdSSppH2ZCgdoeWB'
id = 'projects-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmPBaGbmisGCYgPqV82xZUX3ozuEmJqmtbhDCRZkjzF1t2'
id = 'origins-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmPHWJrJV9M8KhEkRQZhwqtC9cjKc6VUQG6axBVFwxcWWx'
id = 'kanban-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmP1hHTmSf77Q41E5Z8tvoyEefgLHBCWQ3wTBDucDAsMGf'
id = 'notes-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeJz3YttC3m6QKpxkR2saYnLPpsoUUyB8Cf6nvftnGMnU'
id = 'tasks-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmP3JEF2b3JnZ3iqY96pq3hDyKMr2HLShLT2qojFCMbNHo'
id = 'fields-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmbdXEv1ytuqx5cnZf99vkLBHWbGTbez3YFstN5ehzuVZc'
id = 'personalinformation-test::f79dff71-5241-4129-9b37-149f075ef22c'
uuid = 'f79dff71-5241-4129-9b37-149f075ef22c::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmV4kNmjK3i5yWb8HbAXpnCsdhLaAs5LjfGZBZadRRnT46'
id = 'freckles-test::a794d207-53c0-434f-b1a1-16c730db9017'
uuid = 'a794d207-53c0-434f-b1a1-16c730db9017::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/iAopiq/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/iAopiq/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/iAopiq/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/iAopiq/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/iAopiq/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/iAopiq/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::f79dff71-5241-4129-9b37-149f075ef22c'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/iAopiq/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::a794d207-53c0-434f-b1a1-16c730db9017'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/iAopiq/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
