bridges = []
persistence_dir = '/tmp/tmp.9VlgWQxqgQ/tryorama/mvPhV5'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'lucy::kanban::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcSCiDNNYtPqhjc4vtS5U4DZz4YU3be5jZnPergddw3xdz47wxf8CDPhJrdk6vi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcScj6moHJBWkqhwgmQY33SwT4Snpvvj9wPpChQNbmh7xtcsF3Mv6MNcePtbqri'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcSCin6BBHcfg5gavv4FyTX4CUSjaaavfKgD9urpiHzd79uougj4tYZNdr7gcwz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcSCJiYXo5q6jrz4oe6Qs5HVsHOdjwagf9RVEJI33n94svyfviQKyuJV5zxxh9a'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'
public_address = 'HcScJYsJb4we7d4y7qHsh9tP6Gz66sseu5gUMuAhamuvrowbfy7zq6H9gQ9Zwor'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmU4wjuHQmGr42z12U6zvMPYPWHjgced8XzH5SHw9CbuKG'
id = 'kanban-test'
uuid = '45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmTEAtWeMCoTmuFYov7Gm1ggKymWTTN3pFQ5ZEDhBqUoW9'
id = 'notes-test'
uuid = '45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmbZ9zH4BHHpadLDds5KN9XoNczGAuoTGUqiruQV7JSFYo'
id = 'tasks-test'
uuid = '45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmfTaEkSAv6RJm6piuxswbNrnN6CHcNGjajWhi47w5fmrR'
id = 'fields-test'
uuid = '45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmTtkz9UDz1kAQXyEiwatM5L87DCgW62BY1maNfejUo6tP'
id = 'personalinformation-test::6f778754-d932-483e-ba54-43c7fffd80e4'
uuid = '6f778754-d932-483e-ba54-43c7fffd80e4::45e1a1bd-a7ac-4bb8-9bb4-751d922b62b2'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/mvPhV5/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/mvPhV5/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/mvPhV5/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/mvPhV5/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::6f778754-d932-483e-ba54-43c7fffd80e4'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.9VlgWQxqgQ/tryorama/mvPhV5/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
