bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/NIyLeJ'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScJazMRYhxjbuw4ui69h3p5d4KBg6mi7mxznIjWcavec9gMbIDQUfFrxnfwfa'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCi4oqKMMTwdn9qg5ztb4sfnTbwvv4eEp4Pk5GAFOrgbrut9CeyHcoimz6e9z'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScJQ9PsDvd86ihu8bBw7bvTWF6nwodwfxF6rXWMPrzf6q4HUdMZ5Q66GS9saa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCia4M8hbvVou7uqa6HCBD4e6sV9o5y59pJR8TIr3gpjiryC7deIDPz583ozi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCjMWSNKObsxn4iju5pa83uppmsxavh9a4HJDouKW5miuvQ4i4N4h7JOiWhoi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCJ6Q9SD8UBBbtniyo7u3hShHDk9vf4zMt6YG7ifdyxzuxHWIN638fg67hrii'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCJEKWNSIfy4gmegAFe4h4JGpF3yzv6HUTmh5sCIveet333aoeceMhuzf78fr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmRxkGsNZP2Q1yXhwiRfxTotEicNzDRDn5TNL7bGUu5mvy'
id = 'origins-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmQvpxoiR4zLcbZgJXPGGm7jWnnLPN5nZRiV7mTsT3Eyqb'
id = 'kanban-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmVBYv9DcLc6fju9AXUKbpp5guuU3Bae14j7KpC6GbrsEM'
id = 'notes-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmU3pxPmfoaRdcmsDjcZigBDq2xKLVmYq8234Fp1tYfSxq'
id = 'tasks-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmPMyZn4P9iB7KcCLt4u5NkAJ9muQJc2qFaLxAScSjwp6c'
id = 'fields-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmZPNMT1HJ2YEDfmXXCbTyYcBCTyTqAwsM454eNAPgzqHa'
id = 'personalinformation-test::a6c501c1-590f-450b-a032-2d594243dff3'
uuid = 'a6c501c1-590f-450b-a032-2d594243dff3::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmPpencuh7jGURJFSTNAZMM6UTcZSLhgrCg96E8hWb66of'
id = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
uuid = 'a66e1d3a-6ad0-43d7-9619-e3b4a622690b::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/NIyLeJ/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/NIyLeJ/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/NIyLeJ/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/NIyLeJ/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/NIyLeJ/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::a6c501c1-590f-450b-a032-2d594243dff3'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/NIyLeJ/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/NIyLeJ/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
