bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/8bMYBM'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'arthur::projects::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScjgCZ4hxXa4u4wcW445s6K7hWn5w6y4pFD9DRH3pdziqq7k5cq7Hhj5Zgd4z'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScjU9Q5VvnYax7bm8QQC94K4Ti4W3BtoVGyRVy7xiphbjqIRf6DC5UpNcwf4a'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScie6vfJW5J9ckzv6hS6oMKn75KX3uaSOP774OrZG4QtzgG3J7YUHmqJkcsca'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScJJVJ4oPJswsecqktDdI7qbKpphuoxk7N5CVy6pTpwagtGu7zXkQAjjzhrxz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScjcH87ze64xXandrY6VXkQS9Pjdjh8ETbFuSMRrb3q89tSAgMp44WSujrfzi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScJET6SXdj39u9ouMyGk75EK79edgauzfU4EJD5UE5turxeQOaeesuez57wwz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScI4Vhnd898Howmf4Azmhpd8knmgb46aX5NIkZ4mdchb3pW6uS3QvPwgn33hr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCJ4OMfzfIsg98j8eOR7spXpu5hq7wrnxQcIzrtjeg7kqi8IDCxAQ3vAjoq4z'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmbJrmZy27juv2HYjoLWt8CdRJqQkTk38pxcSurDyWzYDW'
id = 'projects-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmQutjyu1gmtmBmAysKi97J7zWFGZ5vd4qswrqNt2RU7xq'
id = 'origins-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNnYtKAEggRsuFufbRZyPmKYgRVtTHNVWHmGMmsYPu7C6'
id = 'kanban-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmaNcK79mga5ttAcHDfZT4KphgXsdYLZeFhM2Vw5UL5euF'
id = 'notes-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWkkYJaZxunVzn66Sba67XRqsvCrBKuYm7744TJwyrK49'
id = 'tasks-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbA5oA41mbtKNCSUaAyhvc8NUjzidT2LDop1TqZETawmu'
id = 'fields-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmSedEMaKYLTmbrxKCPu91u46zx5XNvcNGvLimhWrtxXk9'
id = 'personalinformation-test::9dcb1041-7c07-496d-825d-fd522a166e27'
uuid = '9dcb1041-7c07-496d-825d-fd522a166e27::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbrwEAXQjS1b7fqhLFkmxusDXYirSmATwMW9nE9egS2t4'
id = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
uuid = '747c6bb9-c2d1-4b5d-9927-b3ffd4174748::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/8bMYBM/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/8bMYBM/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/8bMYBM/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/8bMYBM/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/8bMYBM/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/8bMYBM/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::9dcb1041-7c07-496d-825d-fd522a166e27'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/8bMYBM/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/8bMYBM/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
