bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/vokFbV'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScjB8kV77m3PF7qjc4nnbfMw9kffxtvegtedi4eN4gix7uVGcHj9D3hI39mni'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCJ7MSe4BXo677qyU8VkgBorifbiq76QY6OStsdwyvaxqerD9yIS3U4Ed3jhz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCJ6cPd5F65cZfrq4fhwq8Vry7Pvr9s9XkhxW4J4bSkq4qtHIfnNesz8dy5aa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSci3DU9Wc9s7C4efo64RVn99v49vZTniKkHXM7uCesyq55736jaSFNJt3R6zr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScId3QzOBDr3ty5cXUAkWPhxnge59x9oUYSI5jHAta76tsn5u6RkuMPS79wnr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCINcY5ychqgum5tKWXgQQxPz3kbmtp3Qe85MfQEkDydh7wMWQ8ZeGYnb9t9z'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCJNq6YJAHfvyoexjAkkHa9EWnynu7rPG7OsqCtUixfwmoUViS5SXYmdwu7ji'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmXY5ei2q8tCvRBGb2diHjTj7jQ7pFnwiMf4ERvBSyyLBc'
id = 'origins-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRv9ga5obxctQqz6DPxVkJbyo4ZjadiwD49Hcx6ML7833'
id = 'kanban-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmTujJA3qJUgy2XhvjvVxWSYbegUV8n1GDuRmsSePfL5YK'
id = 'notes-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmf5CUzvxThU6C22RsBKRBZTf8spmynjavtWe2d9dgqXjr'
id = 'tasks-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmdzu7EiT4eM89tDytzJ1SsJLPPMdJ23z9aCeYnwniUumW'
id = 'fields-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmawPNb6cNq4WQeT8qnqCzncnsyWr93qCf4WqPbEtFsrEo'
id = 'personalinformation-test::62f2825f-2e7c-4e26-81b6-d432cc4252eb'
uuid = '62f2825f-2e7c-4e26-81b6-d432cc4252eb::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qme4LkdURYs1nEpK4VhrmvyPbPpPDw6ZCkVHYMFgMa9VBT'
id = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
uuid = '84b0e8f9-cc77-43b4-94ad-a41582d7b704::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/vokFbV/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/vokFbV/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/vokFbV/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/vokFbV/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/vokFbV/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::62f2825f-2e7c-4e26-81b6-d432cc4252eb'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/vokFbV/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/vokFbV/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
