bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/f6dQQf'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcScjfoOuhZz5ggqhd6756vnfw9oQR97ZCb5rWMG9SftercraY9o4Gn8Y9Nnuwr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcSCiFhU9ZZypbwm3n776mu7b6ze6N6sqpH3k9sDBAirhnzsS9Fr6n7NS88mymi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcScjcZKTNIa4yegbo9t3adc44a4sGumx4jPKp5eFZbnmdcccrOIgKO87ww9u6a'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcSCjTdvj7AC7jinuek4vHyfPdApjfrwp3v8XF56ZpZ6X3qzwiOOr34GKHkw7vi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcScI7SXFOSzfcs7sthR79Eeeg4TMsrxnJAMzmwkuc6aqn34uX9n9N9g48QTqza'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmem7H1NSpNJUoLiNdbwUgFFpc8aLyZWiay1Qfd8s2NRrK'
id = 'kanban-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPjz9jKtrrN5DLdUEvV8LdZUm9MZKcMJTZM6omS2Vqh6B'
id = 'notes-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmTabiqZ457XGHP7Z4v3vnce5JzLaVGc6fsrzFrY4A2Yq9'
id = 'tasks-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmQLMMUFJmtAEYzFe8rJ4ZUU5r5944ewJJZc7bmsG9mBAf'
id = 'fields-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmUHGPsRUdoZKnoSHWgLgxTUnYqfpQZQjaYka6HJobkM6u'
id = 'personalinformation-test::fb9eebed-1670-411d-851d-cc4a3301fb41'
uuid = 'fb9eebed-1670-411d-851d-cc4a3301fb41::a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/f6dQQf/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/f6dQQf/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/f6dQQf/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/f6dQQf/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::fb9eebed-1670-411d-851d-cc4a3301fb41'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/f6dQQf/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
