bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/yzO7Ja'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'arthur::projects::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCIGC7OhKn65zrxspEXYfHdervkjerq5VIg9cHmNYn6xtbRb3oMM3R6PNqmpr'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'arthur::origins::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScj3UuNfYwh647h8baBI3YBxF4b4bzuysa5oobKpkd9t76M5nZ4IW89G6cTbr'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'arthur::kanban::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCjCq334Vsgtivjfm6RAUedtBqgfqj8jyrWoqmdztijmo4PbvK6XtRk8qupca'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'arthur::notes::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSciA7wpRm97t3wzi5Mh9aNFPfIhcknizn9TiHYrZggf9b5wB9JzJc4bDzhjhr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'arthur::tasks::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScjvFcdrOct4kircz5cOTX7pPiv7qv67bfpKPqgKmqjetreDVdCzw3owzgr4z'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCInivmsCjb7zz35hk4vy4JS4EQjxia3oM86iuQkqbxgmaE363vF4eRHhMxga'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScJtC77ENUrw6reaKbCS9uE4dBbp3hs5svvd47vKPyh89347EhTPPgAVjxiii'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'arthur::freckles::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCiWvbJ4ZF6btfwdV6Oah7syY9e7mpfHzj5NhXRBqpnfcvvGmfybqszowuedz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'Qmb2RPsPGcdCwkNtHmdHTieSC7dP5URhfkZFGfsQp8gAFq'
id = 'projects-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qma1JTKpyG4URmDcgPANiRVBr8TneiTXhipMMFE5kPNnU2'
id = 'origins-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNW3pea1AdCue3cNx2cmgD7F2Cpajbu45t3jmXMqfVpL6'
id = 'kanban-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmV8fqNo5sD6Uz86JnFbvQJE6BXcTnhozwm5WF4FoenDL6'
id = 'notes-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmNp9Bw3XNDAHHcBXJn2w8XfdH1QxZ7QXStRK9KUYpzdQa'
id = 'tasks-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbcZ4twcVVNPDwg25HwfzkFaN4w6xWzTctbjf3gn45krL'
id = 'fields-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmXcWAnJsNCayN1UPAYqBDdd6gycSqX8SDTR6g8ZQtFTqN'
id = 'personalinformation-test::74967623-f486-4a1e-a295-8de38af79e72'
uuid = '74967623-f486-4a1e-a295-8de38af79e72::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmWLNDe1gYhjEcNzKmFKPYfsYPbHa2h7YZCyMMrgxPW5uy'
id = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
uuid = 'cda1197e-03cf-4b98-8fd6-8a713f367342::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/yzO7Ja/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/yzO7Ja/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/yzO7Ja/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/yzO7Ja/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/yzO7Ja/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/yzO7Ja/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::74967623-f486-4a1e-a295-8de38af79e72'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/yzO7Ja/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/yzO7Ja/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
