bridges = []
persistence_dir = '/tmp/tmp.udyD72ci2B/tryorama/e64OHr'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'alice::57c01ed8-30ae-4fca-b6f9-40192821fed2::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCJSZBQSGtuf39o4B78B6qGScssnmckjRfTPGd8S3s8m77rpZGopsMwpxtgsr'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCjpI6ishuyadxko6z5aFNQVQS6qgqeYdT9r9O83NwxbvfBKgzqPcTinjkcmz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCjNvvUto68b6te5GJ5vZww7mok6pjzqqW75Xn4Jc6y3yjQ8A5mFJN5ICr3vz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCi5Ntr7dS5zzbncwrrQZ5qRihoenkruo636iy3R9Q9vqtk9oH6JiX853PBxr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCJ8Zaic67sR33ydaX7JJUBtgizqr9yuai6reSo8rmnqr4n8d89xIubAMymwz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcScIM5b4NSuezzt8jx9QY8uNuWzvswpthmzvBgtWosfw9fzertO739H7Nt6I9z'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'alice::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'
public_address = 'HcSCj9b55CZ9NPboz9ZXqJC7W6Ij7b55ch7998HDC3TYOSef54F6d4rkw4Ba5ha'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qme2fURTTGenmv4Q37AcjRPszaptc8WxZLBViCi7rHqg9G'
id = 'origins-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTvKjN6pQiYqgY11JtQnxMQbAp1TfK8TKUyDn9uLus8G6'
id = 'kanban-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmXdA1jW3sxFMM9YiPMANSCpwoqK5bRKaRj9E9DWVLxsBy'
id = 'notes-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmaHRhRZozYmmjkJiavN4HANP1yfbE7r3Wp1AAaKumFYoH'
id = 'tasks-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmZnfNNAtPEx9dSkwtzTqE86u7GzQ3KUvzJHk8is4ggcAK'
id = 'fields-test'
uuid = '9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmXT3RQkUT5EHfwkKLZV3U7z8YxorRSDYvenePtNt77bBt'
id = 'personalinformation-test::862f2b24-2840-4420-930f-4df1a55611a2'
uuid = '862f2b24-2840-4420-930f-4df1a55611a2::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qmddhy4DaGnyrp1ZTn62duJbMh8G5TnX15kJWFxQPuKENy'
id = 'freckles-test::fd4840e6-f120-482a-beea-334d911eae38'
uuid = 'fd4840e6-f120-482a-beea-334d911eae38::9e38ad2b-d8d2-4b24-be47-eb1cf75f3bcb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/e64OHr/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/e64OHr/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/e64OHr/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/e64OHr/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/e64OHr/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::862f2b24-2840-4420-930f-4df1a55611a2'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/e64OHr/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::fd4840e6-f120-482a-beea-334d911eae38'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/e64OHr/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
