bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/UIc2v6'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'alice::origins::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSCI3Fgw4z3Mb96fgt8DSJKWUxxk5enwDMP8t755tHaib7e9SJENbhT4Shg9ai'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSCjSqIVpFzsng9tjucc4Ud8wPQcpb93raB7Oi35yc77qxt8IdYRsGPSnxurfi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSCIWHtJ4dUmbix8pbv95j77k3u64r9ba8VqP5X4c6xAcyzFP5X8gFMwV3d7fz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScIREeNUy544gmxm4rdBF5OX3pDvmc5dZZJ6z3kvmdf93cp6yG3X99ycF6Sma'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScIH8onaSkzgiwyi8f7reQb4tPh833k4smsn9NUP3wxtz78v6Jb35JV5ODmia'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSCikxOAK89Vbbivi8ffpN4NZ4aWxpieKi4fdO6G3u4pnguY4Pf45fjs4kGkbz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScJ49ktgqJN6uqqrbxMQ9iIrbxhtfrxfI4IHvR4Zb35tz6Xj7hXvvrusmv3jr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmWhapg9MKVmqX8oHFvLizv6gCL7Gzjep8fFgqdv4waiZX'
id = 'origins-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmaEK8Gr61M18zkMpYCW1GBge43SJi312yPPm3zNixVaB3'
id = 'kanban-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmXMyGVJrUGD2uveJEjzrQk4FQy5jPYwUTHhPJ8tSsZjcv'
id = 'notes-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXKaDmdKERMJfrreQNq6BSVtEwedfiyeMrjBhcx8FYdrK'
id = 'tasks-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmPVJJiiakMRi9hfz7YXJcuUjH8eDDwgjtoGYt1j4n1csA'
id = 'fields-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmWdyiQB8sbfBsQi4j5ezsbkXJsXnCoLJCffQuEVPhbKMz'
id = 'personalinformation-test::465ca01e-21b0-4f91-8e6e-777ad32c7572'
uuid = '465ca01e-21b0-4f91-8e6e-777ad32c7572::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbHXCgGeVAVNRTNVGTEJevtYx7zmtnw3Ra6g6KKvf9Vt2'
id = 'freckles-test::633afb47-8f96-4d88-97c3-6b05ef95752f'
uuid = '633afb47-8f96-4d88-97c3-6b05ef95752f::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/UIc2v6/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/UIc2v6/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/UIc2v6/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/UIc2v6/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/UIc2v6/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::465ca01e-21b0-4f91-8e6e-777ad32c7572'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/UIc2v6/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::633afb47-8f96-4d88-97c3-6b05ef95752f'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/UIc2v6/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
