bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/HFbp0d'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'alice::origins::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCid36vYvHRx87em6v3piaU97uHOxmaooMJ4F78zn49s486YySvBkzcdemuxi'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCI5wsYtx9jx8g8mpZExw58qyTqu3avAt7hnQ3B6NrzgtufXrGOpKT6hfhqvr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCJQrQntmg7k89xis7SGtZHx988Mutzib8QFebfWjcc86y7xqqTkia7Ge9f7r'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcSCJQUcVeMyjijhp5Y4dpQrZStrueuq3tUhz5NTbjiasx7ysRe6rWQbsrti9wr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScj4iG4WJSX8jcjvr4gce88QkK8Cv4cW8P8kY8QpXwsfxh4bqoKuVEet36d8r'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScI5E34E8KrRk5y6M3fJzbysR8dmqws3c4TPca49QrFx3vVn9M79K84X5rati'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'
public_address = 'HcScJ3gW84JgrPjghz3OIFSJo8Vahyjc6esW8MrezFwesd99F4HTjdohssgzpri'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmPBaGbmisGCYgPqV82xZUX3ozuEmJqmtbhDCRZkjzF1t2'
id = 'origins-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmPHWJrJV9M8KhEkRQZhwqtC9cjKc6VUQG6axBVFwxcWWx'
id = 'kanban-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmP1hHTmSf77Q41E5Z8tvoyEefgLHBCWQ3wTBDucDAsMGf'
id = 'notes-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeJz3YttC3m6QKpxkR2saYnLPpsoUUyB8Cf6nvftnGMnU'
id = 'tasks-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmP3JEF2b3JnZ3iqY96pq3hDyKMr2HLShLT2qojFCMbNHo'
id = 'fields-test'
uuid = '60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmaGFbHxWh4kyA9C4qhC9skctWr4PaTq1dTwxGScN4gL25'
id = 'personalinformation-test::dbcadaca-0f00-46c4-9525-f049ff4eac5e'
uuid = 'dbcadaca-0f00-46c4-9525-f049ff4eac5e::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmV4kNmjK3i5yWb8HbAXpnCsdhLaAs5LjfGZBZadRRnT46'
id = 'freckles-test::a794d207-53c0-434f-b1a1-16c730db9017'
uuid = 'a794d207-53c0-434f-b1a1-16c730db9017::60d01a31-b8f4-4d61-91ca-cc4cb04df86d'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/HFbp0d/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/HFbp0d/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/HFbp0d/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/HFbp0d/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/HFbp0d/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::dbcadaca-0f00-46c4-9525-f049ff4eac5e'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/HFbp0d/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::a794d207-53c0-434f-b1a1-16c730db9017'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/HFbp0d/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
