bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/4pB3ZS'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'alice::origins::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCiKyyNa64Oi8udqynnUeXEGdrjaxmc4v694qFrPVXordhggDG3xT53Jgtjfa'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScIQTuGEjaxrogm4apJHim4Wp8c5vtkGzGcK4bIg6doa7eTo6gPkONTseycsi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSci8V8RfHy5Ne87tpqSWxhp5UufdwqqdDQbgj6Jmr3of6hy3qIUPzyoqechqz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCINpSUBddv568rvBy7mZXZQQgoku5zg8ymmbk5v5Jojqu4o6T4AJ58mUeKvz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScJURnKYpopdzimoMVFi86mn8KWnrv3KUmFAiNGrx8s8tnE4KPVKsPcdp6zqa'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCjiYP8gwZjiri45G69PQgTC9cidmhqKJ9JYYybedrersg54mXWUYImf9n9ez'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCjaD5jcumj9zkxqms3oZZadX9yrjnjEpmCtxmCh6gxk8jZRcy8qIUtyp53sz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmRxkGsNZP2Q1yXhwiRfxTotEicNzDRDn5TNL7bGUu5mvy'
id = 'origins-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmQvpxoiR4zLcbZgJXPGGm7jWnnLPN5nZRiV7mTsT3Eyqb'
id = 'kanban-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmVBYv9DcLc6fju9AXUKbpp5guuU3Bae14j7KpC6GbrsEM'
id = 'notes-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmU3pxPmfoaRdcmsDjcZigBDq2xKLVmYq8234Fp1tYfSxq'
id = 'tasks-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmPMyZn4P9iB7KcCLt4u5NkAJ9muQJc2qFaLxAScSjwp6c'
id = 'fields-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmRE7wBc2nSJsw5skNYFbhVHi6LZ8KysZxM9aAh8KS77nj'
id = 'personalinformation-test::7d3438bb-ac1f-4eb4-8c9f-43db01d7f504'
uuid = '7d3438bb-ac1f-4eb4-8c9f-43db01d7f504::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmPpencuh7jGURJFSTNAZMM6UTcZSLhgrCg96E8hWb66of'
id = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
uuid = 'a66e1d3a-6ad0-43d7-9619-e3b4a622690b::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/4pB3ZS/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/4pB3ZS/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/4pB3ZS/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/4pB3ZS/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/4pB3ZS/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::7d3438bb-ac1f-4eb4-8c9f-43db01d7f504'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/4pB3ZS/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/4pB3ZS/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
