bridges = []
persistence_dir = '/tmp/tmp.2oszwWo19C/tryorama/v3DzHH'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'alice::origins::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScjbS8EkID6k6s76SKiUA3Y7VIynmxyzX6v48kF6hONddhnpF447PgUCHq74z'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSciErb6JkTpthkcaP9fK7t8jyrD53b6jX89sUCYC4473ZrhBNJe8jeKtawydr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCIcvQTUfkbb3mnfhd3JMJpyPh5p667B4zMhC6KRDfb7wocCv64BeKh3y3kta'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCig98WpC7bIjb5ukAWJ5Tsd4tvbfykqkwz6FfuMmqjp5wkirsv4BFHatdapr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCJfVkDe8emvvp4uquAs9Erj55azzhugXBTsG659jwnzwd7aqz5ziQs78Owbr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScIkzQx3wK4yc4o4jnS4EPWsny6f3tdMn9Gqx4X8Uejbrzz6kIUI6EgE9xzri'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCIg73a9sKdow4tjB4rd4ROk7m6pcaznfN8oRYnjn7v6p4DIQEpcXD46jai9z'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmUnZVzRcXX2nBYgfpTJDVQVTYHnX3R7bwJ1WRdUn4JmPF'
id = 'origins-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTxSTHTjwMwEW6sUizD8euRk2RV6kLqkXCT4NBXxMkgzq'
id = 'kanban-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQDHS5v5V1cCtik1RiZzBiZLdAmrFqCffe74oHWh2DqSW'
id = 'notes-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmdHzqRj1X2woEa5wxKVx4VHx8HfEK7jKyoXdhZFPLvFpN'
id = 'tasks-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmRzbVi6sBZ15yAS3ri7WXakpJ9XtbTMpkdbYhGS3qLcVU'
id = 'fields-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmTAYJj4UywfgXs57bxix5MVLWzWynxwq1BofyJJwZGgPn'
id = 'personalinformation-test::4db36f2a-7c81-4229-8c80-f65ab42765dd'
uuid = '4db36f2a-7c81-4229-8c80-f65ab42765dd::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmeYjU1hubDJth1NWHCmgPEddPzhnFQDkjoY99ttg9oV67'
id = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
uuid = '93309f35-de11-4f62-8af4-af46a19ab638::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/v3DzHH/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/v3DzHH/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/v3DzHH/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/v3DzHH/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/v3DzHH/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::4db36f2a-7c81-4229-8c80-f65ab42765dd'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/v3DzHH/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/v3DzHH/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
