bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/kFgyRW'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'alice::origins::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScJXuGgG56dyvq6nzgPgyjcvbzjykfh7i8UvppiJUxeqitZwUe8Nk8Z5fw83i'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScjGhH6xSxwqqcdkNCF4d33J9SC89GmcnWTeKcNxxojrk77dHCHH5Na5e7xia'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScJUxsZbciet7wizrG89CDpQVGus6yhT8A4psOu6Ndftxq8kQw8xOXXat4gji'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCitXsavrv9bd4t6Q65c8PQAv8epzcgHv8B99TUCke4dvwC75hXvx7UqUe59z'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCjaOqre8Nav73fos4tsrD6EA9A6qavd4yr9ZDOiwzbbopQ47VSVSCo3v6dzr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCIFggwD87YznstxCwHbpUrh6zecgupMD9Kk9hXaxxrvxo7TIz65q5SSUCxor'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCIJhTchqnktbeauuTAO5Z3XoYsetdc8mIHp6W8ZK7M6kkHq7N8xOP7yp3zzi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qma1JTKpyG4URmDcgPANiRVBr8TneiTXhipMMFE5kPNnU2'
id = 'origins-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNW3pea1AdCue3cNx2cmgD7F2Cpajbu45t3jmXMqfVpL6'
id = 'kanban-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmV8fqNo5sD6Uz86JnFbvQJE6BXcTnhozwm5WF4FoenDL6'
id = 'notes-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmNp9Bw3XNDAHHcBXJn2w8XfdH1QxZ7QXStRK9KUYpzdQa'
id = 'tasks-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbcZ4twcVVNPDwg25HwfzkFaN4w6xWzTctbjf3gn45krL'
id = 'fields-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmVYsYrpWkYReDMvyU1wNHViuYuuFrfK8XQuQY1Z2wwoAR'
id = 'personalinformation-test::e1c3dfeb-97a4-47c1-951f-a99db39e4e9d'
uuid = 'e1c3dfeb-97a4-47c1-951f-a99db39e4e9d::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmWLNDe1gYhjEcNzKmFKPYfsYPbHa2h7YZCyMMrgxPW5uy'
id = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
uuid = 'cda1197e-03cf-4b98-8fd6-8a713f367342::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/kFgyRW/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/kFgyRW/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/kFgyRW/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/kFgyRW/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/kFgyRW/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::e1c3dfeb-97a4-47c1-951f-a99db39e4e9d'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/kFgyRW/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/kFgyRW/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
