bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/py5Fkg'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSCi4RGf5ZDN4aq3i7PuMWXJ6ESzdqvuyx9PxtghR73ng5yze6hr3xqzVhab5a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcScj6Mvvv5OafimrtyIyBCFd3j6q458asJC7dMHcekt3kej3SwXKpZRbrq7ooa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSCJZx5eUS7oiv466sUMHZDszp997i6esB36F7KUXsr8h3tDbkafc3YObjobyi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcScJ8ewXXSTz8zhtbNjX4cgXp6ry3mb74DpF5tGGA9Qfxfw5O75aPcjs8vjiwr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcScj4WvOva3Ex44j5tm6o3RavVQ8btyzFfj6VofcoqxffdsgBvSgrK8xiqv8wa'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSCIU93wh6EpKxpvoxekAyqUwpg3prdxmBroJSybr9zm3zmaiGUpZy64f8a4ar'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmc3dAbkCZpYiaJhU6rvFeFRX3y94KfgRPajzyJmFR3B8N'
id = 'kanban-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYnYdQpsBKykziRFrw2c4e1SnEZrQkT52f5xnM7YZ84M7'
id = 'notes-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmc35riQquy3LLX26RmMS1w3PCeJSLMoNETuGANhaEh9X8'
id = 'tasks-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmNhQTwe4n7Mwy8ip8erF3zpxMeWFdeo9B8fgGsdtksugp'
id = 'fields-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmdUckCavvYqZC6JmjqDC7fyxBXLyhmvKBrWFsppWDktyM'
id = 'personalinformation-test::31f8e248-784a-44c9-97fb-ec042248c6f4'
uuid = '31f8e248-784a-44c9-97fb-ec042248c6f4::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmXE376k38bxBjudZ473CbgZo7qSb7uYRN8H2sPwjRe9eM'
id = 'freckles-test::f00ca8cb-859c-433b-a57f-c16f6ba2cce5'
uuid = 'f00ca8cb-859c-433b-a57f-c16f6ba2cce5::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/py5Fkg/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/py5Fkg/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/py5Fkg/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/py5Fkg/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::31f8e248-784a-44c9-97fb-ec042248c6f4'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/py5Fkg/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::f00ca8cb-859c-433b-a57f-c16f6ba2cce5'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/py5Fkg/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
