bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/Z1Zg2L'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCiKwgqkznwj8wwysW84gpK8VZF4zorsZvZxV6Ci5hvw6io6Rwh3rRZQr877a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCIUpwQE6ebi8rjp53yebye9dd9DqgfY5ubmDsAshksqvmxzZCGgmjko9vsgz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScJJB6ZtbDoe6rz8vud5J3hxWghuch33tejvzcZKb5di4jyXn5DuMXzaxjivr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcSCJq7Wee58j5cyidVSuSfCu5ubracb6conXRrzEtcdmkx37KmYYCQq6Bra77z'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'
public_address = 'HcScJ377QQ9TvxKvxkr6cehY3H5bwz4wdFMN6r4bXf7sjbpeF53QNwNRDFtvs3r'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTvEQoxuEYwvZgt4QRv82SPBEMAbv4pGa5KF6TJUdArZV'
id = 'kanban-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmfENeArJWfouiueEiFJNktR79wd7iEwxmBRps8ikVZ8xs'
id = 'notes-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qme7HaKn5K2zZARtCLWdgvkxzCGLpETeue7iPStGV6eGMa'
id = 'tasks-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmeXdovo2y5QMKi3eGE13tcLuuDB2vjDcCxtL9dBB8y5B5'
id = 'fields-test'
uuid = '11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmQXnANzadBJJ3s2QF5NmEH5nAWQCzfnj7gJywFJx26YFL'
id = 'personalinformation-test::36da855f-6906-42ed-98af-e2351559e5f0'
uuid = '36da855f-6906-42ed-98af-e2351559e5f0::11fc5ecf-b4ac-48ba-88a4-1e2a84a1adfb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Z1Zg2L/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Z1Zg2L/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Z1Zg2L/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Z1Zg2L/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::36da855f-6906-42ed-98af-e2351559e5f0'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Z1Zg2L/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
