bridges = []
persistence_dir = '/tmp/tmp.OWNPLglEr7/tryorama/cRNS11'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSCjv4BCK7UZgzcmrQ93Imvh8wqer5eueoso8kKVre8zdy98pxRQbkGz7x8cgi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcScJktt5jeRsk3aazQR6Fkim6I6edfqbA9YXXACoGcpkgjsBXdx67rNscmpnsz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcScI5cV8ogc7jbnyeJX8dTE4paFvp4qcUkCxX5dMHbo5nbg83P5ibI6dpmnnmz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcSCJ8SRA6Zf8Pye7c9oGuY9DYC973vbcwHuFhai8ddtpxdozMgbOi3wfihn6dz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::94d80625-7315-41aa-9beb-4ac94b237877'
public_address = 'HcScjg9Q5gHoU3szd4n7BeRK5xkFj7iciIKA9WvPOFo6wzx88XcX3sTNjZbtimi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmYVdbfytqwqkM4Mr4gmqm6KYuvkoKmHfCECpnmZkjHMyr'
id = 'kanban-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdGtdWeCoYbiz1qCU2hZmLa2AjUiA6gJeFyKvpYNLyngA'
id = 'notes-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmVWBR6YCNCVP7gCosgv6e63drYiwJaQuqKMnNqizT4aFs'
id = 'tasks-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmWzE9sFyPxuSGK6bBRovcAK8d2sMm7SKVaED7T4FT3dDB'
id = 'fields-test'
uuid = '94d80625-7315-41aa-9beb-4ac94b237877'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmVgkgTNAKUb28dTmCbKevKonxbFWoekqTbcCGrdTwKX4n'
id = 'personalinformation-test::b7e32e73-3cfb-47fa-b3b7-22dc3bb58ce2'
uuid = 'b7e32e73-3cfb-47fa-b3b7-22dc3bb58ce2::94d80625-7315-41aa-9beb-4ac94b237877'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/cRNS11/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/cRNS11/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/cRNS11/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/cRNS11/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::b7e32e73-3cfb-47fa-b3b7-22dc3bb58ce2'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.OWNPLglEr7/tryorama/cRNS11/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
