bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/OcIIrh'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScInSuxnObdevgqvhN4EKB4vNWbckd7EceSRg4r4eksb98P7NSPsJhsh6myir'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScjFhu9FSgxkjvyj4aJ39gvkxqoat4chgqSNtthvrjt3hfDMMXQsNJubn835z'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScJE4MOPnu88vfozRi4ok5DiIit3d5wDuyEqxK9Krr547dF45zjAQExakep5r'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCjFCQDv5vuhjs5yjV4n8vMM5bsagka6DsZ55K6hJk9H8n7WvfNeMOn569fci'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcSCi76Zqqr8vFunisMOzmVXSfy9sua7kd585j9vSpPKdwz8oy7nMaVSkbkfisa'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::460edfc3-8675-4d67-826a-5bd51aae6ae0'
public_address = 'HcScIHw37zPy7XyydfKA3A3pOBsBrnuobe77I6yJ4mONs3h37xz76bHBm7nv35i'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmedGmoWrgruqTQo8CCbueViSHtygNqDGUe5UDuNMBw49J'
id = 'kanban-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYj38vX7snVRgUbRiYSnCSTeQ7rfXRTzPZnthyMGPVuy6'
id = 'notes-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmSkMFYYPAvptbPV4oHMR4jDRR1EZVjrHJy7xE4fqz9jtN'
id = 'tasks-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmZV4fqhTA68pJXXSwLqgDDvj9C4QE2in6H6Er8rk6n5cc'
id = 'fields-test'
uuid = '460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmVdZRepKry5v9eRrzKAjwcV1ijjkyqn2yNk5GTZ3GsxP4'
id = 'personalinformation-test::debc8c36-dd19-4e93-bcb1-b255c2c85c89'
uuid = 'debc8c36-dd19-4e93-bcb1-b255c2c85c89::460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmQKynt27wddsW3qw2SpKgXtToZBEFUZwvrUmHoozA5uN5'
id = 'freckles-test::cd82d866-2022-4b03-a303-35754cdab152'
uuid = 'cd82d866-2022-4b03-a303-35754cdab152::460edfc3-8675-4d67-826a-5bd51aae6ae0'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/OcIIrh/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/OcIIrh/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/OcIIrh/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/OcIIrh/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::debc8c36-dd19-4e93-bcb1-b255c2c85c89'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/OcIIrh/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::cd82d866-2022-4b03-a303-35754cdab152'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/OcIIrh/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
