bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/tNvjUx'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'alice::origins::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScJ6PxTcozfmntuwgHKu5RBhYo636yaMuKdJevh744yyztMbV93667bZCBgiz'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSciYiyh5vve9rak4P5bDyzY6VRyeyouyI9U46JtZ6y6ntaA3VqcWqR6yzh8vz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCiZO9h6QRGxcknw6aSPO799w79vbbkRRrh48Rv8cKxh398BvocDsVXhcnv4a'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScj3Qi9Vo6spiu3ub3J4a8TGFaJ3rp3v6COtoII84Z4xteNMR9sZfNMmiebsa'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcScJhwkBjWczqjdvvnbeCO69n6DtjauySSI95z8jYHu98gfJ7yR756Yapdkm5r'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSciiDf58wTI6oqon9knqI6s4NQExtpkDC4C9FvsXcgmjefuWMsTbDtbcjxqhi'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCiQV8DMEGuozzm8s6v57g4776st4tanaq4cnjecjr9hetSDtXIUIn45ndxiz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmXY5ei2q8tCvRBGb2diHjTj7jQ7pFnwiMf4ERvBSyyLBc'
id = 'origins-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRv9ga5obxctQqz6DPxVkJbyo4ZjadiwD49Hcx6ML7833'
id = 'kanban-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmTujJA3qJUgy2XhvjvVxWSYbegUV8n1GDuRmsSePfL5YK'
id = 'notes-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmf5CUzvxThU6C22RsBKRBZTf8spmynjavtWe2d9dgqXjr'
id = 'tasks-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmdzu7EiT4eM89tDytzJ1SsJLPPMdJ23z9aCeYnwniUumW'
id = 'fields-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmYD4Vocg3MRDfNXyNqKzzCiPp8HrLGteDWnHWPQzpt543'
id = 'personalinformation-test::29141bc5-486d-400e-a46e-c6bbb298d0a8'
uuid = '29141bc5-486d-400e-a46e-c6bbb298d0a8::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qme4LkdURYs1nEpK4VhrmvyPbPpPDw6ZCkVHYMFgMa9VBT'
id = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
uuid = '84b0e8f9-cc77-43b4-94ad-a41582d7b704::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/tNvjUx/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/tNvjUx/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/tNvjUx/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/tNvjUx/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/tNvjUx/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::29141bc5-486d-400e-a46e-c6bbb298d0a8'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/tNvjUx/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/tNvjUx/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
