bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/6NlNLK'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcSCiIT6aI3vbxyg365XZ9j9s5Fj496hsRgNBvwcxrikmqgqrkZ9AdeONsckhpa'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcScJxrKH7A5W36rcezEbnMVGGwt9kdgdKQk69PStWyyzwkg9GNk79X6zH5wtiz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcScjRHm4KU78iqusenvON993bvI6By67kngbrwtAgxgqane6MT4H8uS36taWez'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcScjw9Cgp9GGjeawyY66iXva99kN4BzeTfWUQYizd5vvmeiQA5Ip93FOXknapz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcScI4GBqexH3v855w58tBQiNy995W3ferukhGhU8Zukdjq4fsdXK47AwAirpii'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'
public_address = 'HcScjkfNCeUkux4z78aoJj8ntKcpsnf9gY7yjVK43h86A9xr93vxrIU4tMwsior'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmbGHNTYEnW2Q9j6N25bYJWSaS1Gu3nCpr6qJcgsKEeSGK'
id = 'kanban-test'
uuid = '4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'Qma9UT8W1JG7B7bKCytWsAi1cGckSfABik11c1U59QLAo2'
id = 'notes-test'
uuid = '4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmZTX4sAybvBeZwTd4jos7UURizccWDRi3i7dJEzSYkfuN'
id = 'tasks-test'
uuid = '4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmcoU6Ht8kvYYQN4RSnY5brSJrQZyrSjemdVgmnVogMuFX'
id = 'fields-test'
uuid = '4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmUFhh9Adt4MHPMMQc7shSvtrf4u1ZJgFBWGMwYnnQT33h'
id = 'personalinformation-test::713443d1-7435-4fda-9717-b100d66f91c7'
uuid = '713443d1-7435-4fda-9717-b100d66f91c7::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbR5aoTdoKs8itdhvPzwd6CVEXmSS66K58c6ZwrJDY75t'
id = 'freckles-test::477b7602-9e49-432a-80cb-7b614a4614cc'
uuid = '477b7602-9e49-432a-80cb-7b614a4614cc::4e0fa48b-1ba5-4cd4-a0f7-cb9332bb1ee4'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/6NlNLK/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/6NlNLK/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/6NlNLK/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/6NlNLK/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::713443d1-7435-4fda-9717-b100d66f91c7'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/6NlNLK/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::477b7602-9e49-432a-80cb-7b614a4614cc'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/6NlNLK/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
