bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/06l7Q4'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCJjjOV6HGvn7x9moc3KUx7FRmbkmzm4uyhnbH7Faqgz6bd4ssI3VBs6Zgzma'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCiM3cOJ9yvaxr8nPoyjnxMCyou7t7yQHn6wiO7a6dc8a7rTrsfSVmn75n4yz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCjdJVNK7dkc5kaiXc6qR4hu64FNkhszwpoCetj4wqcp553FWDD79yPVNa7dr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCIfsSs6QFdksuf3Zt7jZyXyM67ufkuacST4BHycyb6f8dbgA6PH78rqhhd4r'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCj7sV5VX8biw8e9otgxPeyfongs5e8JHeovoOQ34tj45dVTb3MKEIb57ijsi'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::7b626691-ab6c-4019-b71a-90ccc9150ef3'
public_address = 'HcSCI6UHwMTmeive6t3saf7v3oBMeawrhgpiJi8BXWqmstimKCHAdfcK7h7k6xr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmZ2TGpauVUoTTTPwmqNpwmCLcDavKr4utUxdJAmHXZfXE'
id = 'kanban-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmbL8eFNsa9UYtJY2iqRPWVfhHok46fdoYCAskt6gakegE'
id = 'notes-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeqVu6wrMg1KapacXdZDLr5CC4WkjMKYUMXdjubuHeDUE'
id = 'tasks-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmap2ypwmfw4DccYDrJDDZF8iGRbKNsMbcAV69NwRLQ5hG'
id = 'fields-test'
uuid = '7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmaxjiUUEHNDSfGvRHkFBBe1q5kNAi53uVigE6BXLePegz'
id = 'personalinformation-test::e754c4d8-cdea-49ab-a151-1a84d62d2980'
uuid = 'e754c4d8-cdea-49ab-a151-1a84d62d2980::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmSNFSC8iDvsCT8FUiFUFY97EZcTLaAnHmX6UsysFtzbdU'
id = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
uuid = '59280fe2-f7cb-43ec-9f20-e4d7cd883a8b::7b626691-ab6c-4019-b71a-90ccc9150ef3'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/06l7Q4/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/06l7Q4/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/06l7Q4/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/06l7Q4/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::e754c4d8-cdea-49ab-a151-1a84d62d2980'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/06l7Q4/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::59280fe2-f7cb-43ec-9f20-e4d7cd883a8b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/06l7Q4/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
