bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/3RmUoA'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcScid3ad7Nopgbd3qJzTjYvMRxpgntkpyDK7YKw7m73vocsUFJIPj58t5kyxwi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSci3Q8vOGbsac9nkJRq3fnZsXwmi3ok3E3DZ74cbTrNhvxm3MH7tFh37Erqmi'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcScizeKYjcegnvoj377QMZaeI4zSoc4zVeaY5W9dkFhwmawP557IgWUubkjxez'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSCiGHBKthwxd7qp7jOkAxdXobo466gxycwQj5iF9Tzpmc6VSa7ASV37qR6b3a'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSCIZS34H8AW8Jj9mZBjZb54B7vh3pcmEs56MGa9GCZ4ucaAYfYdBUhkm8ovez'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::98ca96a2-3e14-4667-901c-7749cbf91902'
public_address = 'HcSCjR9knjkTrcb8qzP5M7X6DrgY5YpuvbZUh7XuiAisbyoacdUXbKvghehpzcr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRkZXAU5eLc97AT1VHyh3AhfAs2AByVhwpV3rxr11zBna'
id = 'kanban-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPhVNhYLSezQ38m2rj61gJpHZu5B51oEAcVHhGhNEaMzy'
id = 'notes-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmdY8guqM7UnX1RReGfpsVLJSiwvXUa68FvuZurdhhSSmW'
id = 'tasks-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmdwWqWuiSe6EFvkX5zhfD3T4nJPZGKhpCZYJW64gc891e'
id = 'fields-test'
uuid = '98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmakY8zcdPVwGJyRmrQ7QpkRv9s9WnaFzx49mNdhLVi1PE'
id = 'personalinformation-test::02bedaa4-0de8-4ed3-b6db-0fe28e88e51a'
uuid = '02bedaa4-0de8-4ed3-b6db-0fe28e88e51a::98ca96a2-3e14-4667-901c-7749cbf91902'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmVLY4FKCq2Lx6M8pVUDJpEAoAJ9PrWFXMzf25cD2YRTWt'
id = 'freckles-test::f6edce91-1156-4adc-8517-442c564a2dc4'
uuid = 'f6edce91-1156-4adc-8517-442c564a2dc4::98ca96a2-3e14-4667-901c-7749cbf91902'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3RmUoA/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3RmUoA/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3RmUoA/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3RmUoA/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::02bedaa4-0de8-4ed3-b6db-0fe28e88e51a'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3RmUoA/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::f6edce91-1156-4adc-8517-442c564a2dc4'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/3RmUoA/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
