bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/U9g8qQ'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'alice::origins::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCItx9CZN3ztojo9SxIUBodKacb35ebWj488EE5EKi5ipci494E7k3XgU5Nnr'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScIQUTwG74cphmztsBsp88j8nqHf5dijKQ3sbAuVrk765mN53g9BI6p9Zr6Zz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScimI6k85D74wGqa3RUjnvCF3Apokyy7k5DeGXCcWvwkjb8CETSIOKqqi45hz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScJBooqWvfxcauc5HO58TR6aAGrpzsnxx785NFD86AVow656z3S6X9GwZM5Wr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScJxHcOFQ3tfn559R69b43h4PGetY9a7RXVt6yS97jQuqiINd5qGZhC7nntxi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcScJf35norJgwp3sp5tB3P537RhJE9bs35rrYjXCqGu6d57uxsbeIUH5g3vk4r'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::bc941daf-bc8b-4237-8666-ed4a145f48a4'
public_address = 'HcSCiddIDpx3ytktvcq5iPM75DDqP9e578pOJ8JQVPRgrj6hrEn3y4VtO656bur'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmQutjyu1gmtmBmAysKi97J7zWFGZ5vd4qswrqNt2RU7xq'
id = 'origins-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNnYtKAEggRsuFufbRZyPmKYgRVtTHNVWHmGMmsYPu7C6'
id = 'kanban-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmaNcK79mga5ttAcHDfZT4KphgXsdYLZeFhM2Vw5UL5euF'
id = 'notes-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWkkYJaZxunVzn66Sba67XRqsvCrBKuYm7744TJwyrK49'
id = 'tasks-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbA5oA41mbtKNCSUaAyhvc8NUjzidT2LDop1TqZETawmu'
id = 'fields-test'
uuid = 'bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmRHjLoAcaEE33SHAzb8gG7ZehoyqPqoZEaY68LNnTkzNT'
id = 'personalinformation-test::b7cce387-116e-4813-9a9e-2c3516ca00ab'
uuid = 'b7cce387-116e-4813-9a9e-2c3516ca00ab::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbrwEAXQjS1b7fqhLFkmxusDXYirSmATwMW9nE9egS2t4'
id = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
uuid = '747c6bb9-c2d1-4b5d-9927-b3ffd4174748::bc941daf-bc8b-4237-8666-ed4a145f48a4'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/U9g8qQ/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/U9g8qQ/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/U9g8qQ/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/U9g8qQ/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/U9g8qQ/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::b7cce387-116e-4813-9a9e-2c3516ca00ab'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/U9g8qQ/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::747c6bb9-c2d1-4b5d-9927-b3ffd4174748'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/U9g8qQ/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
