bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/PXodjy'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'alice::origins::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCjfMhN565rnd5avP9ZfgzXnbtubo4hMJbKQUj95Ur5434X9TJUSoQx3yj95z'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCJHgqYb764v486zR75DHztxsmi88o3ikpiDmseuzvcyseazX643Og6CHuw4i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScjaSGw4pIr8y5egWAkCUBy4Bvqw7a3twhtG39B7wh4drkqDuocQdmbasb56z'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCivm8Nyg34uosbgTIoc9mu9Gs4j45gYW3n63rIS9J57rs6ZeOMbbSawkzbqi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCjPXGZaE6cg8vhx6PQ6FBEjmSi8k83u3igxZ9Nb74smyncTr6sk8RNzoawpa'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScIk37iZQoyijsjzYaEJO4zI4Rc899gZ9RX9rv3fFwvxak6OEFiJE7fJwjabr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'alice::freckles::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCJrD73S5pHq9pdvyQen7D5AARo6qdfPCv89cpAMQ8md4dvKFU3Ejup3q667a'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmWyriGuATgo1GFQgTptmfCxeLZXGMXyadLtCANQDkY3K3'
id = 'origins-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmcDhhqTmDs23m3Y5BkdBzQfGL1eYDSfAnnsBMQoCwMqvG'
id = 'kanban-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQ5y4jfcu9qXKPp5ruu8ooAzvJ2Lb4Kzwmr9UpQLAoobR'
id = 'notes-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXDkj9aqA28zUksXSwonAF3nSzPvgycUnZEqsyAvJ7CAu'
id = 'tasks-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbWbsBwqnuGBUvnBhVXSQ3f5qMGihdEFPsyDp4eK3ognT'
id = 'fields-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmRUhnELajeiKtx8j9rcEaxyafgzugYdKiVo2uA8ygx46T'
id = 'personalinformation-test::65825a50-1455-4bde-955a-7b75c6d738e5'
uuid = '65825a50-1455-4bde-955a-7b75c6d738e5::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qma8Xq6UMmagyzuug5iM8YjrVe73caRyNrQrtXHMWBoVU7'
id = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
uuid = '33fd973f-e5ec-45c2-b4e6-bbd294cae814::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PXodjy/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PXodjy/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PXodjy/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PXodjy/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PXodjy/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::65825a50-1455-4bde-955a-7b75c6d738e5'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PXodjy/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PXodjy/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
