bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/p7OdXF'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'alice::kanban::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcScjU3zxHKHiy58xbW546GNjwNvKjtmkiMvuFTa65bp6zkwj8OIf9WSepiaita'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'alice::notes::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcSCjcQz4BKb6wjnei8e9b3MUYHTcy9r63v3Mi7nncT6Yvhz99snK6c3wnHKfqr'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'alice::tasks::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcScjN55zI64K8xY5zjiGWqQpHhgzzv6zxX9fSo7CRWz54nbkvuTB7h3yTpednz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcSCJXXAQZT97i5gavANosp3VnEwidpy4qRwOjkXresjneidgiM5oHRwX5iqb8r'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::a3ef64bf-5a74-4422-a632-39bd9958cb88'
public_address = 'HcScJuI9BuZss9w9d8HgsUjvEuki6v35hWT4r3OE3knHz3cwv68TFkvC9Rcsnsr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmem7H1NSpNJUoLiNdbwUgFFpc8aLyZWiay1Qfd8s2NRrK'
id = 'kanban-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPjz9jKtrrN5DLdUEvV8LdZUm9MZKcMJTZM6omS2Vqh6B'
id = 'notes-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmTabiqZ457XGHP7Z4v3vnce5JzLaVGc6fsrzFrY4A2Yq9'
id = 'tasks-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmQLMMUFJmtAEYzFe8rJ4ZUU5r5944ewJJZc7bmsG9mBAf'
id = 'fields-test'
uuid = 'a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal information/dna/dist/dna.dna.json'
hash = 'QmcqvTTdbRar9WKWZTJM2xbENructJ6kqUS2qWnQq8T7RX'
id = 'personalinformation-test::c730d9cb-e12e-470b-a43b-2ae0baa78504'
uuid = 'c730d9cb-e12e-470b-a43b-2ae0baa78504::a3ef64bf-5a74-4422-a632-39bd9958cb88'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/p7OdXF/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/p7OdXF/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/p7OdXF/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/p7OdXF/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::c730d9cb-e12e-470b-a43b-2ae0baa78504'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/p7OdXF/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
