bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/2jGx2p'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::37d9f00a-49d8-43a4-93b4-5555c33d3da4'
public_address = 'HcSCjfRawO369d9erzoywovaZRgo3chjhieA9DX9Cw6kja489vFzudvN8wxou3a'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::37d9f00a-49d8-43a4-93b4-5555c33d3da4'
public_address = 'HcSCibtzHvYwe8iyvdo8j8KGE74mxU4mdTH64zpqc6IWtt8oWE4Yg5wR7ir5zta'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::37d9f00a-49d8-43a4-93b4-5555c33d3da4'
public_address = 'HcScIoJAGrbqxbsoia8kS7VEmcRPvqfpfJw43HknP33mPi8h9Pqu76gXc9d3Har'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::37d9f00a-49d8-43a4-93b4-5555c33d3da4'
public_address = 'HcSCIuZ4w44t4Kx3xhqK6WDX6CdMyykyb67jAcvu4S9OCzhevWuoBJKSsu88aor'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::37d9f00a-49d8-43a4-93b4-5555c33d3da4'
public_address = 'HcSCicS4vxTanta9tk5E44R77pp8CQhBgehUWDxe7ShruipfWAUJAzBR757nooi'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::37d9f00a-49d8-43a4-93b4-5555c33d3da4'
public_address = 'HcScirUz8g6iIdx8viqzY8GTkmGuik3gfZffhWv65AchpnrrbAnDNWvyyircqdi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmSFdmx4d5P8gtnAr8kDLpYHrKdyZkChZwncoqP9NR69eS'
id = 'kanban-test'
uuid = '37d9f00a-49d8-43a4-93b4-5555c33d3da4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmeexD5S96kWcXpKm7MgvqZ79uQGyJUGB7MmZNRJto2rRC'
id = 'notes-test'
uuid = '37d9f00a-49d8-43a4-93b4-5555c33d3da4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmYQZDU7jgzBXH6vzvFJmjLf4N3W8CWncoKWqq1BAmqiyP'
id = 'tasks-test'
uuid = '37d9f00a-49d8-43a4-93b4-5555c33d3da4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/fields/dna/dist/dna.dna.json'
hash = 'QmTjHivx6R5KqHxdcFgrHZzJGZyCdTLWyVB3TEw8JhNisK'
id = 'fields-test'
uuid = '37d9f00a-49d8-43a4-93b4-5555c33d3da4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'Qmd6TZ2SQTJXN9QpWGZYgkB5msEDwBg8NMR9Hs95nWpUxw'
id = 'personalinformation-test::10b7c8be-208b-4c31-8dc1-e1893b84b09e'
uuid = '10b7c8be-208b-4c31-8dc1-e1893b84b09e::37d9f00a-49d8-43a4-93b4-5555c33d3da4'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmUthW1bHmvcEkFaEcnoxAgSHs8YqGLCyjmKD1YhKvaoFC'
id = 'freckles-test::e9de571d-836a-4748-a802-993893aafcae'
uuid = 'e9de571d-836a-4748-a802-993893aafcae::37d9f00a-49d8-43a4-93b4-5555c33d3da4'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2jGx2p/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2jGx2p/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2jGx2p/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2jGx2p/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::10b7c8be-208b-4c31-8dc1-e1893b84b09e'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2jGx2p/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::e9de571d-836a-4748-a802-993893aafcae'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2jGx2p/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
