bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/xvbxLd'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'mark::projects::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCJuGP9keAixkurqi3rZ4HOTnvwqvzt86hijYKhbkx66hbQkCYyKI75f4t57r'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'mark::origins::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCJ78c3FQt5cX9qyPbki4gcDKsgqqtn789m5t6YjoDf89RYxnKMBzto5mfjdi'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCj7MgJTBVzspb36ZZyXv8Gb3Wwxhkfy7U4eQunsuwkxgi3IUgOzbXA9bgtta'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScisdD7IsJj8yhvqfzDh7pM4pGv3m9grM65ayKKbSucrznZzOCxwud6kskpoz'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScIOQh6wGhg8mwwef87r6UXDCgZbekoAsE76YR6TgtreuyjUpgQqhvbva8nrr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSci6gfdX3f8A3o7j9YVBaESFbq4unxbCb4IJmf76xTkrgvfukr8iX66i78Ihz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcScjADi5YeEsoi4mbVcNNo9s5Ph35gggX4C34vTkuDmxnhx5iJdaQzN6J5uqtz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::c8655cb3-76de-4c04-8a06-b232f7c2683e'
public_address = 'HcSCjqcO5CNXu95c8d6mY4AR68PZyinj5zkppwBFD5si5vssQW69xo5B7cbGhbi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'Qmb2RPsPGcdCwkNtHmdHTieSC7dP5URhfkZFGfsQp8gAFq'
id = 'projects-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qma1JTKpyG4URmDcgPANiRVBr8TneiTXhipMMFE5kPNnU2'
id = 'origins-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmNW3pea1AdCue3cNx2cmgD7F2Cpajbu45t3jmXMqfVpL6'
id = 'kanban-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmV8fqNo5sD6Uz86JnFbvQJE6BXcTnhozwm5WF4FoenDL6'
id = 'notes-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmNp9Bw3XNDAHHcBXJn2w8XfdH1QxZ7QXStRK9KUYpzdQa'
id = 'tasks-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbcZ4twcVVNPDwg25HwfzkFaN4w6xWzTctbjf3gn45krL'
id = 'fields-test'
uuid = 'c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmZVPnQZCQMSzxPGqJ9UMGsDTHAfPM4K3S74XMMnLLMtmz'
id = 'personalinformation-test::d7418b74-2e1b-4d15-a79b-96d584b9389a'
uuid = 'd7418b74-2e1b-4d15-a79b-96d584b9389a::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmWLNDe1gYhjEcNzKmFKPYfsYPbHa2h7YZCyMMrgxPW5uy'
id = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
uuid = 'cda1197e-03cf-4b98-8fd6-8a713f367342::c8655cb3-76de-4c04-8a06-b232f7c2683e'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/xvbxLd/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/xvbxLd/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/xvbxLd/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/xvbxLd/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/xvbxLd/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/xvbxLd/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::d7418b74-2e1b-4d15-a79b-96d584b9389a'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/xvbxLd/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::cda1197e-03cf-4b98-8fd6-8a713f367342'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/xvbxLd/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
