bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/PvNTWK'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'mark::projects::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcScJhfD9v47Pc39hctNdg5PNnuqnipeh85sGMem5t9u3anfJQbIqjo8Rtjowzz'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'mark::origins::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcScIK8gw8eNAbawp7b485B83t8XpCnDbOiv4t3D4RVc67k59HBVWKw5rIrnoci'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcScipc69qM88x3DteRR8k955TQihUdodNP3Yncj5BK6sw6sqpJUGoZ6Ui59rfr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCJRnX7Iy98Gccy5N6BzM8hNjIijfccMPXC7D5KdIt3vpsJ83Fvm6O4FA4Pea'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCIXXjHs3Rfjrzdq6uEUGioydkpvvtw8havv3wpJO5oikdPkf4KK48Ja64xii'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcScjcS79eAGx8hh9v733HbsWvBfq5bc4KEjuv8pPeigya6in7dxgy9O74nxzcr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcScI6dioXp35696Mk3pty8I6HWVTvcppA8Hc3cd8VKzktbhfGJRnRUG9ud44sa'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::40c9d725-fb55-427b-8480-b4907c2e07ef'
public_address = 'HcSCjnImfa6Qynjj4koWqWJNCMesxovyj7uSxctR38kFw7ec3IWBik768nroiyr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmVTKX1Lo1hzEKgFHPbcizERgNShzZ8nZzzpGEoHdHTdV5'
id = 'projects-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qmb7p6mBV37tfhmhX8XYrVWGKtRvCcT5DTnFJgtdpZ36aQ'
id = 'origins-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmeYSH4uiDD1B7FxFpYishKeRbHy4PrVXUH6y1pxoE9N3B'
id = 'kanban-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmPwfAmvYZLXHnXcE56XCLYd7iSZUUbcimp9WqaZEKjPuz'
id = 'notes-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXbj16YVJEEsvnueYT9rLNPYpyu4WvQKVgL5HJ644dvWi'
id = 'tasks-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUx9DQeZrXmN1PA8ahX5VVyQa8pR2hfREgJQqyD5Jja1z'
id = 'fields-test'
uuid = '40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmT7XzohE2ainaoCvXmoajrMLpxK8xHBtiJaNLVJgGAEEw'
id = 'personalinformation-test::b26dc8bc-b789-4f19-bc9a-3e25c8f99963'
uuid = 'b26dc8bc-b789-4f19-bc9a-3e25c8f99963::40c9d725-fb55-427b-8480-b4907c2e07ef'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmWJ7PP9r5YLGVadVUNVa1Hor9WrSpSDcgj3ucMnseC1qv'
id = 'freckles-test::2a056bee-03fb-4871-a9d7-07acc3002515'
uuid = '2a056bee-03fb-4871-a9d7-07acc3002515::40c9d725-fb55-427b-8480-b4907c2e07ef'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PvNTWK/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PvNTWK/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PvNTWK/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PvNTWK/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PvNTWK/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PvNTWK/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::b26dc8bc-b789-4f19-bc9a-3e25c8f99963'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PvNTWK/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::2a056bee-03fb-4871-a9d7-07acc3002515'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/PvNTWK/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
