bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/eExQJV'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'mark::origins::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCiE8ru3AcRhzd4ed4pffaEjNxb88b8w9csGd8Z4ufmuxhH583F7XpjoKy94r'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCIZDUxIczwq3debFWgapD57O75gybkSyVu7Nc395ewuwn934kuIWDCztadsz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScIc4wIv5dUbd4ryG6mUuCdn8txuxqu6d8q49R33xbAQX5W6W85GFThj7nyar'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScidND9Z8cDnvwttBGZYTB69Rebpe9ubYb4t6g5K7EW4j8CEVnIO9rqusxcga'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScjTzAaDZabbcg69YUwmtteEnxfn75mu3hAutIZ9Vs5kbaV9o7UEQPqhoqu7z'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcSCIMqfo3iyfn9qcdg36RUeh5aA4BpzwO55UTxZv9awsqnswZ8jz88jZ8n6H8a'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::fe4e8898-eedb-4f06-967c-b7535d26c6e5'
public_address = 'HcScIvgyN8rEdc3k7oZ3sui8CSQ89sdzvSJo9yrqGC74y46yFoSxX3484bRSqvr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmRxkGsNZP2Q1yXhwiRfxTotEicNzDRDn5TNL7bGUu5mvy'
id = 'origins-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmQvpxoiR4zLcbZgJXPGGm7jWnnLPN5nZRiV7mTsT3Eyqb'
id = 'kanban-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmVBYv9DcLc6fju9AXUKbpp5guuU3Bae14j7KpC6GbrsEM'
id = 'notes-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmU3pxPmfoaRdcmsDjcZigBDq2xKLVmYq8234Fp1tYfSxq'
id = 'tasks-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmPMyZn4P9iB7KcCLt4u5NkAJ9muQJc2qFaLxAScSjwp6c'
id = 'fields-test'
uuid = 'fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmRkY6VfTFYaD8MqZTNecLWrP4V7fe8d7g7pufN7Sj1MoG'
id = 'personalinformation-test::e49401c3-37bd-461b-83b1-307532b2a1f1'
uuid = 'e49401c3-37bd-461b-83b1-307532b2a1f1::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmPpencuh7jGURJFSTNAZMM6UTcZSLhgrCg96E8hWb66of'
id = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
uuid = 'a66e1d3a-6ad0-43d7-9619-e3b4a622690b::fe4e8898-eedb-4f06-967c-b7535d26c6e5'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eExQJV/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eExQJV/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eExQJV/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eExQJV/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eExQJV/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::e49401c3-37bd-461b-83b1-307532b2a1f1'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eExQJV/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::a66e1d3a-6ad0-43d7-9619-e3b4a622690b'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/eExQJV/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
