bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/Sz6O43'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcScjX8FsbUOvm8o9akAmiF9mQm9f8ofomFtNIOFjr9onasuRfvZnWCv7eqjpoi'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcScjHe9sMJnxknf5z7bKjKVQN8axfixhUGyd494ZmNjxjghzxH856KNCyCk94z'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcScjtRhexDh46a8t64uPbm3nW9SYwy8k87KKb4966tfIqTy7Q7wRJT5U9QCpma'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcScjyrW8u6Zszxtz87upTX7Vu4HWi6biBmk6eKTWjvsr45kiMZUVxia3r4uryi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcSCjaWgK4AvyvhkuyQOfJVQ9ODc86v7eI94aUc8ymjNfovnXWEkrImJqf4phbr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'
public_address = 'HcScJdmQhvSehimtuez6gD3ff9Xj9QsuwstkeOOo3I5zskrpEv6Nd37fd88N55i'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'Qmc3dAbkCZpYiaJhU6rvFeFRX3y94KfgRPajzyJmFR3B8N'
id = 'kanban-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYnYdQpsBKykziRFrw2c4e1SnEZrQkT52f5xnM7YZ84M7'
id = 'notes-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmc35riQquy3LLX26RmMS1w3PCeJSLMoNETuGANhaEh9X8'
id = 'tasks-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmNhQTwe4n7Mwy8ip8erF3zpxMeWFdeo9B8fgGsdtksugp'
id = 'fields-test'
uuid = 'b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmUzNorcux6SkqeUQm1cpKQLyBVahS9nZMXuwJUYXkSW8J'
id = 'personalinformation-test::09aa35c9-a59b-4850-ba57-2eaa734c535b'
uuid = '09aa35c9-a59b-4850-ba57-2eaa734c535b::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmXE376k38bxBjudZ473CbgZo7qSb7uYRN8H2sPwjRe9eM'
id = 'freckles-test::f00ca8cb-859c-433b-a57f-c16f6ba2cce5'
uuid = 'f00ca8cb-859c-433b-a57f-c16f6ba2cce5::b815a7b0-8e99-4ed5-84f9-8f2227cc3043'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Sz6O43/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Sz6O43/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Sz6O43/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Sz6O43/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::09aa35c9-a59b-4850-ba57-2eaa734c535b'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Sz6O43/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::f00ca8cb-859c-433b-a57f-c16f6ba2cce5'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/Sz6O43/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
