bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/fUbN8q'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'mark::origins::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScJmHid7a6cmuyrrESIa4PcsUh3jsmohn53JUEGap7s7oc64UnX7V97N38dYi'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSCjQ6D79Hcprmmpifb84E5y7GoHmd6agAk4WwDQXvki4aiPmIfSbR5qezzk8i'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScJGTvKtgsdgdp9zkxuX3hKIszt8o4cSpROGUbAooq9dccoqErPf7b4Oo45ki'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScjQFD38kP9OygyoxQBvA3rjReyoh9d7Qo9m3v73ihFr63Z3Yno7s66sWhnkr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSciPeOEO3usnxvefi8JIh88wtkx54cpx8NWmVX9E6PvsowNv3NwXUkPe88wai'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcSciubtiyJuhx7ehmvp3xAw4RH37q6rbCGCBUZZ5angx4zhQ3Az5ugcfrzteiz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::889bcef4-61c7-4a26-af31-ebacf3619ff6'
public_address = 'HcScj9MsKyZQry9wy4oC33qwHP38Dp5qoNedp7g9p89rnry46GRtX4933Z36YIz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmPFZhyBXvh2hQ5PS1owunyYQYXtYdgQiqvqPddeF3XkoQ'
id = 'origins-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmeSXu4dswfLrsRyzNTbymk8sKpkzwbRxAYRpfhv7GVRit'
id = 'kanban-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmUXgNsmbaFgMgBzaQJSAfaCyKu9iYGJqoi9FozngzLTy8'
id = 'notes-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXXAi39ozsnt2VevFJXXbfosLbd9H5GXBuGmT9kEoh4jt'
id = 'tasks-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUVZeALCVgsXi1cwvFJNtxMQYLvfAg3v8WSQ3pwGvT71f'
id = 'fields-test'
uuid = '889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'Qmar1ECmK1bUnYvEygicnhzinNBXEWEKhPRyjuySrAMSQg'
id = 'personalinformation-test::58dbb50f-1ac8-4c37-8a0c-b06ec1da2dc4'
uuid = '58dbb50f-1ac8-4c37-8a0c-b06ec1da2dc4::889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmVYSaV357KD231hRsiHoRnxtTh3yAhh1qy8XDYmFJ8JLj'
id = 'freckles-test::4b691b60-1794-4462-a39c-ab8fd0038262'
uuid = '4b691b60-1794-4462-a39c-ab8fd0038262::889bcef4-61c7-4a26-af31-ebacf3619ff6'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/fUbN8q/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/fUbN8q/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/fUbN8q/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/fUbN8q/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/fUbN8q/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::58dbb50f-1ac8-4c37-8a0c-b06ec1da2dc4'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/fUbN8q/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::4b691b60-1794-4462-a39c-ab8fd0038262'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/fUbN8q/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
