bridges = []
persistence_dir = '/tmp/tmp.ZoqKnNUsEm/tryorama/PmMLre'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'mark::origins::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScJ8bwpWDY9pmijjV93pAsacQ4E74fqWtjZokv3zuyow9h4vMpoOxg7Tf7soa'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScja9KJN3P8Kvm8y5YyEgZ66j99hUwsaWVCEHjRrb4ido763RRn9nqK5hiczr'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScjzt9DnMDz4oi9sEIequeHrbijef4p44q9iCeVNRwp65daNGyInidxznqzpa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcScjga5O4Fwj3jzwosYUDNuYN4rk3tcvRcBGRoc4S77wtytRYz7Fucv53xnojr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSCiM8IfPs4Sny9nkKab5zEMur993mrpoPTna79b5Vdb335qbqokxO9Dertsiz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSci4Nigi4RJf3qzjYDNSTId3afgmu6dujQI4oc5q39MrzkpKOazCJJgfj9qma'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'
public_address = 'HcSCjwpyTnx4tmp3ig5hKzs4wHt83Oaa73rFXRR3k9D99VsmJY88kAPRDVtqngi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmWhapg9MKVmqX8oHFvLizv6gCL7Gzjep8fFgqdv4waiZX'
id = 'origins-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmaEK8Gr61M18zkMpYCW1GBge43SJi312yPPm3zNixVaB3'
id = 'kanban-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmXMyGVJrUGD2uveJEjzrQk4FQy5jPYwUTHhPJ8tSsZjcv'
id = 'notes-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXKaDmdKERMJfrreQNq6BSVtEwedfiyeMrjBhcx8FYdrK'
id = 'tasks-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmPVJJiiakMRi9hfz7YXJcuUjH8eDDwgjtoGYt1j4n1csA'
id = 'fields-test'
uuid = '4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmaEHBttcJexkn12dH8D8Ts8k56sWG455PLo941e5yGmgJ'
id = 'personalinformation-test::0740c1eb-28cf-4658-a4b2-96a6852cc78f'
uuid = '0740c1eb-28cf-4658-a4b2-96a6852cc78f::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmbHXCgGeVAVNRTNVGTEJevtYx7zmtnw3Ra6g6KKvf9Vt2'
id = 'freckles-test::633afb47-8f96-4d88-97c3-6b05ef95752f'
uuid = '633afb47-8f96-4d88-97c3-6b05ef95752f::4c9b8bd1-8709-450f-8ed4-28a4e0ad0543'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/PmMLre/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/PmMLre/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/PmMLre/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/PmMLre/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/PmMLre/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::0740c1eb-28cf-4658-a4b2-96a6852cc78f'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/PmMLre/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::633afb47-8f96-4d88-97c3-6b05ef95752f'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.ZoqKnNUsEm/tryorama/PmMLre/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
