bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/PyEyOU'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'mark::origins::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCjc5xHO4Uchms8zYzg5NZINjxnfaf88z9I8VSE3ZiBjprxCtn593Jd7rFmhi'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCI4B6pfko9c8jswp7p5fnBkm8Mmgrmwbgx9nevfpmpwk7Xam64I3QCQwa8bz'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCJ5qv6FR6qhsiidIcBMqbN3s8u83uvpx36iESNm85UihbGROIyfTNtznht5r'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSciiMcMfS7ymqt3ygQ4Scr5Ju8bxnm86hVryo4C9pdp3pttSamU8mWWvrftui'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCiW4kR5Za99hwacY39WMQ5887EwTWbcM6TYUDNjgeup3pEhknk8nPrn77yrr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSCI4M4cuBv7bmtu4zmj8D8uJWmdto6hkHKgW74HsTghaigSCVJIdx5tyedn9r'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'
public_address = 'HcSciDsZSnXz63ukgmPa5KeFKkqe9fy6rSeGWgSkv7ew5ee64FfmxZVmZnx43mz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmXY5ei2q8tCvRBGb2diHjTj7jQ7pFnwiMf4ERvBSyyLBc'
id = 'origins-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRv9ga5obxctQqz6DPxVkJbyo4ZjadiwD49Hcx6ML7833'
id = 'kanban-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmTujJA3qJUgy2XhvjvVxWSYbegUV8n1GDuRmsSePfL5YK'
id = 'notes-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmf5CUzvxThU6C22RsBKRBZTf8spmynjavtWe2d9dgqXjr'
id = 'tasks-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'Qmdzu7EiT4eM89tDytzJ1SsJLPPMdJ23z9aCeYnwniUumW'
id = 'fields-test'
uuid = 'b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmRY7yzKdsYrSukpE3ncap755GemVkETiNZ4oK2zW46bQ7'
id = 'personalinformation-test::904a8b64-42c6-4876-9174-7d23adfe563c'
uuid = '904a8b64-42c6-4876-9174-7d23adfe563c::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qme4LkdURYs1nEpK4VhrmvyPbPpPDw6ZCkVHYMFgMa9VBT'
id = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
uuid = '84b0e8f9-cc77-43b4-94ad-a41582d7b704::b780f70e-5d3d-48da-97cb-8cfaf58d28e2'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/PyEyOU/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/PyEyOU/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/PyEyOU/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/PyEyOU/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/PyEyOU/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::904a8b64-42c6-4876-9174-7d23adfe563c'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/PyEyOU/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::84b0e8f9-cc77-43b4-94ad-a41582d7b704'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/PyEyOU/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
