bridges = []
persistence_dir = '/tmp/tmp.Hpt3E1hjCM/tryorama/wRfwzc'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'mark::projects::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCj9nhz7Vy57w79wWY5R9h87Ek9sew8su4Y6uwEE6BvjkfFK6BEXZIbnts53i'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'mark::origins::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcScjnvEtwOkhrbuxbuOQNppE4hnehjajaz9HQ9P7ecZ3zg4NtI7eO5RSK8gwva'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCI3ych9CVQexjezVGpBrpSOkwvtzcvJNQwkF7sSodyrueUmP3ZWMDu6ivy7z'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCIfKTErNm3emd4cpXrMFqa8Jfkko8gKR79HR54o643VCgq3xrhhkKh7v3w3r'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCik3k9yP8B6Nfn5t4ArkItg95Bi9d7TMNriiJiduioaieoWco93rMKZbwvai'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCjsT79KVI4Zrks8t4uOQYNIAzhxhimRgr4dGEn98wg63z9D8ZqnwBH4s6cda'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSCICeQdeNesbwabdxpT5ZYHNB4u336iBb7WC4UDVgcp8xvDdfqARHKchevqqr'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::ae445dd9-e53e-454d-85db-bfb3172413d5'
public_address = 'HcSci68m9ii74p56h3XjF9GMt4pq4s3mpqoGFBmdn7fn6prdqfqqCjjmn48hoor'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmUfuphzKGDCPrE4PHSwi5afC1GeKk4aPQhWfs4Ard3RaG'
id = 'projects-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmWyriGuATgo1GFQgTptmfCxeLZXGMXyadLtCANQDkY3K3'
id = 'origins-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmcDhhqTmDs23m3Y5BkdBzQfGL1eYDSfAnnsBMQoCwMqvG'
id = 'kanban-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQ5y4jfcu9qXKPp5ruu8ooAzvJ2Lb4Kzwmr9UpQLAoobR'
id = 'notes-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmXDkj9aqA28zUksXSwonAF3nSzPvgycUnZEqsyAvJ7CAu'
id = 'tasks-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmbWbsBwqnuGBUvnBhVXSQ3f5qMGihdEFPsyDp4eK3ognT'
id = 'fields-test'
uuid = 'ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmZqdk2bV6ooVSMx9jyzGCtAfZSmVeMcpaeufxUeUVsCfe'
id = 'personalinformation-test::9b1f69e0-5d7e-4930-b6b3-7c9d4436c660'
uuid = '9b1f69e0-5d7e-4930-b6b3-7c9d4436c660::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qma8Xq6UMmagyzuug5iM8YjrVe73caRyNrQrtXHMWBoVU7'
id = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
uuid = '33fd973f-e5ec-45c2-b4e6-bbd294cae814::ae445dd9-e53e-454d-85db-bfb3172413d5'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/wRfwzc/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/wRfwzc/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/wRfwzc/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/wRfwzc/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/wRfwzc/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/wRfwzc/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::9b1f69e0-5d7e-4930-b6b3-7c9d4436c660'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/wRfwzc/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::33fd973f-e5ec-45c2-b4e6-bbd294cae814'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.Hpt3E1hjCM/tryorama/wRfwzc/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
