bridges = []
persistence_dir = '/tmp/tmp.2oszwWo19C/tryorama/hakQcL'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'mark::projects::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCjRCKrpEwabeftxF69CUjGa6zqe74gj6oIJnXJzvrsy93Jo8RPDF6B5A6m6z'
test_agent = true

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'mark::origins::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCI6a435ghb3j76RTpGzwPi64r5jrfgW4YPwHO36STpyik77S63BRAbpfEqgr'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScJ3pugNOCcjhzreQI5CekaSCbn8absV7smM9djEQraeu8Aoyyk86AkH57vja'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCiC977bt487noOb6EuqT4JocRbwqkiCuyP9DggO9zzp5ya8b34QcXCcd48za'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSCjC7X8QH8u6sjec3bWGfoP9tjtw3rsppb53DJVtSiok666B4yZrtTGIeeena'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcSci9YxWNKUqb6bzbNwUYsgeD8zyt8kwPcm7piJ6rt8os7j8x5HY7Hp7iHknca'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScJd7tQnAqvmosnxQsubeaBjrsqwzc59ZwRHzYG4Swdmbwkkrr6Jw4MYxbf8z'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::9a0d0246-e446-4a1e-909a-5485a1a56b0e'
public_address = 'HcScI8goe6hAd3dbbcA6y4KOAmVI6avbqbS9s8bsHtVoxamwQrSCBDRV5gxyb4z'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmZy6baFVXRqJwEbTa2PzEQTAwSXLcFh8wjZLtUkYRBb9Q'
id = 'projects-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmUnZVzRcXX2nBYgfpTJDVQVTYHnX3R7bwJ1WRdUn4JmPF'
id = 'origins-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmTxSTHTjwMwEW6sUizD8euRk2RV6kLqkXCT4NBXxMkgzq'
id = 'kanban-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmQDHS5v5V1cCtik1RiZzBiZLdAmrFqCffe74oHWh2DqSW'
id = 'notes-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmdHzqRj1X2woEa5wxKVx4VHx8HfEK7jKyoXdhZFPLvFpN'
id = 'tasks-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmRzbVi6sBZ15yAS3ri7WXakpJ9XtbTMpkdbYhGS3qLcVU'
id = 'fields-test'
uuid = '9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'Qma26UBg3Bi8JdyAz1MiGW2UKqZg2Ypg8jtHJDwcWy6iDR'
id = 'personalinformation-test::7cf87106-f21a-40e2-b148-ba3e1b0bf2e7'
uuid = '7cf87106-f21a-40e2-b148-ba3e1b0bf2e7::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmeYjU1hubDJth1NWHCmgPEddPzhnFQDkjoY99ttg9oV67'
id = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
uuid = '93309f35-de11-4f62-8af4-af46a19ab638::9a0d0246-e446-4a1e-909a-5485a1a56b0e'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/hakQcL/projects'
type = 'lmdb'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/hakQcL/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/hakQcL/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/hakQcL/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/hakQcL/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/hakQcL/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::7cf87106-f21a-40e2-b148-ba3e1b0bf2e7'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/hakQcL/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::93309f35-de11-4f62-8af4-af46a19ab638'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.2oszwWo19C/tryorama/hakQcL/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
