bridges = []
persistence_dir = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'projects'
keystore_file = '[UNUSED]'
name = 'mark::projects::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScjg49MQR9Y88S6g55oxcc48v5EPwwnixO9MzmHjxe96dn93f8z4i8qe37ynZ'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'mark::57c01ed8-30ae-4fca-b6f9-40192821fed2::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScjo6jwHP97cs4nogyxV8KtQH9r75p3qFfe3Q4ffG6k9hb3iqcoOr54PPtszz'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'mark::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSCjOPWEX5WjoqeohDvYBa3n5CIpx8mj9q6NIAZ8d3msteqnEenmCVW5j9tuji'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScIKTKUODeedykfvnm7f3ahA9Q4VrqurVa78on484dK75wQbxOYDdk6ngj7sa'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSci3H3iPWCA6y5e4pTi85qpE4HEa4yp4E6eZJRAFJ6og8qIaTVzIgXx5fcv6r'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSCi6Toe9s568TJ6r6Jj9T3CABqie5jbuk7CmYym4Jfn7j3PWaA3IbEuxqwtca'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcSCISUDzcUajxst3mhonP3tScstmh4fhu5qb7OHhYfayv6icGO689NnbNcxvpr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScjrcd7W8687OcrxfZkxP3JB7paa548ISP7ojUbrdapk4qf68USwxPs8Wkxdz'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'mark::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::ecf48d70-adf7-4ed8-b304-feb39a619d77'
public_address = 'HcScIb4q8hCZk4p6mqJFjzgGkimtkb9arMKrw6MN6x8Xr3xr49zy9637f8jfk4z'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmR94wEXeaXxXnNFkd2cNUcahYDyFrpfPuXwqcebs438DV'
id = 'projects-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmZ6mb7pkyh34ifEBcYyceHBUcJXsAQwJTML7vJAQqiLvM'
id = 'origins-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmXWq4z1XeeHaDcwYNeEaj3B1wKjbpEcaxLAZ893NRzrfw'
id = 'origins-test::2e0bc1c2-fa7e-4686-a13e-70dc89d99c8a'
uuid = '2e0bc1c2-fa7e-4686-a13e-70dc89d99c8a::ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmWiYJtUvruiEC82iCdk6gKUfwKCvoTwopfms4t7LeH7PA'
id = 'kanban-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmRWrXvPsKg2VQzfQXeQRJuwMsrkhsPp5G5u6ryfy19bK3'
id = 'notes-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmUnpSCbfYjgoLJspA3h1hfaibYQtMzKTjYpV2i3V2j3qb'
id = 'tasks-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmXwWQLUBYQyCHp89pG61mX5TQmsFS6o9EbyHsvC3rhFs5'
id = 'fields-test'
uuid = 'ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmUDsKuUM5QeEZ874yUT49oRNqyiuD9LT7qjnQWhvpfDmN'
id = 'personalinformation-test::6a184534-a799-46c9-af5b-334a010fbbd4'
uuid = '6a184534-a799-46c9-af5b-334a010fbbd4::ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmZPfbLLeazEKr36J4fdA3GcTzzWtMjYzaup2t5Ghaz4VV'
id = 'freckles-test::8c3dff43-f9a3-4b53-8548-7512ce72dbfc'
uuid = '8c3dff43-f9a3-4b53-8548-7512ce72dbfc::ecf48d70-adf7-4ed8-b304-feb39a619d77'

[[instances]]
agent = 'projects'
dna = 'projects-test'
id = 'projects'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq/projects'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins-test::2e0bc1c2-fa7e-4686-a13e-70dc89d99c8a'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::6a184534-a799-46c9-af5b-334a010fbbd4'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::8c3dff43-f9a3-4b53-8548-7512ce72dbfc'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.udyD72ci2B/tryorama/9r0Kwq/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'projects'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
