bridges = []
persistence_dir = '/tmp/tmp.MHR9Pez8g4/tryorama/2StxuU'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'origins'
keystore_file = '[UNUSED]'
name = 'mark::origins::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcScJJh6o9774UUufskpExb8cYtkcimwm5Ac3yhXRPxqzkurUvr3YwuI3Sr9zwa'
test_agent = true

[[agents]]
id = 'kanban'
keystore_file = '[UNUSED]'
name = 'mark::kanban::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCj3kDiUqnzfqsa5Aty8nAsCWop5s7rC5XZCzedr4z5wk6xsn9WN3uD6P4yfa'
test_agent = true

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'mark::notes::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCi6OwMDCQeahpasXi9aiPmiakbquhwTFicrdVpqurrtfe8ynKIEqhJ8v94wa'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'mark::tasks::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCjavQzaTgbhy3qki5Ac78NeodIq4wjKTQfMtY79drioj4oDut5P3jbcaiski'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCJHJaZ66995Mb8p9BzQ9r8AhEU9xt79mbEOP4H9Aobr9aYjM5U79446Bcqdi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSci3kBnxzeqj4obhuFD69t8IC9OH6v3uZsHze7OKhn6vkdFbmbryVWs5ucyrz'
test_agent = true

[[agents]]
id = 'freckles'
keystore_file = '[UNUSED]'
name = 'mark::freckles::3169c5fb-64b8-4668-949d-ebafc253d684'
public_address = 'HcSCjXZVQvopggd85ySqDw4xuqS5r5543S9XwC7hzInwvvgz5CVF83XBe777z7a'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeKjDnW2RYQwTguAtiaHyhBiEkroP4QcHSsWdnztaGmCT'
id = 'origins-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmY5hzbvPET4W2ZPyzhdpbNd1tqkUSvAwSnXQWw44jMbyU'
id = 'kanban-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYULeLPPfiC8yAhvwvxcjYgAmzajtezuWB3JiJ7XHCqe4'
id = 'notes-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmaBbotBPBSgLiqmFwgqX2Tf65rQ4CrdKKwuemDtDjwqYo'
id = 'tasks-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmUqFKMUNmgZdMvsK1jdBwZ3MtEaJKurPFQRFG4MDDioVN'
id = 'fields-test'
uuid = '3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmYjTRL1EEWnY7FdVyn65pEmj5PTvFgwWxS2rGCddRW5SB'
id = 'personalinformation-test::78d661d2-4bf9-481b-abc7-d26da3c09180'
uuid = '78d661d2-4bf9-481b-abc7-d26da3c09180::3169c5fb-64b8-4668-949d-ebafc253d684'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmY5iSifHVjZwBYheJzX9zrZwJBxVtjkqos1jksvkub8ox'
id = 'freckles-test::051792a2-1184-42ce-9f84-a8b80955b413'
uuid = '051792a2-1184-42ce-9f84-a8b80955b413::3169c5fb-64b8-4668-949d-ebafc253d684'

[[instances]]
agent = 'origins'
dna = 'origins-test'
id = 'origins'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2StxuU/origins'
type = 'lmdb'

[[instances]]
agent = 'kanban'
dna = 'kanban-test'
id = 'kanban'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2StxuU/kanban'
type = 'lmdb'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2StxuU/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2StxuU/tasks'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2StxuU/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::78d661d2-4bf9-481b-abc7-d26da3c09180'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2StxuU/personalinformation'
type = 'lmdb'

[[instances]]
agent = 'freckles'
dna = 'freckles-test::051792a2-1184-42ce-9f84-a8b80955b413'
id = 'freckles'

[instances.storage]
path = '/tmp/tmp.MHR9Pez8g4/tryorama/2StxuU/freckles'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'origins'

[[interfaces.instances]]
id = 'kanban'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = 'freckles'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
