bridges = []
persistence_dir = '/tmp/tmp.wkFrnuddpG/tryorama/jNqnb5'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'columns'
keystore_file = '[UNUSED]'
name = 'bob::columns::e04289d6-7ac2-442c-bf69-abdb11dbace4'
public_address = 'HcSCIKAw38BCazhf643ATqMQrBYk5otezZeFeBQFonfum87rgB9k6Uxymo5jtfz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmWfFMm6yi75eCoaK3FfRof2eDiRRzc9cZ6gkiQrxvj1J7'
id = 'columns-test'
uuid = 'e04289d6-7ac2-442c-bf69-abdb11dbace4'

[[instances]]
agent = 'columns'
dna = 'columns-test'
id = 'columns'

[instances.storage]
path = '/tmp/tmp.wkFrnuddpG/tryorama/jNqnb5/columns'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'columns'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
