bridges = []
persistence_dir = '/tmp/tmp.iLzYEUUCEx/tryorama/8fWrPW'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'bob::notes::7810d194-2287-4178-a6b4-bd4aadd54e0c'
public_address = 'HcScJOezjF6Ap4kqddwGSYxbJPwp7euntD9ZmJ6iIP8pxxhjatsUfa6kgvzv8ki'
test_agent = true

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'bob::tasks::7810d194-2287-4178-a6b4-bd4aadd54e0c'
public_address = 'HcSCIKeC9vatpar8pavoVu4YH3w3Fatc37K6zBSdD9jKdvtd4983ZSV47OrPf8A'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'Qmc1vmVPN5fCe1AvUpmbN4ibHxURMf7GDJZAHcQjMkeXrN'
id = 'notes-test'
uuid = '7810d194-2287-4178-a6b4-bd4aadd54e0c'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmPyL2nD1zupb9fjbsAXkPTcnuiSndGAgsmqKFH5BRWLwy'
id = 'tasks-test'
uuid = '7810d194-2287-4178-a6b4-bd4aadd54e0c'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.iLzYEUUCEx/tryorama/8fWrPW/notes'
type = 'lmdb'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.iLzYEUUCEx/tryorama/8fWrPW/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'notes'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
