bridges = []
persistence_dir = '/tmp/tmp.4dgCkC2Dj3/tryorama/xp8zXq'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'phil::notes::c5b6abc5-d789-4b9a-aa58-82572674567a'
public_address = 'HcSCj3Ts6Dq3ONrcap6WZgZiz7bRarg459aFkr7VD4o4NfhzS47K8cBFwZDdh7r'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYnDttFghq7LP6Q7WfyhT5NZscxkccQzKQrkp3UkGCgVv'
id = 'notes-test'
uuid = 'c5b6abc5-d789-4b9a-aa58-82572674567a'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.4dgCkC2Dj3/tryorama/xp8zXq/notes'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'notes'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
