bridges = []
persistence_dir = '/tmp/tmp.19VUmm1ZOU/tryorama/ANN77m'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'lucy::notes::fb48fb12-2e79-45e3-94e6-b4896ddfc1d9'
public_address = 'HcSCjbFhHfiibvxksyJOh9TKqF576s8b5j3TxyIDaqmme36mVpUUvjbJxaokx4r'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmUxmByuzb6hF4whmMrr6MNWFGrSC85XrbRTgQWs4B7JJn'
id = 'notes-test'
uuid = 'fb48fb12-2e79-45e3-94e6-b4896ddfc1d9'

[[instances]]
agent = 'notes'
dna = 'notes-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.19VUmm1ZOU/tryorama/ANN77m/notes'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'notes'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
