bridges = []
persistence_dir = '/tmp/tmp.iLzYEUUCEx/tryorama/eIyUPn'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'bob::tasks::7db5d34b-0363-4109-9f2f-7019114e7f8b'
public_address = 'HcSCJo4cstnFxkyqbkqqXHDxjYuf7q3p36zk786KN8OwA7n8Ro5GX9jyrNc8wnr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmb1kXRuLg8ot68Cp2SN23m6oRyF7G56X1XHgeUew7zxUJ'
id = 'tasks-test'
uuid = '7db5d34b-0363-4109-9f2f-7019114e7f8b'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.iLzYEUUCEx/tryorama/eIyUPn/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
