bridges = []
persistence_dir = '/tmp/tmp.4dgCkC2Dj3/tryorama/QTVddK'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::6ebb9bca-6329-47f4-9c47-7f98d0c889c4'
public_address = 'HcSCiGb5abCrxoj3jfU94AXc7TTgmqmegzriMq7OvKczneiuxB7RjM5MGt6gt9z'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmTJkXSd9rpCeCy6fjchM19TGMCAiyFCB7o9Di5mHdesHn'
id = 'tasks-test'
uuid = '6ebb9bca-6329-47f4-9c47-7f98d0c889c4'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.4dgCkC2Dj3/tryorama/QTVddK/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
