bridges = []
persistence_dir = '/tmp/tmp.4dgCkC2Dj3/tryorama/O938Do'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'phil::tasks::0e0119e8-2727-4794-b044-8b2ce2cf9881'
public_address = 'HcSci3o6RgXQG4n9gf5Orsaf4fYWkurksFGqinYfadspn97t7AeJ6Fk8xkTkusa'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmeKjTA89b7NHtFV3rHoSqiu8ga6D3fgvSGz7GczWhwYQ6'
id = 'tasks-test'
uuid = '0e0119e8-2727-4794-b044-8b2ce2cf9881'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.4dgCkC2Dj3/tryorama/O938Do/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
