bridges = []
persistence_dir = '/tmp/tmp.wkFrnuddpG/tryorama/1oUfGI'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tasks'
keystore_file = '[UNUSED]'
name = 'lucy::tasks::0fc7cd9e-c4a4-419e-93c1-161659ba586b'
public_address = 'HcSCJ3S66PIoGNz7q4oGwfbrI9RessoacfXg3Msby4Yajso75h3oczf5Qjjmrxr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmTXxZYdPevd8WLGh7kdbpaUxjRKy3yCjAe6GdM2hpPoPJ'
id = 'tasks-test'
uuid = '0fc7cd9e-c4a4-419e-93c1-161659ba586b'

[[instances]]
agent = 'tasks'
dna = 'tasks-test'
id = 'tasks'

[instances.storage]
path = '/tmp/tmp.wkFrnuddpG/tryorama/1oUfGI/tasks'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tasks'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
